Repository lightningnetwork/lnd, pull requests merged in 2018-07, with the labels that each got.

#1458 channeldb: expand codec to include net.Addr types
  channeldb/addr.go
  channeldb/addr_test.go
  channeldb/channel.go
  channeldb/codec.go
  channeldb/forwarding_log.go
Labels: database

#1536 docs/INSTALL: fix mismatched code blocks
  docs/INSTALL.md
Labels: P4, needs review

#1125 channeldb+lnrpc: re-work invoicing API to implement robust streaming notification delivery
  channeldb/db.go
  channeldb/invoice_test.go
  channeldb/invoices.go
  channeldb/migrations.go
  channeldb/payments.go
  cmd/lncli/commands.go
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  invoiceregistry.go
  lnd_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/node.go
  rpcserver.go
  server.go
Labels: P2, database, payments, rpc

#1547 channeldb: add new migration to finalize invoice migration for outgoi…
  channeldb/db.go
  channeldb/migrations.go
Labels: P1, bug fix, database, payments

#1554 Filter out bitcoind mempool spends
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/interface_test.go
Labels: P1

#1505 fundingmanager: send messages directly to peers
  discovery/gossiper.go
  discovery/gossiper_test.go
  fundingmanager.go
  fundingmanager_test.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  lnd.go
  lnpeer/peer.go
  peer.go
  server.go
Labels: P2, first pass review done, funding, needs testing, server

#1578 invoiceregistry: make the invoice ntfn chan buffered
  invoiceregistry.go
Labels: P2, optimization, payments

#1371 server: prune link nodes without any open channels
  channeldb/db.go
  channeldb/graph.go
  channeldb/graph_test.go
  channeldb/nodes.go
  channeldb/nodes_test.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_watcher.go
  contractcourt/channel_arbitrator.go
  lnd_test.go
  peer.go
  server.go
Labels: P2, channels, first pass review done, needs testing, routing nodes

#1600 channeldb+routing: prune unconnected graph vertexes on start up
  channeldb/graph.go
  channeldb/graph_test.go
  routing/router.go
Labels: P2, bug, database, graph

#1531 Only act on confirmed spends
  breacharbiter.go
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/interface.go
  chainntnfs/interface_test.go
  chainntnfs/neutrinonotify/neutrino.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_watcher.go
  contractcourt/chain_watcher_test.go
  contractcourt/contract_resolvers.go
  discovery/gossiper_test.go
  fundingmanager_test.go
  htlcswitch/mock.go
  lnd_test.go
  lntest/node.go
  mock.go
Labels: P2, first pass review done, needs testing, notifications, tests

#1387 multi: send a channel update with disabled flag set on channel close
  chancloser.go
  contractcourt/chain_arbitrator.go
  lnd_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  peer.go
  routing/notifications.go
  rpcserver.go
  server.go
Labels: P2, channel closing, needs review, needs testing

#1617 lnwallet/size: correct commit to-local and 2nd stage script/witness sizes
  breacharbiter.go
  lnwallet/size.go
  utxonursery.go
Labels: HTLC, P1, fees, needs review, safety

#1613 make: if timeout not set, use 20m instead of default 10m
  make/testing_flags.mk
Labels: P1

#1643 [htlcswitch/link] use FailFinalExpiryTooSoon as exit hop
  htlcswitch/link.go
  htlcswitch/link_test.go
Labels: HTLC, P3, htlcswitch, needs review

#1582 [integration tests] assert waiting close also for force closes
  lnd_test.go
Labels: P2, needs review, testing

#1655 routing: ensure generateSphinxPacket can handle being passed empty set of routes
  routing/router.go
  routing/router_test.go
Labels: P1, bug, needs review

#1657 discovery/gossiper: copy bolt key to prevent panic
  discovery/gossiper.go
Labels: brainstorming, safety
