Repository lightningnetwork/lnd, pull requests merged in 2018-04, with the labels that each got.

#1001 brontide/listener: make handshake asynchronous
  brontide/listener.go
  brontide/noise_test.go
Labels: p2p

#992 Makefile docs
  docs/INSTALL.md
  docs/MAKEFILE.md
Labels: documentation, golang/build system

#1014 Correcting install docs to add path for upgrade instructions section
  docs/INSTALL.md
Labels: documentation

#1006 gitignore: exclude local lnd+lncli binaries
  .gitignore
Labels: golang/build system

#912 docker: replace bash shells with last command
  docker/btcd/start-btcctl.sh
  docker/btcd/start-btcd.sh
  docker/lnd/start-lnd.sh
  docker/ltcd/start-ltcctl.sh
  docker/ltcd/start-ltcd.sh
Labels: docker

#929 aezeed: add tests and README
  aezeed/README.md
  aezeed/cipherseed_test.go
Labels: crypto, documentation, testing

#798 year Update LICENSE
  LICENSE
Labels: documentation

#1007 htlcswitch: fix periodic calculation of satoshis sent/received
  htlcswitch/switch.go
Labels: htlcswitch

#744 lnd: use single asterisk for gitignore wildcards
  .gitignore
Labels: code health

#958 Include a pending_balance in channelbalance response
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: channels, rpc

#969 chainntnfs: optionally only notify spends on block inclusion
  breacharbiter.go
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/interface.go
  chainntnfs/interface_test.go
  chainntnfs/neutrinonotify/neutrino.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_watcher.go
  contractcourt/contract_resolvers.go
  discovery/gossiper_test.go
  fundingmanager_test.go
  mock.go
Labels: backend, notifications

#966 Make log rotation configurable
  config.go
  log.go
  sample-lnd.conf
Labels: config, logging

#1051 remove witness_only in doc
  docs/grpc/python.md
Labels: documentation, gRPC

#956 [refactor] lnwallet/channel: add NewLocalForceCloseSummary
  contractcourt/chain_arbitrator.go
  contractcourt/channel_arbitrator.go
  lnwallet/channel.go
Labels: channels, code health

#898 Wrong BOLT11 prefix in regtest
  zpay32/invoice_test.go
Labels: payments

#1020 Add version field to GetInfo RPC endpoint
  .gitignore
  lnrpc/README.md
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: rpc

#1042 updated js docs for macaroons and grpc ssl cipher
  docs/grpc/javascript.md
Labels: documentation, gRPC

#1095 docs: update Go version to 1.9 in Contribution Checklist
  docs/code_contribution_guidelines.md
Labels: documentation

#1096 main: Stop setting GOMAXPROCS to NumCPU explicitly
  lnd.go
Labels: code health, golang/build system

#746 Fix a-vs-an typos
  autopilot/graph.go
  autopilot/prefattach.go
  brontide/conn.go
  brontide/noise.go
  chainntnfs/interface_test.go
  chainntnfs/neutrinonotify/neutrino.go
  channeldb/channel.go
  channeldb/graph.go
  channeldb/graph_test.go
  channeldb/invoices.go
  channeldb/nodes.go
  contractcourt/briefcase.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_watcher.go
  discovery/gossiper.go
  htlcswitch/queue.go
  htlcswitch/switch.go
  htlcswitch/test_utils.go
  lnd_test.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/node.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/interface.go
  lnwallet/script_utils.go
  lnwire/accept_channel.go
  lnwire/commit_sig.go
  lnwire/error.go
  lnwire/init_message.go
  lnwire/open_channel.go
  lnwire/update_add_htlc.go
  lnwire/update_fail_htlc.go
  lnwire/update_fee.go
  lnwire/update_fulfill_htlc.go
  nursery_store.go
  peer.go
  routing/chainview/interface.go
  routing/chainview/neutrino.go
  routing/errors.go
  routing/router.go
  routing/validation_barrier.go
  rpcserver.go
  utxonursery.go
Labels: documentation

#1081 Include millisatoshis in queryroutes
  lnd_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: fees, rpc

#1080 Added suggestion to INSTALL.md
  docs/INSTALL.md
Labels: documentation

#846 multi: support multi-hop payments over private channels
  cmd/lncli/commands.go
  lnd_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  routing/missioncontrol.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/router.go
  routing/router_test.go
  rpcserver.go
  zpay32/invoice.go
  zpay32/invoice_internal_test.go
  zpay32/invoice_test.go
Labels: multi-hop, payments

#1017 Contract court acting on confirmed chain events
  breacharbiter.go
  breacharbiter_test.go
  channeldb/channel.go
  channeldb/channel_test.go
  channeldb/codec.go
  channeldb/db.go
  contractcourt/briefcase.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_watcher.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  htlcswitch/circuit_map.go
  htlcswitch/link.go
  htlcswitch/switch.go
  lnd_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/harness.go
  lnwallet/channel.go
  peer.go
  rpcserver.go
Labels: commitments, notifications, state machine
