Repository lightningnetwork/lnd, pull requests merged in 2019-01, with the labels that each got.

#2248 channeldb/db: prevent filtering channels with unconfirmed close txs
  channeldb/channel_test.go
  channeldb/db.go
Labels: P2, bug fix, database, needs review

#2354 channeldb+lnrpc: invoice state
  channeldb/invoice_test.go
  channeldb/invoices.go
  channeldb/migrations.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  invoiceregistry.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: P2, database, payments

#2368 keychain: extend DerivePrivKey to derive based on pubkey+KeyFamily
  keychain/btcwallet.go
  keychain/derivation.go
  keychain/interface_test.go
Labels: P2, backups, crypto, enhancement

#2355 invoices: create package
  invoices/invoiceregistry.go
  invoices/log.go
  log.go
  rpcserver.go
  server.go
  witness_beacon.go
Labels: database, enhancement, payments

#1975 [tests] Force tick on FwdEventTicker
  htlcswitch/switch_test.go
Labels: testing, tests, travis

#2293 [autopilot] weighted choice unit tests and optimizations
  autopilot/agent.go
  autopilot/choice.go
  autopilot/choice_test.go
Labels: P3, autopilot, needs review, needs testing, testing

#2118 make: ensure make fmt is run with -s flag
  Makefile
Labels: P3, needs review

#2417 server: configurable min backoff
  config.go
  server.go
Labels: p2p, server

#2341 [autopilot] Decouple agent constraints from heuristics
  autopilot/agent.go
  autopilot/agent_constraints.go
  autopilot/agent_constraints_test.go
  autopilot/agent_test.go
  autopilot/choice.go
  autopilot/choice_test.go
  autopilot/heuristic_constraints.go
  autopilot/interface.go
  autopilot/prefattach.go
  autopilot/prefattach_test.go
  pilot.go
Labels: P2, autopilot, enhancement

#2433 watchtower/lookout: correct txid + session id logging
  watchtower/lookout/lookout.go
  watchtower/lookout/punisher.go
Labels: logging, trivial, watchtower

#2416 netann: move NodeSigner out of main package
  netann/node_signer.go
  server.go
Labels: code health, trivial

#2449 routing/router: avoid naked spew of channel policies
  routing/router.go
Labels: logging, resource usage, routing, trivial

#2418 rpcserver: add connectpeer log, fix existing formatting
  rpcserver.go
Labels: logging, rpc, trivial

#2259 update lnd dockerfile image
  docker/lnd/Dockerfile
Labels: P3, docker, needs review, needs testing

#2445 netann: Add NANN subsystem logger
  log.go
  netann/log.go
Labels: logging, trivial

#2289 rpcserver+lnd_test: fixing unassigned UnsettledBalance field
  lnd_test.go
  rpcserver.go
Labels: channels, enhancement, first pass review done, gRPC, needs testing

#2430 lnwallet: Remove breach txn from NewBreachRetribution
  breacharbiter_test.go
  contractcourt/chain_watcher.go
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: wallet, watchtower

#2431 lnwallet: Add keyring and remote CSV delay to BreachRetribution
  contractcourt/chain_watcher.go
  lnwallet/channel.go
Labels: wallet, watchtower

#2446 lncfg: NetAddress parsing
  lncfg/address.go
  lncfg/address_test.go
Labels: config, watchtower

#2462 lnwire: ensure we precisely encode the length for onion errors w/ cha…
  lnwire/onion_error.go
  lnwire/onion_error_test.go
Labels: bug fix, wire protocol

#2275 fundingmanager: rejects funding requests with number of confirmations too large
  breacharbiter_test.go
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/bitcoindnotify/bitcoind_dev.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/btcdnotify/btcd_dev.go
  chainntnfs/neutrinonotify/neutrino.go
  chainntnfs/neutrinonotify/neutrino_dev.go
  chainntnfs/txnotifier.go
  chainntnfs/txnotifier_test.go
  channeldb/channel.go
  channeldb/channel_test.go
  fundingmanager.go
  fundingmanager_test.go
  htlcswitch/test_utils.go
  lnwallet/errors.go
  lnwallet/interface_test.go
  lnwallet/reservation.go
  lnwallet/test_utils.go
  lnwallet/transactions_test.go
  test_utils.go
Labels: P2, bug fix, funding, needs testing

#2397 [bugfix] Process fee updates as any other update message
  htlcswitch/link.go
  htlcswitch/switch.go
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: P2, bug fix, commitments

#2198 multi: add ability to sweep all coins in the the wallet to an addr to sendcoins
  breacharbiter.go
  cmd/lncli/commands.go
  contractcourt/contract_resolvers.go
  lnd_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnwallet/btcwallet/signer.go
  lnwallet/interface.go
  lnwallet/reservation.go
  lnwallet/test_utils.go
  lnwallet/wallet.go
  lnwallet/witnessgen.go
  rpcserver.go
  server.go
  sweep/fee_estimator_mock_test.go
  sweep/input.go
  sweep/sweeper.go
  sweep/sweeper_test.go
  sweep/txgenerator.go
  sweep/walletsweep.go
  sweep/walletsweep_test.go
Labels: P3, needs review, needs testing, rpc, utxo sweeping, wallet

#2439 wtpolicy: migrate to using wtpolicy.Policy + blob bitvector flags
  watchtower/blob/justice_kit.go
  watchtower/blob/justice_kit_test.go
  watchtower/blob/type.go
  watchtower/blob/type_test.go
  watchtower/lookout/justice_descriptor_test.go
  watchtower/lookout/lookout.go
  watchtower/lookout/lookout_test.go
  watchtower/wtdb/session_info.go
  watchtower/wtpolicy/policy.go
  watchtower/wtserver/server.go
  watchtower/wtserver/server_test.go
  watchtower/wtwire/create_session.go
  watchtower/wtwire/create_session_reply.go
  watchtower/wtwire/wtwire.go
Labels: needs review, watchtower, wtserver

#2448 watchtower pkg
  log.go
  watchtower/conf.go
  watchtower/conf_experimental.go
  watchtower/config.go
  watchtower/errors.go
  watchtower/interface.go
  watchtower/log.go
  watchtower/standalone.go
Labels: config, watchtower

#1621 [Integration tests] Split chain backend and miner
  .gitignore
  lnd_test.go
  lntest/btcd.go
  lntest/harness.go
  lntest/node.go
Labels: P3, backend, needs review, test flake, testing

#2320 [watchtower] add wtpolicy.Policy and wtserver message logging
  watchtower/wtserver/server.go
  watchtower/wtwire/summary.go
Labels: watchtower, wtserver, wtwire

#2402 docs/INSTALL.md: update Go installation options for Linux
  docs/INSTALL.md
Labels: P3, documentation, golang/build system

#2494 [trivial] build lnd-itest before flakehunting
  Makefile
Labels: trivial

#2499 docs: add new section to contribution guidelines for go mod replace
  docs/code_contribution_guidelines.md
Labels: P3, documentation, enhancement

#2504 build: update release.sh to contain vendor archive + source code
  release.sh
Labels: P3, golang/build system, releases

#2247 rpcserver: forward gRPC proxy requests to localhost when listening on all interfaces
  rpcserver.go
Labels: P3, gRPC, needs review, needs testing, networking

#2460 Support the max_htlc field from ChannelUpdates
  autopilot/graph.go
  channeldb/error.go
  channeldb/graph.go
  channeldb/graph_test.go
  discovery/chan_series.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/utils.go
  fundingmanager.go
  fundingmanager_test.go
  lnwallet/errors.go
  lnwallet/interface_test.go
  lnwallet/reservation.go
  lnwire/channel_update.go
  lnwire/lnwire.go
  lnwire/lnwire_test.go
  lnwire/onion_error_test.go
  peer.go
  routing/ann_validation.go
  routing/notifications.go
  routing/notifications_test.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/router.go
  routing/router_test.go
  rpcserver.go
  server.go
Labels: P2, discovery, enhancement, spec

#2075 contractcourt: settle invoice when claiming HTLC on-chain
  contractcourt/chain_arbitrator.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  contractcourt/htlc_success_resolver.go
  contractcourt/htlc_timeout_resolver.go
  lnd_test.go
  lnwallet/channel.go
  server.go
Labels: P2, bug fix, contracts, htlcswitch

#2350 [Autopilot] Add heuristic dry-run option
  autopilot/agent.go
  autopilot/agent_test.go
  autopilot/combinedattach.go
  autopilot/interface.go
  autopilot/manager.go
  autopilot/prefattach.go
  cmd/lncli/autopilotrpc_active.go
  config.go
  lnrpc/autopilotrpc/autopilot.pb.go
  lnrpc/autopilotrpc/autopilot.proto
  lnrpc/autopilotrpc/autopilot_server.go
  pilot.go
Labels: P3, autopilot, enhancement

#2370 chanbackup: add new package implementing static channel backups
  chanbackup/backup.go
  chanbackup/backup_test.go
  chanbackup/backupfile.go
  chanbackup/backupfile_test.go
  chanbackup/crypto.go
  chanbackup/crypto_test.go
  chanbackup/log.go
  chanbackup/multi.go
  chanbackup/multi_test.go
  chanbackup/pubsub.go
  chanbackup/pubsub_test.go
  chanbackup/recover.go
  chanbackup/recover_test.go
  chanbackup/single.go
  chanbackup/single_test.go
  keychain/derivation.go
Labels: P2, backups, safety

#2505 build: more reliable coverage using go-acc
  Makefile
Labels: bug fix, code health, golang/build system

#2371 channeldb: prepatory modifications for full SCB implementation
  breacharbiter_test.go
  channeldb/channel.go
  channeldb/db.go
  channeldb/db_test.go
  channeldb/error.go
  channeldb/graph.go
  channeldb/migrations.go
  channeldb/nodes.go
  contractcourt/chain_arbitrator.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  peer.go
  rpcserver.go
Labels: P2, backups, database, enhancement
