Repository lightningnetwork/lnd, pull requests merged in 2019-12, with the labels that each got.

#3659 chanfunding: create new package to abstract over funding workflows
  channeldb/channel.go
  fundingmanager.go
  fundingmanager_test.go
  lnwallet/chanfunding/assembler.go
  lnwallet/chanfunding/canned_assembler.go
  lnwallet/chanfunding/coin_select.go
  lnwallet/chanfunding/coin_select_test.go
  lnwallet/chanfunding/log.go
  lnwallet/chanfunding/wallet_assembler.go
  lnwallet/interface_test.go
  lnwallet/reservation.go
  lnwallet/wallet.go
  log.go
  mock.go
Labels: funding, v0.9.0

#3782 routing: improve equal cost route comparison
  routing/heap.go
  routing/pathfind.go
  routing/pathfind_test.go
Labels: payments, routing, v0.9.0

#3584 docker: fix ltcd ports
  docker/btcd/start-btcctl.sh
  docker/btcd/start-btcd.sh
  docker/ltcd/Dockerfile
  docker/ltcd/start-ltcctl.sh
  docker/ltcd/start-ltcd.sh
Labels: docker, litecoin, v0.9.0

#3743 lnwire: assert sorted short channel ids
  lnwire/query_short_chan_ids.go
  lnwire/query_short_chan_ids_test.go
  lnwire/reply_channel_range.go
  lnwire/reply_channel_range_test.go
Labels: gossip, spec

#3749 routing: local balance check before path finding
  channeldb/payments.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_server.go
  routing/errors.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_lifecycle.go
  routing/payment_session.go
Labels: error messages, payments, routing, v0.9.0

#3744 lnrpc: re-enable custom records
  channeldb/migration_01_to_11/payments.go
  channeldb/payments.go
  htlcswitch/hop/payload.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
  tlv/record.go
  tlv/record_test.go
Labels: payments, routing, rpc, v0.9.0

#3698 Warn user before doing SCB restore
  cmd/lncli/commands.go
Labels: documentation, lncli, recovery, scb

#3719 chanbackup: encode broadcast height in chan ID for unconfirmed channels
  chanbackup/single.go
  chanbackup/single_test.go
  chanrestore.go
  lntest/itest/lnd_test.go
Labels: P2, enhancement, safety

#3655 Add Option Upfront Shutdown
  .golangci.yml
  chancloser.go
  chancloser_test.go
  channeldb/channel.go
  channeldb/channel_test.go
  config.go
  feature/default_sets.go
  fundingmanager.go
  fundingmanager_test.go
  lnwallet/channel.go
  lnwallet/reservation.go
  lnwallet/wallet.go
  lnwire/accept_channel.go
  lnwire/accept_channel_test.go
  lnwire/features.go
  lnwire/lnwire.go
  lnwire/lnwire_test.go
  lnwire/open_channel.go
  lnwire/shutdown.go
  peer.go
  server.go
Labels: P2, enhancement, security, spec, v0.9.0, wire protocol

#3770 channeldb+invoices: prepare invoice db for mpp
  channeldb/db.go
  channeldb/invoice_test.go
  channeldb/invoices.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/update.go
  record/mpp.go
Labels: amp, code health, database, payments, refactoring, v0.9.0

#3788 parse and generate bolt 11 invoices w/ payment addrs
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
  zpay32/invoice.go
  zpay32/invoice_internal_test.go
  zpay32/invoice_test.go
Labels: payments, spec, v0.9.0

#3789 republish force and coop closes on startup
  chancloser.go
  channeldb/channel.go
  channeldb/channel_test.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_arbitrator_test.go
  lntest/itest/lnd_test.go
  lnwallet/channel.go
  peer.go
Labels: v0.9.0

#3742 invoices: expose custom tlv records from the payload
  channeldb/invoice_test.go
  channeldb/invoices.go
  htlcswitch/hop/payload.go
  htlcswitch/hop/payload_test.go
  invoices/interface.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/update.go
  lnrpc/invoicesrpc/utils.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  tlv/record.go
  tlv/stream.go
  tlv/stream_test.go
Labels: v0.9.0

#3702 Add optional close address
  chancloser.go
  cmd/lncli/commands.go
  htlcswitch/switch.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  peer.go
  peer_test.go
  rpcserver.go
  server.go
  test_utils.go
Labels: v0.9.0

#3802 rpc: expose invoice features in decodepayreq
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/invoicesrpc/config_active.go
  lnrpc/invoicesrpc/invoices_server.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnwire/features.go
  lnwire/features_test.go
  rpcserver.go
  subrpcserver_config.go
  zpay32/invoice.go
  zpay32/invoice_test.go
Labels: amp, payments, rpc, spec, v0.9.0

#3785 discovery: properly set FirstBlockHeight and NumBlocks in responses
  discovery/syncer.go
  discovery/syncer_test.go
Labels: v0.9.0

#3697 config: improve management of htlc amount lower limit
  chainregistry.go
  channeldb/graph.go
  cmd/lncli/commands.go
  config.go
  fundingmanager.go
  fundingmanager_test.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/test_utils.go
  lnd.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  log.go
  peer.go
  pilot.go
  routing/localchans/log.go
  routing/localchans/manager.go
  routing/log.go
  routing/router.go
  rpcserver.go
  server.go
Labels: payments, routing, v0.9.0

#3820 build: prevent loggers from overwriting each other.
  log.go
Labels: logging, v0.9.0

#3415 htlcswitch+invoices: allow settling invoices via multi-path payments
  channeldb/invoices.go
  htlcswitch/mock.go
  invoices/clock_test.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/update.go
  lnrpc/invoicesrpc/utils.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  queue/priority_queue.go
  queue/priority_queue_test.go
  server.go
Labels: HTLC, amp, payments, v0.9.0

#3825 zpay32: ensure feature vector is always populated
  zpay32/invoice.go
  zpay32/invoice_test.go
Labels: v0.9.0

#3824 lnrpc: expose features on rpc invoices
  lnrpc/invoicesrpc/utils.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: payments, rpc, v0.9.0

#3828 channeldb: custom records sanity check
  channeldb/payments.go
  channeldb/payments_test.go
  lnrpc/routerrpc/router_backend.go
  record/custom_records.go
  rpcserver.go
Labels: database, safety, v0.9.0

#3832 signrpc: fix uncommitted changes from proto
  lnrpc/signrpc/signer.pb.go
Labels: protos, rpc, v0.9.0

#3694 invoices+channeldb: reject payments to expired invoices
  channeldb/invoice_test.go
  channeldb/invoices.go
  clock/default_clock.go
  clock/interface.go
  clock/test_clock.go
  clock/test_clock_test.go
  htlcswitch/mock.go
  invoices/invoice_expiry_watcher.go
  invoices/invoice_expiry_watcher_test.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/test_utils_test.go
  invoices/utils_test.go
  queue/priority_queue.go
  server.go
  zpay32/invoice.go
Labels: P2, bug fix, payments, spec, v0.9.0

#3840 lnrpc: clarify block padding requirement for QueryRoutes
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
Labels: payments, rpc, trivial, v0.9.0

#3834 feature: add transitive feature bit validation
  feature/deps.go
  feature/deps_test.go
  feature/manager.go
  lnwire/features.go
  peer.go
Labels: amp, v0.9.0

#3763 cnct: keep open channel data after channel commitment tx confirms
  channeldb/channel.go
Labels: anchors, channel closing, channels, commitments, database, v0.9.0

#3799 Bugfix: Chanfitness open time for offline peers
  chanfitness/chanevent.go
  chanfitness/chaneventstore.go
  chanfitness/chaneventstore_test.go
  rpcserver.go
Labels: v0.9.0

#3397 lnrpc: Add subscribe peer events rpc
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: v0.9.0

#3814 sweep: add wallet inputs to reach dust limit
  chainregistry.go
  contractcourt/commit_sweep_resolver.go
  contractcourt/commit_sweep_resolver_test.go
  contractcourt/interfaces.go
  lnrpc/walletrpc/walletkit_server.go
  server.go
  sweep/backend_mock_test.go
  sweep/interface.go
  sweep/sweeper.go
  sweep/sweeper_test.go
  sweep/tx_input_set.go
  sweep/tx_input_set_test.go
  sweep/txgenerator.go
  utxonursery.go
  utxonursery_test.go
Labels: anchors, chain handling, channel closing, utxo sweeping, v0.9.0

#3796 Add Upfront Shutdown Address to OpenChannelRequest
  cmd/lncli/commands.go
  feature/manager.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: v0.9.0

#3818 routing: send to route max hops check
  go.mod
  go.sum
  routing/payment_lifecycle.go
  routing/route/route.go
  routing/router.go
  routing/router_test.go
Labels: v0.9.0

#3679 bolt 11 payment addr + single shot mpp for SendPayment
  channeldb/graph.go
  feature/default_sets.go
  feature/deps.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  lntest/wait/wait.go
  lnwire/features.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_lifecycle.go
  routing/payment_session.go
  routing/router.go
  rpcserver.go
Labels: amp, onion routing, payments, v0.9.0

#3847 lnd test: fix csv mempool sweep time
  lntest/itest/lnd_test.go
Labels: v0.9.0

#3838 channeldb+invoices: fix what pending invoice means in ChannelDB
  channeldb/invoice_test.go
  channeldb/invoices.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
Labels: bug fix, code health, v0.9.0

#3845 [trivial] lncfg+lncli: replace WithDialer->WitchContextDialer
  cmd/lncli/main.go
  lncfg/address.go
Labels: gRPC, trivial

#3849 zpay32: update spec test vectors, write features last
  zpay32/invoice.go
  zpay32/invoice_test.go
Labels: v0.9.0

#3831 Add MPPTimeout ResolutionResult and expose to caller
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_incoming_resolver_test.go
  contractcourt/interfaces.go
  contractcourt/mock_registry_test.go
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/mock.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/update.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_server.go
  lnwire/onion_error.go
  lnwire/onion_error_test.go
  routing/missioncontrol_store_test.go
  routing/result_interpretation.go
  routing/result_interpretation_test.go
Labels: v0.9.0

#3863 routing: fix gap in result interpretation
  routing/result_interpretation.go
  routing/result_interpretation_test.go
Labels: mission control, payments, v0.9.0

#3841 routing: check max routing info size
  autopilot/graph.go
  channeldb/graph.go
  channeldb/graph_test.go
  record/mpp.go
  routing/heap.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_lifecycle.go
  routing/payment_session.go
  routing/payment_session_test.go
  routing/route/route.go
  routing/route/route_test.go
  routing/router.go
  routing/router_test.go
  routing/testdata/excessive_hops.json
  rpcserver.go
  server.go
  tlv/varint.go
Labels: v0.9.0

#3855 routing/pathfind_test: construct sorted edge policies
  routing/pathfind_test.go
Labels: trivial, v0.9.0

#3647 build+lncli: default to hex encoding for byte slices
  cmd/lncli/cmd_build_route.go
  cmd/lncli/cmd_query_mission_control.go
  cmd/lncli/commands.go
  cmd/lncli/invoicesrpc_active.go
  cmd/lncli/watchtower_active.go
  cmd/lncli/wtclient.go
  cmd/lncli/wtclient_types.go
  go.mod
  go.sum
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
Labels: P3, enhancement, gRPC, json-rpc, lncli, rpc, v0.9.0

#3722 lnrpc+lnwallet+funding: implement new RPCs to enable external channel funding
  fundingmanager.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/harness.go
  lntest/itest/lnd_test.go
  lnwallet/chanfunding/canned_assembler.go
  lnwallet/wallet.go
  rpcserver.go
  server.go
Labels: funding, rpc, v0.9.0

#3795 lncli+invoices: experimental key send mode
  channeldb/invoices.go
  cmd/lncli/commands.go
  config.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/test_utils_test.go
  invoices/update.go
  lnrpc/invoicesrpc/utils.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_single_hop_invoice_test.go
  lntest/itest/lnd_test.go
  lntest/node.go
  record/experimental.go
  server.go
Labels: payments, tlv, v0.9.0
