Repository lightningnetwork/lnd, pull requests merged in 2019-07, with the labels that each got.

#3262 lnrpc/watchtowerrpc: prevent watchtowerrpc panic when tower not active
  lnrpc/watchtowerrpc/config_active.go
  lnrpc/watchtowerrpc/handler.go
  subrpcserver_config.go
Labels: P2, bug fix, rpc, v0.7.1, watchtower

#3251 routing: move call to PruneGraph outside of the collating loop
  routing/router.go
Labels: P2, database, enhancement, optimization, v0.7.1

#3229 [trivial] lnd: fallback to localhost if failing getting hostname
  lnd.go
Labels: mobile, trivial, v0.7.1

#3263 cmd/lncli/commands: fix updatechanpolicy lowest possible fee msg
  cmd/lncli/commands.go
Labels: trivial, v0.7.1

#3156 routerrpc: add more failure reasons and route hints
  channeldb/payment_control.go
  channeldb/payment_control_test.go
  channeldb/payments.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_server.go
  lntest/itest/lnd_test.go
  routing/control_tower.go
  routing/payment_lifecycle.go
  routing/router.go
Labels: P3, gRPC, payments, routing, rpc, v0.7.1

#3178 multi: replace manual CAS with sync.Once in several more modules
  channelnotifier/channelnotifier.go
  discovery/gossiper.go
  htlcswitch/mailbox.go
  lnrpc/chainrpc/chainnotifer_server.go
  lnwallet/sigpool.go
  netann/chan_status_manager.go
  queue/queue.go
Labels: P3, code health, refactoring, v0.7.1

#3280 lnwallet: fix key derivation for very first key in family
  lnwallet/btcwallet/signer.go
Labels: P2, bug fix, v0.7.1, wallet

#3279 lnrpc: Deprecate fee field in payment struct
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: v0.7.1

#3269 CODEOWNERS: create initial code owners config
  .github/CODEOWNERS
Labels: v0.7.1

#3285 CODEOWNERS: fix aezeed typo
  .github/CODEOWNERS
Labels: v0.7.1

#3246 rpcserver: ForwardingHistory end_time defaults to time.Now()
  cmd/lncli/commands.go
  rpcserver.go
Labels: P3, cli, enhancement, v0.7.1

#1933 Add addresses to transactions returned by SubscribeTransactions
  lnwallet/btcwallet/btcwallet.go
  lnwallet/interface_test.go
  rpcserver.go
Labels: P2, enhancement, rpc, v0.7.1, wallet

#3245 rpc: fix calculating RPC permissions.
  rpcserver.go
Labels: v0.7.1

#3294 build: use github mirror of bsaes dependency
  go.mod
  go.sum
Labels: golang/build system, v0.7.1

#3238 rpc: add channel reserve fields in RPC responses.
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: P3, channels, rpc, v0.7.1, wallet

#2366 lnrpc+rpcserver: Adding timestamps to RoutingPolicy
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: P3, bug fix, gRPC, graph, rpc, v0.7.1

#3188 htlcswitch+routing+routerrpc: error source as index and expose decrypt failure
  go.mod
  go.sum
  htlcswitch/failure.go
  htlcswitch/link.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  htlcswitch/switch_test.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_server.go
  lnwire/onion_error.go
  lnwire/onion_error_test.go
  routing/pathfind_test.go
  routing/payment_lifecycle.go
  routing/router.go
  routing/router_test.go
  server.go
Labels: P3, error messages, routing, rpc, v0.7.1

#3297 MAKEFILE: Clarify what the testcase argument is
  docs/MAKEFILE.md
Labels: documentation, makefile, trivial, v0.7.1

#2957 [lnd test] write goroutine snapshot on integration test failure
  .gitignore
  lntest/harness.go
  lntest/itest/lnd_test.go
  lntest/node.go
  make/testing_flags.mk
Labels: P3, enhancement, itests, testing, v0.7.1

#3284 build: update dependencies to prevent unnecessary bitcoind ZMQ timeouts
  go.mod
  go.sum
Labels: P2, bitcoind, bug fix, v0.7.1

#1859 add C# gRPC doc
  docs/grpc/c#.md
Labels: P3, documentation

#2682 lnd_test: fix channel event subscription test flake.
  lntest/itest/lnd_test.go
Labels: bug fix, gossip, itests, v0.7.1

#2926 routing: tracking visited nodes in findPath
  channeldb/graph.go
  routing/heap.go
  routing/heap_test.go
  routing/pathfind.go
Labels: optimization, routing, v0.7.1

#3313 lnd: prevent panic on nil neutrino cleanup
  chainregistry.go
  lnd.go
Labels: v0.7.1

#3314 peer: don't reply to requests for `initial_graph_sync`
  discovery/gossiper.go
  peer.go
Labels: dos/hardening, gossip, p2p, v0.7.1

#3298 routing: globalize mc
  lnrpc/routerrpc/config.go
  lnrpc/routerrpc/config_active.go
  lnrpc/routerrpc/config_default.go
  routing/missioncontrol.go
  routing/missioncontrol_test.go
  routing/mock_test.go
  routing/nodepair.go
  routing/payment_lifecycle.go
  routing/payment_session.go
  routing/payment_session_source.go
  routing/payment_session_test.go
  routing/router.go
  routing/router_test.go
  server.go
Labels: v0.7.1

#3307 aezeed: publicly export the `word` field in `ErrUnknownMnenomicWord`
  aezeed/cipherseed.go
  aezeed/cipherseed_test.go
  aezeed/errors.go
Labels: v0.7.1

#3325 lnd: log error if any throughout initialization
  lnd.go
Labels: v0.7.1

#3316 rpcserver+channeldb: return num zombies in NetworkInfo response
  channeldb/graph.go
  channeldb/graph_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: v0.7.1

#3221 routing+routerrpc+lnrpc: add option to use mc in queryroutes
  cmd/lncli/commands.go
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_backend_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_session.go
  routing/payment_session_source.go
  routing/payment_session_test.go
  routing/router.go
  routing/router_test.go
  server.go
Labels: P2, enhancement, payments, rpc, v0.7.1

#3165 [funding+autopilot] Make the funding manager and autopilot fee aware
  autopilot/agent.go
  autopilot/agent_test.go
  autopilot/interface.go
  fundingmanager.go
  fundingmanager_test.go
  lnwallet/interface_test.go
  lnwallet/reservation.go
  lnwallet/wallet.go
  lnwallet/wallet_test.go
  mock.go
  pilot.go
  server.go
Labels: P2, autopilot, enhancement, funding, v0.7.1

#3197 Optimize prune zombie channels
  channeldb/graph.go
  channeldb/graph_test.go
  routing/pathfind_test.go
  routing/router.go
  routing/router_test.go
Labels: P2, database, graph, optimization, v0.7.1

#3237 Unit test for autoregenerating expired cert pairs
  lnd.go
  lntest/itest/lnd_test.go
  server_test.go
Labels: P3, itests, test flake, testing, v0.7.1

#3143 htlcswitch: pipeline settles to switch
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  lntest/itest/lnd_test.go
  server.go
  test_utils.go
Labels: P3, htlcswitch, incomplete, optimization, v0.7.1

#3330 [trivial] lnd: remove global var access from genCertPair
  lnd.go
  server_test.go
Labels: v0.7.1

#3303 cmd: Add passphrase confirmation when creating wallet from existing seed
  cmd/lncli/commands.go
Labels: authentication, enhancement, lncli, v0.7.1

#3338 build: update neutrino to latest version
  go.mod
  go.sum
Labels: v0.7.1

#3337 lnd: Add regtest exception for wait to sync on startup
  lnd.go
Labels: v0.7.1

#3339 routing: add block padding to sendpayment
  lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
  lntest/itest/lnd_test.go
  routing/payment_session.go
  routing/payment_session_test.go
Labels: v0.7.1

#3342 config: default autopilot min confs to 1
  config.go
Labels: v0.7.1

#3344 build: update to neutrino version w/ shutdown fix
  go.mod
  go.sum
Labels: v0.7.1

#3347 ticker+queue: run go mod tidy
  queue/go.sum
  ticker/go.mod
Labels: v0.8.0

#3278 channeldb: specify freelist bbolt options by default
  channeldb/db.go
  go.mod
  go.sum
  watchtower/wtdb/db_common.go
Labels: P2, database, optimization, v0.8.0

#3356 lnrpc: remove lncli subscribechannelevents
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
Labels: v0.8.0

#3184 multi: add watchtower client RPC subserver
  cmd/lncli/main.go
  cmd/lncli/wtclient_active.go
  cmd/lncli/wtclient_default.go
  cmd/lncli/wtclient_types.go
  config.go
  lncfg/wtclient.go
  lnd.go
  lnrpc/wtclientrpc/config_active.go
  lnrpc/wtclientrpc/config_default.go
  lnrpc/wtclientrpc/driver.go
  lnrpc/wtclientrpc/log.go
  lnrpc/wtclientrpc/wtclient.go
  lnrpc/wtclientrpc/wtclient.pb.go
  lnrpc/wtclientrpc/wtclient.proto
  lntest/itest/lnd_test.go
  lntest/node.go
  log.go
  make/testing_flags.mk
  rpcserver.go
  server.go
  subrpcserver_config.go
  watchtower/wtclient/candidate_iterator.go
  watchtower/wtclient/candidate_iterator_test.go
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtclient/interface.go
  watchtower/wtclient/session_negotiator.go
  watchtower/wtclient/session_queue.go
  watchtower/wtclient/stats.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtdb/client_session.go
  watchtower/wtdb/tower.go
  watchtower/wtmock/client_db.go
Labels: P2, enhancement, rpc, v0.8.0, watchtower
