Repository lightningnetwork/lnd, pull requests merged in 2020-12, with the labels that each got.

#4789 wtclient: schedule ForceQuit first during Stop
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtclient/session_negotiator.go
Labels: v0.12

#4782 watchtower: anchor channel support
  cmd/lncli/wtclient.go
  htlcswitch/interfaces.go
  htlcswitch/link.go
  lnrpc/wtclientrpc/config.go
  lnrpc/wtclientrpc/wtclient.go
  lnrpc/wtclientrpc/wtclient.pb.go
  lnrpc/wtclientrpc/wtclient.pb.gw.go
  lnrpc/wtclientrpc/wtclient.proto
  lnrpc/wtclientrpc/wtclient.swagger.json
  lntest/itest/lnd_test.go
  peer/brontide.go
  rpcserver.go
  server.go
  subrpcserver_config.go
  watchtower/blob/type.go
  watchtower/blob/type_test.go
  watchtower/wtclient/backup_task.go
  watchtower/wtclient/backup_task_internal_test.go
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtclient/session_negotiator.go
  watchtower/wtpolicy/policy.go
  watchtower/wtpolicy/policy_test.go
  watchtower/wtserver/server.go
  watchtower/wtserver/server_test.go
  watchtower/wtwire/features.go
Labels: v0.12, watchtower, wtclient, wtserver

#4806 Fix Onion v2 support for Neutrino backends
  lnd.go
  tor/tor.go
  tor/tor_test.go
Labels: bug fix, neutrino, tor

#4810 multi: add new config option to toggle gossip rate limiting
  discovery/gossiper.go
  discovery/gossiper_test.go
  lncfg/protocol_legacy_off.go
  lncfg/protocol_legacy_on.go
  lntest/node.go
  server.go
Labels: v0.12

#4816 itest: run sub itests correctly for watchtower tests
  lntest/itest/lnd_test.go
Labels: v0.12

#4792 tls: Add healthcheck to shutdown if certificate is expired
  config.go
  lncfg/healthcheck.go
  sample-lnd.conf
  server.go
Labels: v0.12

#4817 github: remove CODEOWNERS file
  .github/CODEOWNERS
Labels: maintenance

#4815 wtdb+wtclient: segregate session-key-index reservations by blob-type
  watchtower/wtclient/interface.go
  watchtower/wtclient/session_negotiator.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtmock/client_db.go
Labels: v0.12, watchtower, wtclient, wtdb

#4780 chainwatcher: properly derive to_local script for "future" local force closes
  channeldb/channel.go
  channeldb/channel_test.go
  contractcourt/chain_watcher.go
  contractcourt/chain_watcher_test.go
  contractcourt/utils_test.go
  lnwallet/channel.go
  lnwallet/test_utils.go
Labels: v0.12

#4823 itest: fwd interceptor fixes
  lntest/itest/lnd_forward_interceptor_test.go
Labels: itests, test flake, trivial, v0.12

#4787 kvdb: add timeout options for bbolt
  chainntnfs/test_utils.go
  chainreg/chainregistry.go
  channeldb/db.go
  channeldb/forwarding_package_test.go
  channeldb/kvdb/backend.go
  channeldb/kvdb/bolt_compact.go
  channeldb/kvdb/config.go
  channeldb/migration_01_to_11/db.go
  channeldb/migration_01_to_11/options.go
  channeldb/migtest/migtest.go
  channeldb/options.go
  channeldb/options_test.go
  contractcourt/briefcase_test.go
  contractcourt/channel_arbitrator_test.go
  go.mod
  go.sum
  htlcswitch/decayedlog.go
  keychain/interface_test.go
  lncfg/db.go
  lncfg/db_test.go
  lnd.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/btcwallet/config.go
  lnwallet/interface_test.go
  macaroons/service.go
  macaroons/service_test.go
  macaroons/store_test.go
  routing/chainview/interface_test.go
  routing/integrated_routing_context_test.go
  routing/missioncontrol_store_test.go
  routing/missioncontrol_test.go
  sample-lnd.conf
  walletunlocker/service.go
  walletunlocker/service_test.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtdb/db_common.go
  watchtower/wtdb/tower_db.go
  watchtower/wtdb/tower_db_test.go
Labels: boltdb, v0.12

#4822 routing: add missing features to NetworkNodeUpdate (and also depreacte GlobalFeatures)
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  routing/notifications.go
  routing/notifications_test.go
  rpcserver.go
Labels: bug

#4841 rpcserver: replace sweep_all in log with send_all to match rpc arg
  rpcserver.go
Labels: logging, trivial

#4825 itest: adjust parallelization, poll intervals and timeouts to not starve goroutines
  lntest/harness.go
  lntest/itest/lnd_channel_backup_test.go
  lntest/itest/lnd_multi-hop_test.go
  lntest/itest/lnd_test.go
  lntest/node.go
  lntest/wait/wait.go
  make/testing_flags.mk
Labels: flake fix, itests, v0.12

#4850 itest: increase recovery payment amount so htlc isn't dust
  lntest/itest/lnd_channel_backup_test.go
Labels: flake fix, trivial, v0.12

#4838 sweep/txgenerator: fix input witness ordering
  sweep/sweeper_test.go
  sweep/txgenerator.go
Labels: anchors, utxo sweeping, v0.12

#4849 etcd: increment port for embedded etcd server
  channeldb/kvdb/etcd/embed.go
Labels: etcd, test flake

#4843 build: check compilation of each commit
  .github/workflows/main.yml
  scripts/check-commit.sh
  scripts/check-each-commit.sh
Labels: CI, golang/build system, v0.12

#4842 mod: update to btcwallet master
  go.mod
  go.sum
Labels: v0.12, wallet

#4847 peer: do not require static remote for peers with legacy channels
  peer/brontide.go
  peer/brontide_test.go
  peer/test_utils.go
Labels: v0.12

#4854 build: update to addrv2 aware neutrino version
  chainreg/chainregistry.go
  go.mod
  go.sum
Labels: neutrino, v0.12

#4804 discovery: adhere to proper channel chunk splitting for ReplyChannelRange
  channeldb/graph.go
  channeldb/graph_test.go
  discovery/chan_series.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/sync_manager.go
  discovery/sync_manager_test.go
  discovery/syncer.go
  discovery/syncer_test.go
Labels: compatibility, gossip, spec, v0.12

#4856 make: use low-scrypt + parallelization to speed up unit-race
  chainntnfs/test/bitcoind/bitcoind_test.go
  chainntnfs/test/btcd/btcd_test.go
  chainntnfs/test/neutrino/neutrino_test.go
  chainntnfs/test/test_interface.go
  lnwallet/btcwallet/btcwallet_rpctest.go
  lnwallet/test/bitcoind/bitcoind_test.go
  lnwallet/test/btcd/btcd_test.go
  lnwallet/test/neutrino/neutrino_test.go
  lnwallet/test/test_interface.go
  make/testing_flags.mk
Labels: v0.12

#4852 GitHub: specify docker image platforms to enable ARM image builds
  .github/workflows/docker.yml
Labels: ARM, docker, github actions

#4797 make: add zpay32 to fuzz_flags.mk
  make/fuzz_flags.mk
Labels: fuzzing, makefile

#4861 GitHub+Travis+docker: update golang patch version to 1.15.6 everywhere
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .travis.yml
  Dockerfile
  dev.Dockerfile
Labels: CI, docker, github actions, travis

#4865 chanrestore: flip case logic for old backup logic
  chanrestore.go
Labels: bug fix, safety, scb

#4855 multi: cap anchors feerate at configurable maximum
  config.go
  fundingmanager.go
  htlcswitch/link.go
  htlcswitch/test_utils.go
  lntest/itest/lnd_test.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/commitment.go
  peer/brontide.go
  sample-lnd.conf
  server.go
Labels: v0.12

#4867 lnd+walletunlocker: move wallet DB history drop to unlocker
  lnd.go
  walletunlocker/service.go
  walletunlocker/service_test.go
Labels: bug fix, recovery, safety, wallet

#4757 funding: move Manager to own package
  config.go
  funding/interfaces.go
  funding/log.go
  funding/manager.go
  funding/manager_test.go
  lntest/itest/lnd_max_channel_size_test.go
  lntest/itest/lnd_multi-hop-error-propagation_test.go
  lntest/itest/lnd_psbt_test.go
  lntest/itest/lnd_test.go
  lntest/itest/lnd_wumbo_channels_test.go
  log.go
  peer/brontide.go
  pilot.go
  rpcserver.go
  server.go
Labels: code health, funding

#4872 peer: ensure consistent local+global feature bits when downgrading
  peer/brontide.go
  peer/brontide_test.go
Labels: bug fix

#4881 rpcserver: fix log statement in channelbalance
  rpcserver.go
Labels: logging, trivial
