Repository lightningnetwork/lnd, pull requests merged in 2020-04, with the labels that each got.

#4130 rpcserver: align OpenChannel + OpenChannelSync request parsing
  lntest/itest/lnd_test.go
  rpcserver.go
Labels: v0.10

#4133 peer: send local node announcement upon establishing peer connections
  peer.go
Labels: v0.10

#3970 MPP: Enable MultiPathPayments for payment lifecycle
  channeldb/mp_payment.go
  channeldb/payment_control.go
  channeldb/payment_control_test.go
  channeldb/payments.go
  lntest/itest/lnd_mpp_test.go
  lntest/itest/lnd_test.go
  routing/control_tower.go
  routing/control_tower_test.go
  routing/errors.go
  routing/mock_test.go
  routing/pathfind.go
  routing/payment_lifecycle.go
  routing/payment_lifecycle_test.go
  routing/payment_session.go
  routing/payment_session_source.go
  routing/payment_session_test.go
  routing/route/route.go
  routing/route/route_test.go
  routing/router.go
  routing/router_test.go
Labels: mpp, routing, v0.10

#4151 contractcourt/chain_watchter: fix broken log stmts
  contractcourt/chain_watcher.go
Labels: trivial, v0.10

#4143 lntest/itest/lnd_test: wait when calling OpenChannel
  lntest/itest/lnd_test.go
Labels: trivial, v0.10

#4121 lnwallet: apply BIP69+CLTV tie-break to HTLC signature order
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/commitment.go
Labels: v0.10

#4140 lnrpc: use initiator enum for pending channel open initiator
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  rpcserver.go
Labels: v0.10

#4145 htlcswitch: remove overflow queue
  channeldb/invoices.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/mailbox.go
  htlcswitch/queue.go
  htlcswitch/queue_test.go
  htlcswitch/switch_test.go
  htlcswitch/test_utils.go
  invoices/invoiceregistry.go
  lntest/itest/lnd_test.go
Labels: v0.10

#4152 cmd/lncli: move invoice-related cmds to Invoices category
  cmd/lncli/cmd_invoice.go
  cmd/lncli/commands.go
  cmd/lncli/invoicesrpc_active.go
Labels: v0.10

#3960 channeldb+lnrpc+lncli: listpayments pagination support
  channeldb/duplicate_payments.go
  channeldb/mp_payment.go
  channeldb/payments.go
  channeldb/payments_test.go
  cmd/lncli/commands.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  rpcserver.go
Labels: accounting, rpc, v0.10

#3972 routing: extend trackpayment with htlc events
  channeldb/payment_control.go
  channeldb/payment_control_test.go
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_server.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  multimutex/hash_mutex.go
  queue/queue.go
  queue/queue_test.go
  routing/control_tower.go
  routing/control_tower_test.go
  routing/mock_test.go
  routing/payment_lifecycle.go
  rpcserver.go
Labels: gRPC, mpp, payments, routing, rpc

#3967 routing: multi-shard mpp send
  channeldb/payments.go
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lntest/itest/lnd_mpp_test.go
  lntest/itest/lnd_send_multi_path_payment.go
  lntest/itest/lnd_test.go
  routing/integrated_routing_context_test.go
  routing/integrated_routing_test.go
  routing/mock_graph_test.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_session.go
  routing/payment_session_source.go
  routing/payment_session_test.go
  routing/result_interpretation.go
  routing/result_interpretation_test.go
  routing/router.go
  routing/router_test.go
  rpcserver.go
  server.go
Labels: mpp, payments, routing, v0.10

#4075 rpc: allow wumbo invoices
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/invoicesrpc/config_active.go
  lnrpc/invoicesrpc/invoices_server.go
  lnrpc/routerrpc/router_backend.go
  rpcserver.go
  subrpcserver_config.go
Labels: payments, v0.10

#4172 input: assert witness size constants
  chancloser.go
  contractcourt/htlc_timeout_resolver_test.go
  discovery/gossiper_test.go
  fundingmanager.go
  fundingmanager_test.go
  htlcswitch/mock.go
  input/script_utils.go
  input/script_utils_test.go
  input/signer.go
  input/size.go
  input/size_test.go
  input/test_utils.go
  lnrpc/signrpc/signer_server.go
  lnwallet/btcwallet/signer.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/chanvalidate/validate_test.go
  lnwallet/interface.go
  lnwallet/interface_test.go
  lnwallet/reservation.go
  lnwallet/sigpool.go
  lnwallet/test_utils.go
  lnwallet/wallet.go
  lnwire/signature.go
  mock.go
  netann/channel_update_test.go
  netann/node_signer.go
  netann/sign.go
  peer_test.go
  server.go
  sweep/test_utils.go
  sweep/txgenerator_test.go
  watchtower/lookout/justice_descriptor.go
  watchtower/lookout/justice_descriptor_test.go
  watchtower/wtclient/backup_task.go
  watchtower/wtmock/signer.go
Labels: v0.10

#4163 verrpc: add GetVersion endpoint
  Makefile
  build/version.go
  cmd/lncli/cmd_version.go
  cmd/lncli/main.go
  lnrpc/lnclipb/lncli.pb.go
  lnrpc/lnclipb/lncli.proto
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnrpc/verrpc/driver.go
  lnrpc/verrpc/log.go
  lnrpc/verrpc/server.go
  lnrpc/verrpc/verrpc.pb.go
  lnrpc/verrpc/verrpc.proto
  log.go
  rpcserver.go
Labels: rpc, v0.10

#4169 invoices: elminitate sleep from expiry watcher tests
  invoices/invoice_expiry_watcher_test.go
Labels: testing

#4175 channeldb: correct HasChanStatus for ChanStatusDefault, fix rpc channel status
  channeldb/channel.go
  channeldb/channel_test.go
  peer.go
Labels: bug fix, rpc

#4189 routing+routerrpc+lncli: rename MaxHtlcs to MaxShards
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lntest/itest/lnd_send_multi_path_payment.go
  routing/integrated_routing_context_test.go
  routing/integrated_routing_test.go
  routing/payment_session.go
  routing/router.go
  rpcserver.go
Labels: lncli, payments, rpc, v0.10

#4188 lnrpc/verrpc: correct mispelling of compilation
  lnrpc/verrpc/verrpc.pb.go
  lnrpc/verrpc/verrpc.proto
Labels: trivial

#4190 make+lnd+config: fix Windows build and version string
  Makefile
  cmd/lncli/main.go
  config.go
  lnd.go
Labels: v0.10

#4174 htlcswitch: mailbox cancellation
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/linkfailure.go
  htlcswitch/mailbox.go
  htlcswitch/mailbox_test.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  htlcswitch/test_utils.go
  peer.go
  server.go
Labels: v0.10

#4195 htlcswitch: mailbox cancel followups
  htlcswitch/link.go
  htlcswitch/test_utils.go
Labels: v0.10

#4209 cert: define ExtendedKeyUsage as required by macOS 10.15/iOS 13.
  cert/selfsigned.go
Labels: bug fix, security

#4182 routerrpc: revive legacy send and track rpcs
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_server.go
  lnrpc/routerrpc/router_server_deprecated.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
Labels: payments, rpc

#4211 lnwallet: absolute fee floor sanity check
  lnwallet/chainfee/rates.go
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: bug fix, channels, v0.10
