Repository lightningnetwork/lnd, pull requests merged in 2020-11, with the labels that each got.

#4675 htlcswitch,rpc: expose onion blob for intercepts
  htlcswitch/interceptable_switch.go
  htlcswitch/interfaces.go
  lnrpc/routerrpc/forward_interceptor.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
Labels: htlcswitch, onion routing, rpc, v0.12

#4701 multi: remove experimential build flag for assumechanvalid
  Makefile
  config.go
  lncfg/routing.go
  routing/conf.go
  routing/conf_experimental.go
  sample-lnd.conf
  server.go
Labels: v0.12

#4703 btcwallet: return chain best timestamp while backend is syncing
  lnwallet/btcwallet/btcwallet.go
Labels: backend, bug fix, v0.12, wallet

#4655 Travis: run itests in parallel, get ~60% speedup overall
  .gitignore
  .travis.yml
  Makefile
  lntest/bitcoind_common.go
  lntest/btcd.go
  lntest/fee_service.go
  lntest/itest/lnd_channel_backup_test.go
  lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
  lntest/itest/lnd_test.go
  lntest/itest/lnd_test_list_off_test.go
  lntest/itest/lnd_test_list_on_test.go
  lntest/itest/test_harness.go
  lntest/node.go
  make/testing_flags.mk
  scripts/itest_part.sh
Labels: CI, enhancement, golang/build system, itests

#4738 aezeed: fix mnemonic word validation
  aezeed/cipherseed.go
  aezeed/cipherseed_test.go
Labels: v0.12

#1288 walletunlocker+lnd: add command line flag to allow passing admin macaroon after wallet creation
  cmd/lncli/cmd_walletunlocker.go
  docs/macaroons.md
  lnd.go
  lnrpc/chainrpc/chainnotifier_server.go
  lnrpc/invoicesrpc/invoices_server.go
  lnrpc/routerrpc/router_server.go
  lnrpc/signrpc/signer_server.go
  lnrpc/walletrpc/walletkit_server.go
  lnrpc/walletunlocker.pb.go
  lnrpc/walletunlocker.proto
  lnrpc/walletunlocker.swagger.json
  lntest/harness.go
  lntest/itest/lnd_channel_backup_test.go
  lntest/itest/lnd_macaroons_test.go
  lntest/itest/lnd_test.go
  lntest/itest/lnd_test_list_on_test.go
  lntest/node.go
  macaroons/service.go
  macaroons/service_test.go
  macaroons/store.go
  macaroons/store_test.go
  walletunlocker/service.go
  walletunlocker/service_test.go
Labels: P2, cli, macaroons, needs review, needs testing, v0.12

#2018 Mark channels borked in case of remote error
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/linkfailure.go
  peer/brontide.go
Labels: P2, bug fix, needs review, needs testing, p2p

#4756 itest: add parallel flakehunter
  Makefile
  docs/MAKEFILE.md
  lntest/itest/lnd_test.go
  make/testing_flags.mk
Labels: flake fix, itests, test flake

#4683 channelacceptor: add new fields to acceptor response
  chanacceptor/acceptor_test.go
  chanacceptor/chainedacceptor.go
  chanacceptor/errors.go
  chanacceptor/interface.go
  chanacceptor/log.go
  chanacceptor/merge.go
  chanacceptor/merge_test.go
  chanacceptor/rpcacceptor.go
  chanacceptor/rpcacceptor_test.go
  fundingmanager.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnwallet/chancloser/chancloser.go
  log.go
  rpcserver.go
Labels: funding, rpc, v0.12

#4755 multi: use bitcoind uptime api for healthcheck
  chainreg/chainregistry.go
  server.go
Labels: v0.12

#3672 Allow user specify routing hints in private invoice.
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/invoicesrpc/invoices_server.go
  lnrpc/invoicesrpc/utils.go
  lntest/itest/lnd_single_hop_invoice_test.go
  rpcserver.go
Labels: P3, enhancement, payments, routing

#4737 itest: clean harness state before each icase and better naming for icase logs
  .gitignore
  lntest/harness.go
  lntest/itest/lnd_macaroons_test.go
  lntest/itest/lnd_test.go
  lntest/itest/log_error_whitelist.txt
  lntest/node.go
Labels: itests

#4744 discovery: allow DNS seeds to be overwritten
  lncfg/chain.go
  sample-lnd.conf
  server.go
Labels: config, discovery, p2p

#4751 feature: flip static remote key from optional to required
  feature/default_sets.go
Labels: funding, safety

#4762 multi: update listsweeps to allow sweeps that are not in ListTransactions
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  lntest/itest/lnd_test.go
Labels: v0.12

#4781 lntest/timeouts: fix timeout build predicates
  lntest/timeouts.go
  lntest/timeouts_darwin.go
  lntest/timeouts_etcd.go
Labels: v0.12

#4423 Let invoice.Encode receive a function which hashes itself the message
  lnrpc/invoicesrpc/addinvoice.go
  zpay32/encode.go
  zpay32/invoice.go
  zpay32/invoice_test.go
Labels: rpc, signrpc

#4769 GitHub: add workflow for building tagged docker images
  .github/workflows/docker.yml
Labels: docker, github actions

#4768 Correct HTLC dust calculation for remote commitment weight
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: v0.12

#4750 Sweeper: support Inputs with required locktimes and txOuts
  breacharbiter.go
  input/input.go
  input/size.go
  rpcserver.go
  sweep/backend_mock_test.go
  sweep/sweeper.go
  sweep/sweeper_test.go
  sweep/tx_input_set.go
  sweep/tx_input_set_test.go
  sweep/txgenerator.go
  sweep/walletsweep.go
  sweep/walletsweep_test.go
  sweep/weight_estimator.go
  sweep/weight_estimator_test.go
Labels: HTLC, anchors, utxo sweeping

#4790 multi: take over multiple small stale PRs
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  dev.Dockerfile
  docker/README.md
  docker/docker-compose.ltc.yml
  docker/docker-compose.yml
  docker/lnd/start-lnd.sh
  docs/DOCKER.md
  lnwallet/btcwallet/btcwallet.go
  lnwallet/wallet.go
  peer/brontide.go
Labels: code health, docker, documentation, refactoring

#4752 features+invoices: force MPP payload inclusion for non-keysend payments
  feature/default_sets.go
  invoices/invoiceregistry_test.go
  invoices/test_utils_test.go
  invoices/update.go
  lnrpc/invoicesrpc/invoices.swagger.json
  lnrpc/invoicesrpc/utils.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_server.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_forward_interceptor_test.go
  lntest/itest/lnd_test.go
  lnwire/features.go
  lnwire/features_test.go
  routing/router.go
  routing/router_test.go
  rpcserver.go
Labels: payments, safety

#4777 GitHub: build release binaries and upload to release
  .github/workflows/release.yaml
  scripts/release.sh
Labels: releases

#4786 discovery: rate limit incoming channel updates
  channeldb/graph.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  lnwire/channel_update.go
Labels: gossip, resource usage, v0.12

#3367 Batched graph updates
  batch/batch.go
  batch/interface.go
  batch/scheduler.go
  channeldb/db.go
  channeldb/graph.go
  channeldb/graph_test.go
  channeldb/options.go
  discovery/gossiper.go
  lncfg/db.go
  lnd.go
  lntest/itest/lnd_test.go
  lntest/node.go
  routing/router.go
  sample-lnd.conf
Labels: enhancement, gossip, graph, optimization, v0.12
