Repository lightningnetwork/lnd, pull requests merged in 2020-05, with the labels that each got.

#4192 mixed: apply fixes recommended by staticcheck and dead code removal
  autopilot/agent.go
  autopilot/choice_test.go
  autopilot/combinedattach.go
  breacharbiter.go
  brontide/noise.go
  chainntnfs/txnotifier.go
  chainregistry.go
  channeldb/graph.go
  channeldb/invoices.go
  channeldb/payments_test.go
  channelnotifier/log.go
  config.go
  contractcourt/chain_watcher.go
  fundingmanager.go
  fundingmanager_test.go
  htlcswitch/circuit_test.go
  htlcswitch/decayedlog.go
  htlcswitch/decayedlog_test.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/switch.go
  input/script_utils.go
  input/test_utils.go
  invoices/log.go
  lnd.go
  lntest/harness.go
  lntest/node.go
  lnwallet/channel.go
  lnwallet/errors.go
  lnwallet/interface.go
  lnwallet/interface_test.go
  lnwallet/wallet.go
  lnwire/lnwire.go
  monitoring/log.go
  netann/chan_status_manager_test.go
  netann/log.go
  nursery_store.go
  peer.go
  pilot.go
  queue/gc_queue.go
  routing/errors.go
  routing/missioncontrol.go
  routing/notifications.go
  routing/pathfind_test.go
  routing/router.go
  server.go
  tlv/truncated_test.go
  tlv/varint_test.go
  utxonursery_test.go
  watchtower/log.go
  watchtower/standalone.go
  zpay32/amountunits.go
  zpay32/invoice.go
Labels: code health, v0.11

#4089 rpcserver: parameterize acceptortimeout
  config.go
  rpcserver.go
  sample-lnd.conf
Labels: enhancement, funding, rpc, v0.11

#4176 rpcserver: omit uptime in ListChannels response if server not started
  rpcserver.go
Labels: bug fix, rpc, v0.11

#4239 tlv: fix comments for numLeadingZeroBytes{32,64} funcs
  tlv/truncated.go
Labels: v0.11

#4148 lnwallet/test: add coverage for evaluateHtlcView
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: code health, enhancement, refactoring, testing, v0.11

#4221 build: move release script and README to more appropriate locations
  Makefile
  docs/release.md
  make/release_flags.mk
  scripts/release.sh
Labels: trivial, v0.11

#4241 channeldb: eliminate extra copy in QueryPayments
  channeldb/payments.go
  rpcserver.go
Labels: database, optimization, payments, rpc

#4249 itest: extend whitelist
  lntest/itest/log_error_whitelist.txt
Labels: v0.11

#4139 lnrpc: add block height params to GetTransactions and add ListSweeps
  cmd/lncli/commands.go
  cmd/lncli/walletrpc_active.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnrpc/rpc_utils.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit_server.go
  lntest/itest/lnd_test.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/interface.go
  lnwallet/interface_test.go
  mock.go
  rpcserver.go
  sweep/store.go
  sweep/store_mock.go
  sweep/store_test.go
  sweep/sweeper.go
Labels: enhancement, rpc, v0.11

#4236 docs: update instructions for JavaScript and Python on how to use gRPC
  docs/grpc/javascript.md
  docs/grpc/python.md
Labels: documentation, v0.11

#4253 cmd/lncli: remove usage of Millisecond() for Go 1.12
  cmd/lncli/cmd_pay.go
Labels: v0.10.1

#4220 github: add GitHub Actions configuration
  .github/workflows/main.yml
Labels: P3, golang/build system, itests, v0.11

#4250 REST saga 1/3: Cleanup proto files, generate Swagger docs
  docs/code_contribution_guidelines.md
  lnrpc/autopilotrpc/autopilot.pb.go
  lnrpc/autopilotrpc/autopilot.proto
  lnrpc/autopilotrpc/autopilot.swagger.json
  lnrpc/chainrpc/chainnotifier.proto
  lnrpc/chainrpc/chainnotifier.swagger.json
  lnrpc/gen_protos.sh
  lnrpc/invoicesrpc/invoices.pb.go
  lnrpc/invoicesrpc/invoices.proto
  lnrpc/invoicesrpc/invoices.swagger.json
  lnrpc/lnclipb/lncli.pb.go
  lnrpc/lnclipb/lncli.proto
  lnrpc/lnclipb/lncli.swagger.json
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnrpc/signrpc/signer.pb.go
  lnrpc/signrpc/signer.proto
  lnrpc/signrpc/signer.swagger.json
  lnrpc/verrpc/verrpc.pb.go
  lnrpc/verrpc/verrpc.proto
  lnrpc/verrpc/verrpc.swagger.json
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletunlocker.pb.go
  lnrpc/walletunlocker.pb.gw.go
  lnrpc/walletunlocker.proto
  lnrpc/walletunlocker.swagger.json
  lnrpc/watchtowerrpc/watchtower.pb.go
  lnrpc/watchtowerrpc/watchtower.proto
  lnrpc/watchtowerrpc/watchtower.swagger.json
  lnrpc/wtclientrpc/wtclient.proto
  lnrpc/wtclientrpc/wtclient.swagger.json
Labels: enhancement, gRPC, rpc, v0.11

#3018 htlcswitch/switch: log successfully forwarded HTLCs
  htlcswitch/switch.go
Labels: P3, htlcswitch, logging, v0.11

#2668 Dry run migration
  channeldb/db.go
  channeldb/db_test.go
  channeldb/meta_test.go
  channeldb/options.go
  config.go
  lnd.go
Labels: P3, database, enhancement, safety, v0.10.1

#4257 routing+routerrpc: add multiple outgoing channel restriction
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_backend_test.go
  lntest/itest/log_error_whitelist.txt
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_session.go
  routing/router.go
  routing/unified_policies.go
  rpcserver.go
Labels: payments, routing

#3892 contractcourt: fix lingering contract after local breach
  contractcourt/commit_sweep_resolver.go
  contractcourt/commit_sweep_resolver_test.go
  lntest/itest/lnd_test.go
Labels: bug fix, chain handling, commitments, contracts

#4147 router+routerrpc: unify sendtoroute and payment responses
  channeldb/mp_payment.go
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_server.go
  lnrpc/routerrpc/router_server_deprecated.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_mpp_test.go
  lntest/itest/lnd_test.go
  routing/control_tower.go
  routing/control_tower_test.go
  routing/mock_test.go
  routing/payment_lifecycle.go
  routing/router.go
  routing/router_test.go
  rpcserver.go
Labels: enhancement, payments, rpc, v0.11

#4280 channeldb: remove Tx arg from ForEachNode
  autopilot/graph.go
  channeldb/graph.go
  channeldb/graph_test.go
  routing/router.go
  rpcserver.go
Labels: v0.11

#4276 github: remove continue-on-error
  .github/workflows/main.yml
Labels: golang/build system, v0.11

#4274 wtclient: load missing info into client sessions upon new tower
  lnrpc/wtclientrpc/config.go
  lnrpc/wtclientrpc/log.go
  lnrpc/wtclientrpc/wtclient.go
  log.go
  rpcserver.go
  subrpcserver_config.go
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtmock/client_db.go
Labels: v0.10.1

#4277 lnwallet: return signer error
  lnwallet/channel.go
Labels: v0.10.1

#4226 Fix crash when ChainNotifier is being accessed too early.
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/interface.go
  chainntnfs/neutrinonotify/neutrino.go
  contractcourt/chain_watcher_test.go
  discovery/gossiper_test.go
  fundingmanager_test.go
  htlcswitch/mock.go
  lnrpc/chainrpc/chainnotifier_server.go
  mock.go
  sweep/test_utils.go
Labels: bug fix, notifications, v0.11

#4291 build: update to latest btcd and btcwallet versions
  go.mod
  go.sum
  lntest/itest/log_error_whitelist.txt
  lnwallet/btcwallet/btcwallet.go
Labels: v0.10.1

#4286 multi: remove global cfg variable
  chainregistry.go
  cmd/lnd/main.go
  config.go
  fundingmanager.go
  fundingmanager_test.go
  lncfg/autopilot.go
  lncfg/bitcoind.go
  lncfg/btcd.go
  lncfg/chain.go
  lncfg/config.go
  lncfg/neutrino.go
  lncfg/tor.go
  lnd.go
  lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
  lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
  lntest/itest/lnd_test.go
  log.go
  peer.go
  pilot.go
  rpcserver.go
  server.go
  server_test.go
  subrpcserver_config.go
Labels: code health, v0.11

#4213 lnrpc: add optional labels to on chain transactions
  breacharbiter.go
  breacharbiter_test.go
  chancloser.go
  cmd/lncli/commands.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_arbitrator_test.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  contractcourt/htlc_success_resolver.go
  fundingmanager.go
  fundingmanager_test.go
  labels/labels.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnrpc/rpc_utils.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  lntest/itest/lnd_test.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/interface.go
  lnwallet/interface_test.go
  mock.go
  rpcserver.go
  sweep/backend_mock_test.go
  sweep/interface.go
  sweep/sweeper.go
  utxonursery.go
  utxonursery_test.go
  watchtower/config.go
  watchtower/lookout/justice_descriptor_test.go
  watchtower/lookout/punisher.go
Labels: accounting, v0.11, wallet

#4183 htlcswitch: sync local payment hand-off to link
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  htlcswitch/switch_test.go
  lntest/itest/lnd_test.go
  lntest/itest/log_error_whitelist.txt
Labels: bug fix, htlcswitch, routing, v0.11

#4227 multi: Remove need for DerivePrivKey from watchtower, brontide, netann and sphinx package
  brontide/conn.go
  brontide/listener.go
  brontide/noise.go
  brontide/noise_test.go
  go.mod
  go.sum
  htlcswitch/circuit_test.go
  keychain/btcwallet.go
  keychain/derivation.go
  keychain/ecdh.go
  keychain/signer.go
  lnd.go
  lnrpc/signrpc/signer_server.go
  mock.go
  netann/chan_status_manager_test.go
  netann/channel_update_test.go
  netann/node_signer.go
  peer.go
  pilot.go
  rpcserver.go
  server.go
  test_utils.go
  watchtower/config.go
  watchtower/standalone.go
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtclient/derivation.go
  watchtower/wtclient/interface.go
  watchtower/wtclient/session_negotiator.go
  watchtower/wtclient/session_queue.go
  watchtower/wtdb/client_session.go
  watchtower/wtmock/keyring.go
  watchtower/wtserver/server.go
Labels: code health, safety, v0.11

#4304 peer: fix struct alignment
  peer.go
Labels: bug fix, v0.10.1

#4300 channeldb+htlcswitch: don't use fastsha256 in tests
  channeldb/payment_control_test.go
  go.mod
  go.sum
  htlcswitch/switch_test.go
  htlcswitch/test_utils.go
Labels: v0.11

#4302 btcwallet: add transaction outputs bounds check to FetchInputInfo
  lnwallet/btcwallet/signer.go
Labels: v0.10.1

#4132 itest: switch over to routerrpc.SendPaymentV2
  lntest/itest/lnd_multi-hop-error-propagation.go
  lntest/itest/lnd_multi-hop-payments.go
  lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
  lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
  lntest/itest/lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go
  lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
  lntest/itest/lnd_send_multi_path_payment.go
  lntest/itest/lnd_single_hop_invoice_test.go
  lntest/itest/lnd_test.go
  lntest/itest/log_error_whitelist.txt
  lntest/itest/psbt.go
Labels: evolution, itests, v0.11

#4015 kvdb wrapper for etcd
  channeldb/channel_test.go
  channeldb/db.go
  channeldb/db_test.go
  channeldb/kvdb/backend.go
  channeldb/kvdb/bbolt.go
  channeldb/kvdb/config.go
  channeldb/kvdb/etcd/bucket.go
  channeldb/kvdb/etcd/bucket_test.go
  channeldb/kvdb/etcd/db.go
  channeldb/kvdb/etcd/db_test.go
  channeldb/kvdb/etcd/driver.go
  channeldb/kvdb/etcd/driver_test.go
  channeldb/kvdb/etcd/embed.go
  channeldb/kvdb/etcd/fixture_test.go
  channeldb/kvdb/etcd/readwrite_bucket.go
  channeldb/kvdb/etcd/readwrite_bucket_test.go
  channeldb/kvdb/etcd/readwrite_cursor.go
  channeldb/kvdb/etcd/readwrite_cursor_test.go
  channeldb/kvdb/etcd/readwrite_tx.go
  channeldb/kvdb/etcd/readwrite_tx_test.go
  channeldb/kvdb/etcd/stm.go
  channeldb/kvdb/etcd/stm_test.go
  channeldb/kvdb/etcd/walletdb_interface_test.go
  channeldb/kvdb/interface.go
  channeldb/kvdb/kvdb_etcd.go
  channeldb/kvdb/kvdb_no_etcd.go
  channeldb/meta_test.go
  channeldb/payment_control_test.go
  channeldb/payments_test.go
  config.go
  go.mod
  go.sum
  lncfg/db.go
  lnd.go
  server.go
Labels: database, incomplete, v0.11

#4309 lnd: fix regression in DB open time logs
  lnd.go
Labels: v0.11

#4228 walletrpc: add LabelTransaction endpoint to retrospectively label txns
  cmd/lncli/walletrpc_active.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  lntest/itest/lnd_test.go
  lntest/itest/log_error_whitelist.txt
  lnwallet/btcwallet/btcwallet.go
  lnwallet/interface.go
  mock.go
Labels: accounting, v0.11, wallet

#4252 multi: rename kvdb Read* types to R*
  autopilot/graph.go
  breacharbiter.go
  chainntnfs/height_hint_cache.go
  channeldb/channel.go
  channeldb/db.go
  channeldb/duplicate_payments.go
  channeldb/forwarding_log.go
  channeldb/forwarding_package.go
  channeldb/forwarding_package_test.go
  channeldb/graph.go
  channeldb/graph_test.go
  channeldb/invoices.go
  channeldb/kvdb/interface.go
  channeldb/meta.go
  channeldb/meta_test.go
  channeldb/migration_01_to_11/db.go
  channeldb/migration_01_to_11/graph.go
  channeldb/migration_01_to_11/invoices.go
  channeldb/migration_01_to_11/migration_09_legacy_serialization.go
  channeldb/migration_01_to_11/migrations_test.go
  channeldb/migration_01_to_11/payment_control.go
  channeldb/migration_01_to_11/payments.go
  channeldb/migtest/raw_db.go
  channeldb/nodes.go
  channeldb/payment_control.go
  channeldb/payments.go
  channeldb/waitingproof.go
  channeldb/witness_cache.go
  contractcourt/briefcase.go
  discovery/message_store.go
  fundingmanager.go
  htlcswitch/decayedlog.go
  htlcswitch/link_test.go
  htlcswitch/payment_result.go
  lntest/itest/log_error_whitelist.txt
  macaroons/store.go
  nursery_store.go
  routing/graph.go
  routing/missioncontrol_store.go
  routing/router.go
  rpcserver.go
  server.go
  sweep/store.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/db_common.go
  watchtower/wtdb/tower_db.go
  watchtower/wtdb/version.go
Labels: v0.11

#4298 channeldb+invoices: minor invoice subscription fixes
  channeldb/invoice_test.go
  channeldb/invoices.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  rpcserver.go
Labels: v0.10.1

#4285 channeldb: index payments by payment addr, use payment hash as fallback
  channeldb/db.go
  channeldb/error.go
  channeldb/invoice_test.go
  channeldb/invoices.go
  channeldb/log.go
  channeldb/migration/create_tlb.go
  channeldb/migration/create_tlb_test.go
  channeldb/migration/log.go
  channeldb/migtest/migtest.go
  htlcswitch/test_utils.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/test_utils_test.go
  invoices/update.go
  lntest/itest/log_error_whitelist.txt
  lntest/timeouts.go
  lntest/timeouts_darwin.go
Labels: database, migration, payments, v0.11

#4320 config+log: remove global RootLogWriter variable
  config.go
  lnd.go
  log.go
  rpcserver.go
Labels: code health, v0.11

#4331 channeldb/invoices: correct stray kvdb.ReadBucket to RBucket
  channeldb/invoices.go
Labels: database, v0.11

#4326 clock: add module support
  clock/go.mod
  go.mod
  lntest/itest/log_error_whitelist.txt
Labels: v0.11

#4332 channeldb: dry run migration logs
  channeldb/db.go
  lnd.go
Labels: v0.10.1

#4327 routing: don't treat bad features as an unexpected error
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_session.go
Labels: payments, v0.10.1
