Repository lightningnetwork/lnd, pull requests merged in 2020-07, with the labels that each got.

#4371 lnrpc: expose all local and remote channel constraints
  cmd/lncli/commands.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  rpcserver.go
Labels: enhancement, funding, rpc, v0.11

#4428 multi: add relative thaw height interpretation
  channeldb/channel.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  lnwallet/chancloser/chancloser.go
  rpcserver.go
Labels: v0.11

#4418 lnwallet/test: anchor vectors
  lnwallet/test_vectors_anchors.json
  lnwallet/test_vectors_legacy.json
  lnwallet/transactions_test.go
Labels: v0.11

#4347 peer: Brontide Peer implementation
  fundingmanager_test.go
  lnpeer/peer.go
  lnwire/commit_sig.go
  lnwire/revoke_and_ack.go
  lnwire/update_add_htlc.go
  lnwire/update_fail_htlc.go
  lnwire/update_fail_malformed_htlc.go
  lnwire/update_fee.go
  lnwire/update_fulfill_htlc.go
  log.go
  peer/brontide.go
  peer/brontide_test.go
  peer/config.go
  peer/interfaces.go
  peer/log.go
  peer/test_utils.go
  rpcserver.go
  server.go
  test_utils.go
Labels: code health, p2p, v0.11

#4281 netann: add new HostAnnouncer to support dynamic IPs via domains
  config.go
  netann/host_ann.go
  netann/host_ann_test.go
  server.go
Labels: v0.11

#971 Add max value in flight flag
  cmd/lncli/cmd_open_channel.go
  fundingmanager.go
  fundingmanager_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  pilot.go
  rpcserver.go
  server.go
Labels: P3, channels, first pass review done, needs testing, rpc, v0.11

#4157 contractcourt: Persist Resolution Outcomes
  channeldb/db.go
  channeldb/reports.go
  channeldb/reports_test.go
  contractcourt/anchor_resolver.go
  contractcourt/briefcase.go
  contractcourt/briefcase_test.go
  contractcourt/chain_arbitrator.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  contractcourt/commit_sweep_resolver.go
  contractcourt/commit_sweep_resolver_test.go
  contractcourt/contract_resolvers.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_incoming_resolver_test.go
  contractcourt/htlc_outgoing_contest_resolver_test.go
  contractcourt/htlc_success_resolver.go
  contractcourt/htlc_success_resolver_test.go
  contractcourt/htlc_timeout_resolver.go
  contractcourt/htlc_timeout_resolver_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  rpcserver.go
Labels: accounting, contracts, database, v0.11

#4456 chanbackup: always close SCB file after reading
  chanbackup/backupfile.go
Labels: bug fix, scb, v0.11

#4429 multi: I wumbo, you wumbo, he she wumbo
  feature/default_sets.go
  feature/manager.go
  fundingmanager.go
  fundingmanager_test.go
  lncfg/protocol.go
  lncfg/protocol_experimental_off.go
  lncfg/protocol_experimental_on.go
  lncfg/protocol_legacy_off.go
  lncfg/protocol_legacy_on.go
  lntest/itest/lnd_multi-hop-payments.go
  lntest/itest/lnd_test.go
  lntest/itest/lnd_wumbo_channels_test.go
  lntest/itest/log_error_whitelist.txt
  lnwire/features.go
  rpcserver.go
  server.go
Labels: enhancement, funding, v0.11

#4412 New config option - disable height hint cache queries
  chainntnfs/bitcoindnotify/bitcoind_test.go
  chainntnfs/btcdnotify/btcd_test.go
  chainntnfs/height_hint_cache.go
  chainntnfs/height_hint_cache_test.go
  chainntnfs/interface_test.go
  chainregistry.go
  config.go
  lnwallet/interface_test.go
Labels: chain handling, cli, notifications, v0.11

#4344 lntest+itest improvements
  lnrpc/walletrpc/walletkit_server.go
  lntest/harness.go
  lntest/itest/lnd_test.go
  lntest/itest/onchain.go
  lntest/node.go
Labels: enhancement, testing, v0.12

#4467 chainntfns: disable height-hint cache followups
  chainntnfs/bitcoindnotify/bitcoind_test.go
  chainntnfs/btcdnotify/btcd_test.go
  chainntnfs/height_hint_cache.go
  chainntnfs/height_hint_cache_test.go
  chainntnfs/interface_test.go
  chainregistry.go
  lnwallet/interface_test.go
Labels: v0.11

#4384 add modified greedy topK centrality heuristic to autopilot
  autopilot/agent.go
  autopilot/betweenness_centrality_test.go
  autopilot/centrality_testdata_test.go
  autopilot/interface.go
  autopilot/top_centrality.go
  autopilot/top_centrality_test.go
Labels: v0.12

#4455 PSBT: add no_publish flag for safe batch channel opens v2
  cmd/lncli/cmd_open_channel.go
  docs/psbt.md
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/psbt.go
  lnwallet/chanfunding/assembler.go
  lnwallet/chanfunding/psbt_assembler.go
  lnwallet/chanfunding/psbt_assembler_test.go
  lnwallet/reservation.go
  rpcserver.go
Labels: cli, psbt, rpc, safety, v0.11

#4430 lnwallet/channel.go: restore bug fixes
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: bug fix, commitments, v0.11

#4390 docs: documentation for the experimental etcd feature
  docs/etcd.md
Labels: database, documentation, v0.11

#4480 lncli: remove new line from password confirmation
  cmd/lncli/commands.go
Labels: v0.11

#4431 channeldb/channel.go: remove unsignedAckedUpdatesKey when we receive revocation
  channeldb/channel.go
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: bug fix, commitments, v0.11

#4408 travis: add integration test on ARM
  .travis.yml
  go.mod
  go.sum
  lntest/harness.go
  lntest/itest/log_error_whitelist.txt
  lntest/itest/log_substitutions.txt
Labels: ARM, CI, golang/build system, travis

#4432 channeldb+lnwallet: store updates the peer should sign under new key
  channeldb/channel.go
  channeldb/channel_test.go
  channeldb/db_test.go
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: bug fix, commitments, v0.11

#4438 chore: Update minimum golang version to 1.13
  docs/INSTALL.md
  go.mod
Labels: v0.11

#4494 travis: add sanity check stage
  .travis.yml
Labels: travis, v0.11
