Repository lightningnetwork/lnd, pull requests merged in 2020-03, with the labels that each got.

#4040 lnrpc+rpcserver: expose short chan id on feereport
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: rpc, v0.10

#4045 cmd/lncli: add --with flag to list channels
  cmd/lncli/commands.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: rpc, v0.10

#4055 peer: remove unused failedChannels channels map
  peer.go
Labels: code health, p2p

#3996 lncli+proto: use original name in jsonpb marshaler and remove json_name fields in proto
  cmd/lncli/cmd_query_probability.go
  cmd/lncli/commands.go
  cmd/lncli/types.go
  lnrpc/autopilotrpc/autopilot.pb.go
  lnrpc/autopilotrpc/autopilot.proto
  lnrpc/chainrpc/chainnotifier.proto
  lnrpc/invoicesrpc/invoices.pb.go
  lnrpc/invoicesrpc/invoices.proto
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnrpc/signrpc/signer.proto
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/watchtowerrpc/watchtower.proto
  lnrpc/wtclientrpc/wtclient.pb.go
  lnrpc/wtclientrpc/wtclient.proto
  rpcserver.go
Labels: code health

#3993 chanbackup: update on-disk backup file with unconfirmed channels
  channel_notifier.go
  channelnotifier/channelnotifier.go
  fundingmanager.go
  fundingmanager_test.go
  lntest/itest/lnd_test.go
  rpcserver.go
Labels: backups, recovery, safety, scb

#1895 fuzz: new fuzz package and lnwire parsing harnesses
  docs/fuzz.md
  docs/go-fuzz/README.md
  docs/go-fuzz/corpus.tar.gz
  docs/go-fuzz/wirefuzz.go
  fuzz/lnwire/accept_channel.go
  fuzz/lnwire/announce_signatures.go
  fuzz/lnwire/channel_announcement.go
  fuzz/lnwire/channel_reestablish.go
  fuzz/lnwire/channel_update.go
  fuzz/lnwire/closing_signed.go
  fuzz/lnwire/commit_sig.go
  fuzz/lnwire/error.go
  fuzz/lnwire/funding_created.go
  fuzz/lnwire/funding_locked.go
  fuzz/lnwire/funding_signed.go
  fuzz/lnwire/fuzz_utils.go
  fuzz/lnwire/gossip_timestamp_range.go
  fuzz/lnwire/init.go
  fuzz/lnwire/node_announcement.go
  fuzz/lnwire/open_channel.go
  fuzz/lnwire/ping.go
  fuzz/lnwire/pong.go
  fuzz/lnwire/query_channel_range.go
  fuzz/lnwire/query_short_chan_ids.go
  fuzz/lnwire/query_short_chan_ids_zlib.go
  fuzz/lnwire/reply_channel_range.go
  fuzz/lnwire/reply_channel_range_zlib.go
  fuzz/lnwire/reply_short_chan_ids_end.go
  fuzz/lnwire/revoke_and_ack.go
  fuzz/lnwire/shutdown.go
  fuzz/lnwire/update_add_htlc.go
  fuzz/lnwire/update_fail_htlc.go
  fuzz/lnwire/update_fail_malformed_htlc.go
  fuzz/lnwire/update_fee.go
  fuzz/lnwire/update_fulfill_htlc.go
  lnwire/query_short_chan_ids.go
Labels: P3, documentation, fuzzing, testing, v0.10

#3963 doc: add Operational Safety Guidelines document
  README.md
  docs/safety.md
Labels: documentation, safety, security, v0.10

#3821 [anchor] pluggable anchor commitments
  breacharbiter.go
  chanbackup/backup.go
  chanbackup/pubsub.go
  channeldb/channel.go
  config.go
  contractcourt/chain_watcher.go
  contractcourt/commit_sweep_resolver.go
  contractcourt/commit_sweep_resolver_test.go
  contractcourt/htlc_success_resolver.go
  contractcourt/htlc_timeout_resolver_test.go
  feature/default_sets.go
  feature/deps.go
  feature/manager.go
  fundingmanager.go
  htlcswitch/link.go
  input/input.go
  input/script_utils.go
  input/script_utils_test.go
  input/size.go
  input/test_utils.go
  input/witnessgen.go
  lncfg/protocol_legacy_off.go
  lncfg/protocol_legacy_on.go
  lntest/itest/lnd_test.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/commitment.go
  lnwallet/interface_test.go
  lnwallet/reservation.go
  lnwallet/transactions.go
  lnwallet/transactions_test.go
  lnwallet/wallet.go
  lnwire/features.go
  server.go
  sweep/txgenerator_test.go
  utxonursery.go
  utxonursery_test.go
Labels: anchors, v0.10

#4048 server+tor: add support for Tor HASHEDPASSWORD authentication method
  config.go
  docs/configuring_tor.md
  server.go
  tor/README.md
  tor/controller.go
Labels: enhancement, tor

#4010 peer: avoid chansync resend loop
  peer.go
Labels: flake fix, p2p

#4071 [trivial] pilot: log whether autopilot is active at startup
  pilot.go
Labels: trivial

#4061 build: update to x/crypto version w/o broken poly1305 arm assembly
  go.mod
  go.sum
Labels: ARM, bug fix, crypto, raspi

#4080 build: bump travis bitcoind version to v0.19.1
  .travis.yml
  scripts/install_bitcoind.sh
Labels: bitcoind, travis, v0.10

#4082 chanbackup: add SCB support for anchor commitments
  chanbackup/backup.go
  chanbackup/pubsub.go
  chanbackup/single.go
  chanbackup/single_test.go
  chanrestore.go
  lncfg/protocol_legacy_on.go
  lntest/itest/lnd_test.go
  lnwallet/commitment.go
Labels: v0.10

#4051 peers: Track errors across connections
  cmd/lncli/commands.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  peer.go
  queue/circular_buf.go
  queue/circular_buf_test.go
  rpcserver.go
  server.go
Labels: enhancement, p2p, v0.10

#3848 [htlcnotifier 4/4]: lnrpc: Add HTLC Event Subscription
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_server.go
  lnrpc/routerrpc/subscribe_events.go
  rpcserver.go
Labels: HTLC, rpc, v0.10

#3758 cnct: anchor output sweeping and fee bumping
  cmd/lncli/walletrpc_active.go
  contractcourt/anchor_resolver.go
  contractcourt/briefcase.go
  contractcourt/briefcase_test.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_arbitrator_test.go
  contractcourt/chain_watcher_test.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  contractcourt/commit_sweep_resolver_test.go
  contractcourt/interfaces.go
  input/size.go
  input/size_test.go
  input/witnessgen.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit_server.go
  lntest/itest/lnd_test.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/test_utils.go
  rpcserver.go
  sweep/sweeper.go
  sweep/sweeper_test.go
Labels: anchors, v0.10

#4104 [trivial] config: remove default values from flag descriptions
  config.go
Labels: v0.10

#4095 lnrpc: Add push amount to listchannels
  channeldb/channel.go
  channeldb/channel_test.go
  go.mod
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: accounting, rpc

#2669 netann+discovery+server: consolidate network announcements to netann pkg
  discovery/chan_series.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/utils.go
  lnwire/node_announcement.go
  netann/chan_status_manager.go
  netann/channel_announcement.go
  netann/channel_update.go
  netann/channel_update_test.go
  netann/node_announcement.go
  netann/sign.go
  server.go
Labels: code health, discovery

#4064 Use batch for historical confirmations filters request.
  chainntnfs/neutrinonotify/neutrino.go
  go.mod
  go.sum
Labels: mobile, neutrino, notifications, optimization

#3969 fuzz/wtwire: adding wtwire fuzzers
  fuzz/wtwire/create_session.go
  fuzz/wtwire/create_session_reply.go
  fuzz/wtwire/delete_session.go
  fuzz/wtwire/delete_session_reply.go
  fuzz/wtwire/error.go
  fuzz/wtwire/fuzz_utils.go
  fuzz/wtwire/init.go
  fuzz/wtwire/state_update.go
  fuzz/wtwire/state_update_reply.go
Labels: fuzzing, wtwire

#4103 [itests] multi hop test move
  lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
  lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
  lntest/itest/lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go
  lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
  lntest/itest/lnd_multi-hop_test.go
  lntest/itest/lnd_test.go
Labels: v0.10

#4110 itest: wait for file writing in wait predicate
  lntest/itest/lnd_test.go
Labels: backups, flake fix, itests

#3924 itest: use fast scrypt options for aezeed, macaroons DB and wallet DB
  aezeed/cipherseed_rpctest.go
  go.mod
  go.sum
  htlcswitch/link.go
  lntest/itest/lnd_test.go
  lntest/timeouts.go
  lnwallet/btcwallet/btcwallet_rpctest.go
  macaroons/security.go
  macaroons/security_rpctest.go
  macaroons/security_test.go
  macaroons/store.go
Labels: v0.10

#4107 htlcswitch: log fixes
  channeldb/channel.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/switch.go
  htlcswitch/switch_test.go
Labels: htlcswitch, logging, v0.10

#3865 calculate betweenness centrality of nodes
  autopilot/betweenness_centrality.go
  autopilot/betweenness_centrality_test.go
  autopilot/interface.go
  autopilot/simple_graph.go
  cmd/lncli/commands.go
  cmd/lncli/main.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: autopilot, rpc, v0.10

#4092 link+peer: buffer messages until link active
  channelnotifier/channelnotifier.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/test_utils.go
  peer.go
  rpcserver.go
Labels: code health, p2p, v0.10

#4073 lntest/itest: select anchor commitment format and sweeping itests
  contractcourt/channel_arbitrator.go
  lntest/itest/lnd_multi-hop_htlc_local_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_local_timeout_test.go
  lntest/itest/lnd_multi-hop_htlc_receiver_chain_claim_test.go
  lntest/itest/lnd_multi-hop_htlc_remote_chain_claim_test.go
  lntest/itest/lnd_multi-hop_local_force_close_on_chain_htlc_timeout_test.go
  lntest/itest/lnd_multi-hop_remote_force_close_on_chain_htlc_timeout_test.go
  lntest/itest/lnd_multi-hop_test.go
  lntest/itest/lnd_test.go
  sweep/txgenerator.go
  sweep/txgenerator_test.go
Labels: v0.10

#4113 routing: minimum failure relaxation interval
  routing/missioncontrol.go
  routing/missioncontrol_state.go
  routing/missioncontrol_state_test.go
  server.go
Labels: v0.10

#4087 watchtower: automatically create tor hidden service if enabled
  config.go
  docs/watchtower.md
  lnd.go
  server.go
  watchtower/config.go
  watchtower/standalone.go
Labels: tor, v0.10, watchtower

#4079 wallet: PSBT channel funding
  cmd/lncli/cmd_open_channel.go
  cmd/lncli/commands.go
  docs/psbt.md
  fundingmanager.go
  go.mod
  go.sum
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  lntest/itest/psbt.go
  lnwallet/chanfunding/assembler.go
  lnwallet/chanfunding/psbt_assembler.go
  lnwallet/chanfunding/psbt_assembler_test.go
  lnwallet/interface_test.go
  lnwallet/reservation.go
  lnwallet/wallet.go
  rpcserver.go
Labels: enhancement, funding, security, v0.10, wallet

#4129 lnrpc: expose commitment type on pending open and waiting close channels
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: v0.10

#4128 routerrpc+lncli: enable subserver by default and switch over lncli sendpayment
  .golangci.yml
  Dockerfile
  build/release/release.sh
  cmd/lncli/cmd_build_route.go
  cmd/lncli/cmd_pay.go
  cmd/lncli/cmd_query_mission_control.go
  cmd/lncli/cmd_query_probability.go
  cmd/lncli/cmd_reset_mission_control.go
  cmd/lncli/commands.go
  cmd/lncli/main.go
  cmd/lncli/routerrpc.go
  cmd/lncli/routerrpc_default.go
  docker/lnd/Dockerfile
  lnrpc/routerrpc/config.go
  lnrpc/routerrpc/config_active.go
  lnrpc/routerrpc/config_default.go
  lnrpc/routerrpc/driver.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_server.go
  lnrpc/routerrpc/routing_config.go
  lnrpc/routerrpc/subscribe_events.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  make/testing_flags.mk
  mobile/README.md
  subrpcserver_config.go
Labels: v0.10
