Repository lightningnetwork/lnd, pull requests merged in 2020-08, with the labels that each got.

#4411 kvdb+etcd+tests: change etcd flattened bucket key derivation to make it compatible with bbolt
  channeldb/channel_test.go
  channeldb/db.go
  channeldb/db_test.go
  channeldb/forwarding_log_test.go
  channeldb/graph_test.go
  channeldb/invoice_test.go
  channeldb/kvdb/etcd/bucket.go
  channeldb/kvdb/etcd/db_test.go
  channeldb/kvdb/etcd/driver_test.go
  channeldb/kvdb/etcd/readwrite_bucket.go
  channeldb/kvdb/etcd/readwrite_bucket_test.go
  channeldb/kvdb/etcd/readwrite_cursor.go
  channeldb/kvdb/etcd/readwrite_cursor_test.go
  channeldb/kvdb/etcd/readwrite_tx.go
  channeldb/kvdb/etcd/readwrite_tx_test.go
  channeldb/kvdb/etcd/stm.go
  channeldb/kvdb/etcd/stm_test.go
  channeldb/meta_test.go
  channeldb/nodes_test.go
  channeldb/payment_control_test.go
  channeldb/payments_test.go
  channeldb/reports_test.go
  channeldb/waitingproof_test.go
  channeldb/witness_cache_test.go
  nursery_store_test.go
  sweep/store_test.go
  utxonursery_test.go
Labels: v0.11

#4506 config: make bbolt freelist settings mutually exclusive
  channeldb/kvdb/config.go
  config.go
  lncfg/db.go
  lnd.go
Labels: boltdb, bug fix, config, v0.11

#4509 rpc: add missing space to error message
  lnrpc/chainrpc/chainnotifier_server.go
Labels: v0.11

#4475 travis: add integration test on Windows
  .travis.yml
  Makefile
  channeldb/forwarding_log.go
  channeldb/forwarding_log_test.go
  go.mod
  go.sum
  lntest/btcd.go
  lntest/itest/lnd_multi-hop-payments.go
  lntest/itest/lnd_test.go
Labels: golang/build system, travis, v0.11, windows

#4511 Bugfix: Allow browsers to send macaroon in WebSocket calls
  docs/rest/websockets.md
  lnrpc/websocket_proxy.go
  lntest/itest/rest_api.go
Labels: REST, bug fix, v0.11, websockets

#4348 multi: create split local/remote database structure
  chainregistry.go
  config.go
  lncfg/db.go
  lnd.go
  peer/brontide.go
  peer/config.go
  pilot.go
  rpcserver.go
  server.go
Labels: database, v0.11

#4526 lnd: properly pass peer remote db for graph, local db for rest
  server.go
Labels: v0.11

#4529 chainntnfs/txnotifier: remove events on teardown
  chainntnfs/txnotifier.go
Labels: v0.11

#4525 rpcserver: no manual close of restored channels
  lntest/itest/lnd_channel_backup_test.go
  lntest/itest/lnd_test.go
  lntest/itest/log_error_whitelist.txt
  rpcserver.go
Labels: backups, bug fix, recovery, scb, v0.11, v0.12

#4521 lnrpc/invoicesrpc: extend hop hint selection to account for MPP
  lnrpc/invoicesrpc/addinvoice.go
Labels: bug fix, invoices, mpp

#4461 lnwallet/test: extend anchor test vector set
  lnwallet/test_vectors_anchors.json
  lnwallet/test_vectors_legacy.json
  lnwallet/transactions_test.go
Labels: anchors, spec, testing, tests, v0.12

#4552 cmd/lncli: fix sendcoins usage message
  cmd/lncli/commands.go
Labels: v0.12

#4434 multi: add labels to lnd native transactions
  breacharbiter.go
  contractcourt/chain_arbitrator.go
  contractcourt/channel_arbitrator.go
  contractcourt/htlc_success_resolver.go
  fundingmanager.go
  fundingmanager_test.go
  labels/labels.go
  lntest/harness.go
  lntest/itest/lnd_test.go
  lnwallet/chancloser/chancloser.go
  server.go
  utxonursery.go
  watchtower/lookout/punisher.go
Labels: accounting, v0.12, wallet

#4531 [trivial] htlcswitch: use kvdb.View for loading fwdpkgs
  channeldb/forwarding_package.go
  htlcswitch/switch.go
Labels: v0.12

#4505 lnd: removing activeNetParams global, passed around instead via configs
  chainparams.go
  chainregistry.go
  config.go
  fundingmanager_test.go
  lnd.go
  mock.go
  pilot.go
  rpcserver.go
  server.go
Labels: code health, refactoring, v0.12

#4380 build: add all subservers to dev build with an optional with-rpc build param
  make/testing_flags.mk
Labels: v0.12

#4550 README: update link to security disclosure GPG key
  README.md
Labels: security, v0.12

#4548 watchtower: remove dev tag from unit test files
  watchtower/lookout/justice_descriptor_test.go
  watchtower/lookout/lookout_test.go
  watchtower/lookout/mock.go
  watchtower/wtclient/client_test.go
Labels: v0.12

#4493 invoices: garbage collect settled/canceled invoices
  channeldb/invoice_test.go
  channeldb/invoices.go
  config.go
  invoices/invoice_expiry_watcher.go
  invoices/invoice_expiry_watcher_test.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  server.go
Labels: database, invoices, v0.12

#4479 healthcheck: add regular chain backend and disk space checks
  build/log_shutdown.go
  build/logrotator.go
  cmd/lncli/cmd_open_channel.go
  cmd/lnd/main.go
  config.go
  go.mod
  go.sum
  healthcheck/diskcheck.go
  healthcheck/diskcheck_solaris.go
  healthcheck/diskcheck_windows.go
  healthcheck/healthcheck.go
  healthcheck/healthcheck_test.go
  healthcheck/log.go
  lncfg/healthcheck.go
  log.go
  mobile/bindings.go
  sample-lnd.conf
  server.go
  signal/signal.go
Labels: logging, safety, v0.12, windows

#4551 lnd: Add CORS support to the WalletUnlocker proxy
  lnd.go
  rpcserver.go
Labels: v0.12

#4527 fundingmanager: configurable remote max htlcs
  config.go
  fundingmanager.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/harness.go
  lntest/itest/lnd_test.go
  rpcserver.go
  server.go
Labels: config, funding, v0.12

#4570 btcwallet: skip unsupported addresses in ListTransasctionDetails
  lnwallet/btcwallet/btcwallet.go
Labels: bug fix, v0.12, wallet

#4560 Shim funded channels: don't count towards max pending channels, allow to abandon them
  fundingmanager.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  lnwallet/reservation.go
  rpcserver.go
Labels: funding, rpc, v0.11.1

#4580 fundingmanager: hold lock during loop
  fundingmanager.go
Labels: bug fix, concurrency, funding
