Repository lightningnetwork/lnd, pull requests merged in 2021-07, with the labels that each got.

#5452 aezeed: export wordlist and properties
  aezeed/cipherseed.go
  aezeed/cipherseed_test.go
  aezeed/wordlist.go
Labels: refactoring, trivial

#5280 htlcswitch: set sourceRef when resolving packets through interceptor
  htlcswitch/interceptable_switch.go
  lntest/itest/lnd_forward_interceptor_test.go
Labels: bug fix, htlcswitch

#5457 lnd+config+sample-lnd.conf: add wallet-unlock-allow-create flag
  config.go
  lnd.go
  sample-lnd.conf
Labels: security, wallet

#5478 lnwallet: fix payment regression introduced by MayAddOutgoingHtlc
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: bug fix, channel management, commitments, wallet

#5479 lnrpc/routerrrpc+routing: fix send to route error propagation
  channeldb/payment_control.go
  routing/payment_lifecycle.go
  routing/router.go
  routing/router_test.go
Labels: bug fix, routing

#5383 docs+Makefile: update fuzz.md to explain new build/run process
  Makefile
  docs/fuzz.md
Labels: documentation, fuzzing

#5525 harness: remove killed nodes from active nodes
  kvdb/etcd/embed.go
  lntest/harness.go
Labels: etcd, itests, test flake

#5545 mod+GitHub: shorten PR template, bump golang to 1.15
  .github/pull_request_template.md
  docs/release-notes/release-notes-0.14.0.md
  go.mod
Labels: docs

#5516 etcd: kvdb fixes
  kvdb/debug.go
  kvdb/etcd/debug.go
  kvdb/etcd/nodebug.go
  kvdb/etcd/readwrite_bucket.go
  kvdb/etcd/readwrite_cursor.go
  kvdb/etcd_test.go
  kvdb/nodebug.go
Labels: etcd, performance, tests

#5547 etcd: optionally reduce concurrency to single writer for legacy code
  docs/release-notes/release-notes-0.14.0.md
  kvdb/etcd/config.go
  kvdb/etcd/db.go
  kvdb/etcd/fixture.go
  kvdb/etcd/readwrite_tx.go
  kvdb/etcd_test.go
Labels: compatibility, database, etcd

#5526 Allow lnd to be imported into projects that are compiled to WASM
  docs/release-notes/release-notes-0.14.0.md
  go.sum
  healthcheck/diskcheck.go
  healthcheck/diskcheck_js.go
  kvdb/backend.go
  kvdb/backend_js.go
  kvdb/bolt_compact.go
  kvdb/interface.go
  lnwallet/btcwallet/config.go
Labels: golang/build system

#5514 payments: allocate payment sequences in blocks
  channeldb/payment_control.go
  docs/release-notes/release-notes-0.14.0.md
Labels: database, etcd, optimization

#5542 build: add itest-race build target to catch data races with itests
  Makefile
  docs/release-notes/release-notes-0.14.0.md
Labels: data-race, itests

#5553 Remove warning about pruned nodes
  docs/INSTALL.md
  docs/release-notes/release-notes-0.14.0.md
Labels: documentation

#5576 mod: upgrade miekg/dns library to fix dependabot alert
  docs/release-notes/release-notes-0.14.0.md
  go.mod
  go.sum
Labels: dependencies, security

#5579 itest: fix async payment benchmark timeout flakes
  docs/release-notes/release-notes-0.14.0.md
  lntest/itest/lnd_payment_test.go
Labels: flake fix, itests
