Repository lightningnetwork/lnd, pull requests merged in 2021-02, with the labels that each got.

#4911 lnrpc+mobile: use docker to compile/format protos
  .github/workflows/main.yml
  .travis.yml
  Makefile
  lnrpc/Dockerfile
  lnrpc/README.md
  lnrpc/gen_protos.sh
  lnrpc/gen_protos_docker.sh
  mobile/gen_bindings.sh
  scripts/install_travis_proto.sh
Labels: P3, docker, gRPC, golang/build system

#4974 Fix typo in restorechanbackup command description
  cmd/lncli/commands.go
  docs/recovery.md
Labels: typo, v0.13

#4902 lntest/channels: introduce subpackage to deduplicate static structs
  breacharbiter_test.go
  channeldb/channel_test.go
  contractcourt/briefcase_test.go
  htlcswitch/test_utils.go
  lntest/channels/channels.go
  peer/test_utils.go
Labels: P3, refactoring, testing, v0.13

#4934 discovery: pinned syncers
  config.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/sync_manager.go
  discovery/sync_manager_test.go
  discovery/syncer.go
  discovery/syncer_test.go
  lncfg/gossip.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/itest/lnd_test.go
  rpcserver.go
  sample-lnd.conf
  server.go
Labels: P2, v0.12.1, v0.13

#4924 routerrpc,routing: limit max parts if the invoice doesn't declare MPP support
  lnrpc/routerrpc/router_backend.go
  routing/payment_session.go
Labels: P2, bug fix, invoices, payments, v0.12.1, v0.13

#4961 build: update CI builds to use go 1.15.7
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .travis.yml
  lnrpc/Dockerfile
Labels: P1, v0.12.1, v0.13

#4979 routing: add new TestPaymentAddrOnlyNoSplit test case
  routing/integrated_routing_context_test.go
  routing/integrated_routing_test.go
Labels: payments, routing, testing, v0.12.1

#4915 multi: store bool to determine retransmission ordering
  channeldb/channel.go
  htlcswitch/link_test.go
  lnwallet/channel.go
Labels: P1, htlcswitch, spec, v0.12.1, v0.13

#4980 v0.12.1-beta.rc1
  .github/workflows/docker.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .travis.yml
  Makefile
  breacharbiter_test.go
  build/version.go
  channeldb/channel.go
  channeldb/channel_test.go
  cmd/lncli/commands.go
  config.go
  contractcourt/briefcase_test.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/sync_manager.go
  discovery/sync_manager_test.go
  discovery/syncer.go
  discovery/syncer_test.go
  docker/lnd/start-lnd.sh
  docs/recovery.md
  htlcswitch/link_test.go
  htlcswitch/test_utils.go
  lncfg/gossip.go
  lnrpc/Dockerfile
  lnrpc/README.md
  lnrpc/gen_protos.sh
  lnrpc/gen_protos_docker.sh
  lnrpc/invoicesrpc/config_active.go
  lnrpc/invoicesrpc/invoices_server.go
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  lntest/channels/channels.go
  lntest/itest/lnd_test.go
  lnwallet/channel.go
  mobile/gen_bindings.sh
  monitoring/monitoring_on.go
  netann/chan_status_manager.go
  netann/channel_update.go
  peer/test_utils.go
  routing/integrated_routing_context_test.go
  routing/integrated_routing_test.go
  routing/payment_session.go
  rpcserver.go
  sample-lnd.conf
  scripts/install_travis_proto.sh
  scripts/verify-install.sh
  server.go
  subrpcserver_config.go
Labels: v0.12.1

#4996 itest: add coverage for hold invoices with hop hints
  lntest/itest/lnd_test.go
Labels: P1, itests

#5003 Revert "Merge pull request #4895 from wpaulino/disallow-premature-cha…
  discovery/gossiper.go
  discovery/gossiper_test.go
Labels: v0.12.1

#4945 discovery: no graph sync
  discovery/sync_manager.go
  discovery/sync_manager_test.go
  lntest/itest/lnd_test.go
Labels: P2, graph, optimization, v0.12.1, v0.13

#5006 discovery: use token bucket based rate limiting to throttle gossip
  discovery/gossiper.go
  discovery/gossiper_test.go
  lncfg/protocol_legacy_off.go
  lncfg/protocol_legacy_on.go
  lntest/node.go
  server.go
Labels: v0.12.1

#4964 channeldb+routing+gossiper: add local updates to graph immediately
  batch/interface.go
  batch/scheduler.go
  channeldb/graph.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  routing/router.go
Labels: P1, blocked, bug fix, database, graph, v0.12.1, v0.13

#4909 routing: allow runtime updates to mission control config
  cmd/lncli/cmd_mc_cfg_get.go
  cmd/lncli/cmd_mc_cfg_set.go
  cmd/lncli/routerrpc.go
  lnrpc/rest-annotations.yaml
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.pb.gw.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_backend_test.go
  lnrpc/routerrpc/router_server.go
  lntest/itest/lnd_test.go
  routing/integrated_routing_context_test.go
  routing/missioncontrol.go
  routing/missioncontrol_test.go
  routing/mock_test.go
  routing/payment_session_test.go
  routing/probability_estimator.go
  routing/probability_estimator_test.go
  routing/router_test.go
  server.go
Labels: P2, enhancement, mission control, routing

#5007 lncfg: add IPv6 resolution bypass & account for local hostname aliases
  lncfg/address.go
Labels: v0.12.1

#4988 lncfg: add isIPv6Host helper to force v6 addrs through system resolver
  lncfg/address.go
Labels: P1, bug fix, tor, v0.12.1, v0.13

#4899 [gossiper] Ignore received ChannelAnnouncements for own channels
  discovery/gossiper.go
  discovery/gossiper_test.go
  server.go
Labels: P1, bug fix, database, gossip

#5009 v0.12.1-beta.rc2
  Makefile
  batch/interface.go
  batch/scheduler.go
  build/version.go
  channeldb/graph.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/sync_manager.go
  discovery/sync_manager_test.go
  docs/release.md
  lncfg/address.go
  lncfg/protocol_legacy_off.go
  lncfg/protocol_legacy_on.go
  lntest/itest/lnd_test.go
  lntest/node.go
  routing/router.go
  server.go
Labels: v0.12.1

#5013 github/workflows: pin exact docker release
  .github/workflows/main.yml
  .github/workflows/release.yaml
Labels: golang/build system, v0.12.1

#5020 config: clean and expand backup file path
  config.go
Labels: bug fix, config

#5021 scripts: allow verification of custom binary
  scripts/verify-install.sh
Labels: verification

#5019 release: create and verify detached signatures, fix hashing command on MacOS
  .github/workflows/release.yaml
  docs/release.md
  scripts/release.sh
  scripts/verify-install.sh
Labels: golang/build system, v0.12.1, verification

#5023 scripts/verify-install: require 5 of 7 signatures before accepting
  scripts/verify-install.sh
Labels: v0.12.1

#5016 lntest: update error log whitelist
  lntest/itest/log_error_whitelist.txt
Labels: flake fix, trivial, v0.12.1

#5026 htlcswitch: init mockFeeEstimator in other LinkChannelConfigs
  htlcswitch/link_test.go
  htlcswitch/mock.go
  htlcswitch/test_utils.go
Labels: flake fix, trivial, v0.12.1

#5017 routing: if MaxShardAmt is set, then use that as a ceiling for our splits, use default of 16 for MaxParts
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lntest/itest/lnd_multi-hop-error-propagation_test.go
  routing/integrated_routing_context_test.go
  routing/integrated_routing_test.go
  routing/payment_session.go
  routing/router.go
Labels: P1, enhancement, payments, rpc

#5027 v0.12.1-beta.rc4
  .github/workflows/release.yaml
  build/version.go
  cmd/lncli/cmd_pay.go
  config.go
  docs/release.md
  htlcswitch/link_test.go
  htlcswitch/mock.go
  htlcswitch/test_utils.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lntest/itest/lnd_multi-hop-error-propagation_test.go
  lntest/itest/log_error_whitelist.txt
  routing/integrated_routing_context_test.go
  routing/integrated_routing_test.go
  routing/payment_session.go
  routing/router.go
  scripts/release.sh
  scripts/verify-install.sh
Labels: v0.12.1

#5037 release: fix golang version issue in docker-release and shasum issue in verification script
  Makefile
  scripts/verify-install.sh
Labels: makefile, releases, v0.12.1

#5039 v0.12.1-beta.rc5
  .github/workflows/main.yml
  Makefile
  build/version.go
  cmd/lncli/cmd_pay.go
  lnrpc/routerrpc/router_backend.go
  lntest/itest/lnd_multi-hop-error-propagation_test.go
  scripts/verify-install.sh
Labels: releases, v0.12.1

#5046 lntest/itest: add websocket close to error whitelist
  lntest/itest/log_error_whitelist.txt
Labels: flake fix, trivial

#5043 routing: dial back max concurrent block fetches
  routing/router.go
  routing/router_test.go
Labels: v0.12.1

#5045 v0.12.1-beta.rc6
  build/version.go
  routing/router.go
  routing/router_test.go
Labels: v0.12.1

#5038 make: add unit-debug target
  Makefile
  make/testing_flags.mk
Labels: golang/build system, makefile

#3191 Add option for deleting failed-only payments.
  channeldb/payment_control_test.go
  channeldb/payments.go
  channeldb/payments_test.go
  lnrpc/rpc.pb.go
  lnrpc/rpc.pb.gw.go
  lnrpc/rpc.proto
  lnrpc/rpc.swagger.json
  rpcserver.go
Labels: P1, database, rpc, v0.13

#5049 lnd+lnwallet: make capacity check stricter by adding fee
  breacharbiter_test.go
  lnwallet/commitment.go
Labels: P1, commitments, tests, v0.13
