Repository lightningnetwork/lnd, pull requests merged in 2022-01, with the labels that each got.

#6053 invoice: fix inactive client not cleaned from invoice registry
  docs/release-notes/release-notes-0.15.0.md
  invoices/invoiceregistry.go
  lnrpc/invoicesrpc/invoices_server.go
Labels: payments, bug fix

#6082 peer: fix competing connections to the same peer
  discovery/bootstrapper.go
  docs/release-notes/release-notes-0.14.2.md
  lnwallet/channel.go
  lnwallet/wallet.go
  peer/brontide.go
  peer/test_utils.go
  routing/notifications.go
  server.go
Labels: p2p, networking, bug fix

#6116 itest: increase pg database connection limit
  Makefile
  docs/release-notes/release-notes-0.14.2.md
Labels: itests, postgres

#6113 Edited mobile documentation for mobile developers [skip ci]
  docs/release-notes/release-notes-0.15.0.md
  mobile/README.md
  mobile/docs/proto_folder.png
  mobile/docs/separate_gradle_module.png
Labels: documentation, mobile

#6054 discovery: resend premature messages when block height reached
  chainntnfs/txnotifier.go
  discovery/gossiper.go
  discovery/reliable_sender.go
  discovery/sync_manager.go
  docs/release-notes/release-notes-0.15.0.md
  funding/manager.go
  routing/errors.go
  routing/router.go
  routing/validation_barrier.go
  routing/validation_barrier_test.go
Labels: discovery, bug fix

#6124 contractcourt: use "info" log level for messages leading to force-closes
  contractcourt/channel_arbitrator.go
  docs/release-notes/release-notes-0.15.0.md
Labels: documentation, contracts

#6052 itest: prepare itest for major refactor
  lntest/harness_miner.go
  lntest/harness_net.go
  lntest/harness_node.go
  lntest/itest/assertions.go
  lntest/itest/lnd_channel_force_close_test.go
  lntest/itest/lnd_open_channel_test.go
  lntest/itest/lnd_rpc_middleware_interceptor_test.go
  lntest/itest/lnd_test.go
  lntest/test_common.go
Labels: flake fix

#6006 Allow remote signer to run without chain backend
  chainreg/chainregistry.go
  chainreg/no_chain_backend.go
  config.go
  config_builder.go
  docs/release-notes/release-notes-0.14.2.md
  docs/remote-signing.md
  go.mod
  go.sum
  input/signer.go
  lncfg/chain.go
  lncfg/healthcheck.go
  lncfg/remotesigner.go
  lnrpc/signrpc/signer_server.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.pb.gw.go
  lnrpc/walletrpc/walletkit.pb.json.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit.yaml
  lnrpc/walletrpc/walletkit_grpc.pb.go
  lnrpc/walletrpc/walletkit_server.go
  lntest/itest/lnd_psbt_test.go
  lntest/itest/lnd_remote_signer_test.go
  lntest/itest/lnd_test_list_on_test.go
  lntest/mock/walletcontroller.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/btcwallet/config.go
  lnwallet/btcwallet/log.go
  lnwallet/btcwallet/psbt.go
  lnwallet/btcwallet/psbt_test.go
  lnwallet/btcwallet/signer.go
  lnwallet/btcwallet/signer_test.go
  lnwallet/interface.go
  lnwallet/log.go
  lnwallet/rpcwallet/healthcheck.go
  lnwallet/rpcwallet/log.go
  lnwallet/rpcwallet/rpcwallet.go
  log.go
  sample-lnd.conf
  server.go
Labels: psbt, signrpc, remote signer

#6080 multi: consolidate trivial PRs that are stuck on CI pipeline steps
  .golangci.yml
  channeldb/channel.go
  channeldb/graph.go
  channeldb/payments.go
  config.go
  contrib/init/lnd.service
  docs/DOCKER.md
  docs/INSTALL.md
  docs/code_contribution_guidelines.md
  docs/grpc/java.md
  docs/grpc/javascript.md
  docs/postgres.md
  docs/recovery.md
  docs/release-notes/release-notes-0.15.0.md
  lntest/harness_net.go
  lntest/harness_node.go
  lntest/itest/assertions.go
  lnwire/writer.go
Labels: docs

#6144 peer: always defer clean up of the block epoch client used for ping headers
  docs/release-notes/release-notes-0.14.2.md
  lnwire/lnwire_test.go
  lnwire/ping.go
  lnwire/pong.go
  peer/brontide.go
  peer/brontide_test.go
  server.go
Labels: bug fix

#6152 lncli: closechannel chan_point flag
  cmd/lncli/commands.go
  cmd/lncli/commands_test.go
  docs/release-notes/release-notes-0.15.0.md
Labels: cli

#6159 contractcourt: catch error when no historical bucket exists
  channeldb/db.go
  channeldb/db_test.go
  contractcourt/channel_arbitrator.go
  docs/release-notes/release-notes-0.14.2.md
Labels: bug fix, legacy nodes

#6111 kvdb+channeldb: speed up graph cache
  channeldb/graph.go
  channeldb/graph_cache.go
  channeldb/graph_test.go
  docs/release-notes/release-notes-0.14.2.md
  go.mod
  kvdb/etcd/readwrite_bucket.go
  kvdb/interface.go
  kvdb/postgres/readwrite_bucket.go
  kvdb/postgres/readwrite_tx.go
  kvdb/postgres_test.go
  kvdb/readwrite_bucket_test.go
  routing/router.go
Labels: database, graph, optimization, postgres

#6181 General improvements to mobile instructions
  docs/INSTALL.md
  docs/release-notes/release-notes-0.14.2.md
  mobile/README.md
Labels: gRPC, mobile, docs

#6158 server+contractcourt: create breachResolver to ensure htlc's are failed back
  contractcourt/breach_resolver.go
  contractcourt/breacharbiter.go
  contractcourt/briefcase.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_watcher.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  docs/release-notes/release-notes-0.14.2.md
  server.go
Labels: contracts, refactoring

#6197 lntest/test: ensure nodes connected before disconnecting
  lntest/itest/lnd_channel_policy_test.go
Labels: itests, flake fix

#6182 invoicerpc: refactor SelectHopHints to allow external use
  docs/release-notes/release-notes-0.15.0.md
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/invoicesrpc/addinvoice_test.go
Labels: rpc, invoices
