Repository lightningnetwork/lnd, pull requests merged in 2023-03, with the labels that each got.

#7471 rpc: assign peer alias lookup error string
  docs/release-notes/release-notes-0.16.0.md
  rpcserver.go
Labels: rpc

#7446 discovery: flatten future msg cache and increase its size
  discovery/gossiper.go
  discovery/gossiper_test.go
  go.mod
  go.sum
Labels: no-changelog

#7485 build: bump version to v0.16.0-rc2
  build/version.go
Labels: no-itest

#7483 multi: fix wait.NoError and sub-test names
  chainntnfs/bitcoindnotify/bitcoind_test.go
  chainntnfs/test_utils.go
  lntest/wait/wait.go
Labels: no-changelog

#7492 Add trace logs for `discovery` to catch test flakes
  discovery/gossiper.go
  discovery/syncer.go
  lntest/node/config.go
  server.go
Labels: discovery, itests, no-changelog

#7508 multi: make linter happy
  build/version.go
  config_builder.go
  lnutils/chan.go
  lnwallet/mock.go
  lnwallet/rebroadcaster_test.go
  lnwallet/wallet.go
Labels: no-changelog

#7510 lncli: allow specifying `--min_confs` in `wallet psbt fund` to select unconfirmed inputs
  cmd/lncli/walletrpc_active.go
  docs/release-notes/release-notes-0.16.1.md
Labels: no-itest

#7511 itest+lntest: make sure states are cleaned when tests end
  itest/lnd_htlc_test.go
  lntest/harness.go
Labels: itests, no-changelog

#7331 [3/?] - lnwire: add new TLV record types + messages for taproot chans
  channeldb/graph.go
  discovery/gossiper.go
  docs/release-notes/release-notes-0.17.0.md
  htlcswitch/link_test.go
  lnrpc/routerrpc/router_backend.go
  lnrpc/signrpc/signer_server.go
  lnwallet/chancloser/chancloser.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/rpcwallet/rpcwallet.go
  lnwallet/sigpool.go
  lnwire/accept_channel.go
  lnwire/channel_reestablish.go
  lnwire/closing_signed.go
  lnwire/commit_sig.go
  lnwire/extra_bytes.go
  lnwire/features.go
  lnwire/funding_created.go
  lnwire/funding_locked.go
  lnwire/funding_signed.go
  lnwire/fuzz_test.go
  lnwire/lnwire.go
  lnwire/lnwire_test.go
  lnwire/musig2.go
  lnwire/open_channel.go
  lnwire/partial_sig.go
  lnwire/revoke_and_ack.go
  lnwire/shutdown.go
  lnwire/signature.go
  lnwire/signature_test.go
  lnwire/writer.go
  lnwire/writer_test.go
  netann/channel_announcement.go
  netann/channel_announcement_test.go
  netann/channel_update.go
  routing/router_test.go
  server.go
  watchtower/blob/justice_kit.go
  watchtower/blob/justice_kit_test.go
  watchtower/lookout/justice_descriptor_test.go
  watchtower/lookout/lookout_test.go
  watchtower/wtclient/backup_task.go
  watchtower/wtclient/backup_task_internal_test.go
  zpay32/decode.go
  zpay32/encode.go
Labels: wire protocol, tlv, taproot, taproot chans

#7490 Return FEE_INSUFFICIENT before checking balance for incoming low-fee HTLCs
  docs/release-notes/release-notes-0.16.1.md
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/switch_test.go
Labels: privacy, htlcswitch

#7500 Makefile: add testing_flags to coverage test
  Makefile
  make/testing_flags.mk
Labels: no-itest, no-changelog

#7059 multi+towers: add ClientSessionFilterFn option
  docs/release-notes/release-notes-0.16.1.md
  lnrpc/wtclientrpc/wtclient.go
  lnrpc/wtclientrpc/wtclient.pb.go
  lnrpc/wtclientrpc/wtclient.proto
  lnrpc/wtclientrpc/wtclient.swagger.json
  watchtower/wtclient/client.go
  watchtower/wtclient/interface.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtmock/client_db.go
Labels: rpc, watchtower, bug fix, optimization

#7514 itest+rpcserver: fix itest flake in `3rd_party_anchor_spend`
  docs/release-notes/release-notes-0.16.1.md
  itest/lnd_onchain_test.go
  rpcperms/interceptor.go
  rpcserver.go
Labels: rpc, itests, flake fix

#7069 watchtower: start using the DeleteSession message
  docs/release-notes/release-notes-0.16.1.md
  itest/list_on_test.go
  itest/lnd_watchtower_test.go
  lncfg/wtclient.go
  lnrpc/wtclientrpc/wtclient.go
  lntest/rpc/watchtower.go
  sample-lnd.conf
  server.go
  watchtower/wtclient/addr_iterator.go
  watchtower/wtclient/addr_iterator_test.go
  watchtower/wtclient/candidate_iterator.go
  watchtower/wtclient/candidate_iterator_test.go
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtclient/errors.go
  watchtower/wtclient/interface.go
  watchtower/wtclient/sess_close_min_heap.go
  watchtower/wtclient/sess_close_min_heap_test.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtdb/log.go
  watchtower/wtdb/migration6/client_db.go
  watchtower/wtdb/migration6/client_db_test.go
  watchtower/wtdb/migration6/codec.go
  watchtower/wtdb/migration6/log.go
  watchtower/wtdb/migration7/client_db.go
  watchtower/wtdb/migration7/client_db_test.go
  watchtower/wtdb/migration7/codec.go
  watchtower/wtdb/migration7/log.go
  watchtower/wtdb/version.go
  watchtower/wtmock/client_db.go
Labels: watchtower, disk space

#7533 travis: increase timeout to 120 minutes
  .travis.yml
Labels: travis, itests, no-itest, no-changelog

#7531 Fix web fee estimator test flake and increase retry timeout for channel close
  lntest/harness.go
  lnwallet/chainfee/estimator_test.go
Labels: flake fix, no-changelog

#7526 multi: add more trace logs regarding link activate flow
  discovery/gossiper.go
  discovery/message_store.go
  htlcswitch/link.go
  peer/brontide.go
Labels: logging, no-changelog

#7528 itest: assert change output type
  itest/lnd_misc_test.go
  itest/lnd_psbt_test.go
Labels: itests, taproot, no-changelog

#7541 watchtower: let client recover after data loss
  docs/release-notes/release-notes-0.16.1.md
  watchtower/wtclient/client_test.go
  watchtower/wtclient/errors.go
  watchtower/wtclient/interface.go
  watchtower/wtclient/session_negotiator.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtmock/client_db.go
Labels: watchtower, bug fix
