Repository lightningnetwork/lnd, pull requests merged in 2023-04, with the labels that each got.

#7576 lnd: merge v0.17.0 staging branch into master
  channeldb/invoice_test.go
  channeldb/invoices.go
  docs/release-notes/release-notes-0.17.0.md
  invoices/invoiceregistry.go
  invoices/invoices.go
  invoices/update.go
Labels: github, branching

#7560 docker+docs: bump btcd version
  docker/btcd/Dockerfile
  docs/INSTALL.md
Labels: no-itest, no-changelog

#7585 lnd: manual merge docker bump into master branch
  docker/btcd/Dockerfile
  docs/INSTALL.md
Labels: no-itest, no-changelog

#7582 build: update build system to Go 1.20.3
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .travis.yml
  Dockerfile
  dev.Dockerfile
  make/builder.Dockerfile
Labels: golang/build system, no-changelog

#7442 docs: add notes on contents of Postgres DB as Key-Value store to Postgres.md
  docs/postgres.md
  docs/release-notes/release-notes-0.16.0.md
Labels: documentation, postgres, no-itest

#7563 lnutils: add methods `ForEach`, `Len` and `LoadOrStore` to `SyncMap`
  lnutils/sync_map.go
  lnutils/sync_map_test.go
Labels: no-changelog

#7513 wallet: improve logging around transaction broadcast failures
  docs/release-notes/release-notes-0.16.1.md
Labels: no-itest

#7593 docs: update remote signing docs
  docs/remote-signing.md
Labels: no-itest, no-changelog

#7603 funding: use p2tr by default for batch_open_channel
  docs/release-notes/release-notes-0.16.1.md
  funding/batch.go
  itest/lnd_funding_test.go
  lntest/harness_assertion.go
Labels: funding, taproot

#7604 Log Output Fix (Missing Value)
  docs/release-notes/release-notes-0.16.1.md
  netann/chan_status_manager.go
Labels: no-changelog

#7597 Update `channelLink` policy correctly when opening channel with custom fee parameters
  docs/release-notes/release-notes-0.16.1.md
  funding/manager.go
  funding/manager_test.go
  itest/lnd_custom_message_test.go
  itest/lnd_open_channel_test.go
  peer/brontide.go
  server.go
Labels: funding, channel management, bug fix

#7608 make: clean up container after linting
  Makefile
Labels: docker, no-itest, no-changelog

#7614 lntest+lnd: gracefully shutdown pprof server
  lnd.go
  lntest/node/harness_node.go
  lntest/wait/timeouts.go
Labels: no-changelog

#7637 Fix panic when canceling rebroadcast for neutrino backend
  sweeper_wallet.go
Labels: neutrino, bug fix, no-changelog

#7635 routing: log node pubkey as hex
  routing/router.go
Labels: no-itest, no-changelog

#7643 multi: catch a few uncaught instances of "funding locked"
  channeldb/channel.go
  channeldb/legacy_serialization.go
  funding/manager.go
  funding/manager_test.go
  htlcswitch/link.go
  htlcswitch/switch_test.go
Labels: no-changelog

#7647 contractcourt: skip checkpoint htlc outgoing resolver if it's resolved
  contractcourt/channel_arbitrator.go
  contractcourt/htlc_timeout_resolver.go
Labels: HTLC, mempool, no-changelog
