Repository lightningnetwork/lnd, pull requests merged in 2023-09, with the labels that each got.

#7906 Create release-notes-0.18.0.md
  docs/release-notes/release-notes-0.18.0.md
Labels: documentation, no-itest, no-changelog

#7175 channeldb: properly decide and handle payment status
  channeldb/duplicate_payments.go
  channeldb/mp_payment.go
  channeldb/mp_payment_test.go
  channeldb/payment_control.go
  channeldb/payment_control_test.go
  channeldb/payment_status.go
  channeldb/payment_status_test.go
  channeldb/payments.go
  cmd/lncli/cmd_payments.go
  docs/release-notes/release-notes-0.18.0.md
  itest/lnd_max_htlcs_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_server.go
  routing/control_tower.go
  routing/control_tower_test.go
  routing/router.go
Labels: payments

#7957 gomod: sync versions for submodules
  cert/go.mod
  cert/go.sum
  clock/go.mod
  clock/go.sum
  go.mod
  go.sum
  healthcheck/go.mod
  healthcheck/go.sum
  kvdb/go.mod
  kvdb/go.sum
  tlv/go.mod
  tlv/go.sum
  tor/go.mod
  tor/go.sum
Labels: no-changelog

#7944 multi: bump Go versions
  .golangci.yml
  Dockerfile
  cert/go.mod
  cert/go.sum
  clock/go.mod
  clock/go.sum
  docker/btcd/Dockerfile
  docker/ltcd/Dockerfile
  healthcheck/go.mod
  healthcheck/go.sum
  kvdb/go.mod
  kvdb/go.sum
  lnrpc/Dockerfile
  lnrpc/autopilotrpc/autopilot.pb.go
  lnrpc/chainrpc/chainkit.pb.go
  lnrpc/chainrpc/chainnotifier.pb.go
  lnrpc/devrpc/dev.pb.go
  lnrpc/gen_protos_docker.sh
  lnrpc/invoicesrpc/invoices.pb.go
  lnrpc/lightning.pb.go
  lnrpc/lnclipb/lncli.pb.go
  lnrpc/neutrinorpc/neutrino.pb.go
  lnrpc/peersrpc/peers.pb.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/signrpc/signer.pb.go
  lnrpc/stateservice.pb.go
  lnrpc/verrpc/verrpc.pb.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletunlocker.pb.go
  lnrpc/watchtowerrpc/watchtower.pb.go
  lnrpc/wtclientrpc/wtclient.pb.go
  make/builder.Dockerfile
  queue/go.mod
  ticker/go.mod
  tlv/go.mod
  tlv/go.sum
  tools/Dockerfile
  tools/go.mod
  tools/go.sum
  tor/go.mod
  tor/go.sum
Labels: no-changelog

#7955 kvdb/sqlbase: fix params used in `randRetryDelay`
  .github/workflows/main.yml
  Makefile
  kvdb/go.mod
  kvdb/go.sum
  kvdb/sqlbase/db.go
  kvdb/sqlbase/sqlerrors.go
  scripts/tidy_modules.sh
  scripts/unit_test_modules.sh
Labels: bug fix, no-changelog

#7954 multi: fix unit test flakes
  aezeed/cipherseed_test.go
  chainntnfs/bitcoindnotify/bitcoind_test.go
  contractcourt/taproot_briefcase_test.go
  lnwallet/chainfee/estimator.go
  lnwallet/chainfee/estimator_test.go
Labels: flake fix, no-itest, no-changelog

#7960 build: update to kvdb v1.4.3
  go.mod
  go.sum
  itest/lnd_channel_funding_fund_max_test.go
  itest/lnd_channel_funding_utxo_selection_test.go
  kvdb/sqlbase/sqlerrors.go
  kvdb/sqlbase/sqlerrors_no_postgres.go
  kvdb/sqlbase/sqlerrors_no_sqlite.go
  kvdb/sqlbase/sqlerrors_postgres.go
  kvdb/sqlbase/sqlerrors_sqlite.go
  lnwallet/chanfunding/coin_select_test.go
Labels: no-changelog

#7966 contractcourt: make sure we force sweep outgoing htlcs
  contractcourt/htlc_timeout_resolver.go
Labels: no-changelog

#7977 build: bump version to v0.17.0 rc3
  build/version.go
  go.mod
  go.sum
Labels: no-changelog

#7985 lnwallet+contractcourt: gracefully handle auto force close post data …
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  docs/release-notes/release-notes-0.17.0.md
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: no-changelog

#7991 lnrpc: increase max message size for ws proxy
  docs/release-notes/release-notes-0.17.0.md
  lnrpc/websocket_proxy.go
Labels: gRPC, optimization, websockets

#7983 lnd+config: add ability to obtain blocking and mutex profiles
  config.go
  docs/release-notes/release-notes-0.17.0.md
  lnd.go
  sample-lnd.conf
Labels: no-changelog

#7994 multi: add ability to specify local nonces for musig2 signer rpc, add itest for remote signer taproot chans
  docs/release-notes/release-notes-0.17.0.md
  input/musig2.go
  input/musig2_session_manager.go
  itest/lnd_payment_test.go
  itest/lnd_remote_signer_test.go
  lnrpc/signrpc/signer.pb.go
  lnrpc/signrpc/signer.proto
  lnrpc/signrpc/signer.swagger.json
  lnrpc/signrpc/signer_server.go
  lntest/mock/signer.go
  lnwallet/musig_session.go
  lnwallet/rpcwallet/rpcwallet.go
  watchtower/wtmock/signer.go
Labels: rpc, signrpc, taproot, musig2

#7981 watchtower: handle rogue updates
  docs/release-notes/release-notes-0.17.0.md
  lnrpc/wtclientrpc/wtclient.go
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtclient/queue_test.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtdb/queue_test.go
  watchtower/wtmock/client_db.go
Labels: watchtower, bug fix

#7665 lnwire: encode channel_update type in onion errors
  lnwire/onion_error.go
  lnwire/onion_error_test.go
Labels: testing, fuzzing, BOLTs, no-changelog

#7900 itest: fix itest logs upload
  Makefile
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/mempool.go
  chainntnfs/neutrinonotify/neutrino.go
  chanbackup/pubsub.go
  chanfitness/chaneventstore.go
  channelnotifier/channelnotifier.go
  contractcourt/breacharbiter.go
  contractcourt/chain_arbitrator.go
  contractcourt/utxonursery.go
  discovery/gossiper.go
  funding/manager.go
  healthcheck/healthcheck.go
  htlcswitch/hop/iterator.go
  htlcswitch/htlcnotifier.go
  htlcswitch/switch.go
  invoices/invoiceregistry.go
  netann/chan_status_manager.go
  netann/host_ann.go
  peernotifier/peernotifier.go
  routing/missioncontrol.go
  routing/router.go
  scripts/itest_parallel.sh
  server.go
  sweep/sweeper.go
Labels: itests, no-changelog

#7823 sweeper: lower the default max fee rate and make it configurable
  config.go
  docs/release-notes/release-notes-0.18.0.md
  itest/lnd_onchain_test.go
  lncfg/sweeper.go
  lnwallet/chainfee/rates.go
  lnwallet/chainfee/rates_test.go
  rpcserver.go
  sample-lnd.conf
  server.go
  sweep/defaults.go
  sweep/sweeper.go
  sweep/sweeper_test.go
  sweep/tx_input_set.go
  sweep/tx_input_set_test.go
  sweep/txgenerator.go
  sweep/txgenerator_test.go
  sweep/walletsweep.go
  sweep/walletsweep_test.go
  sweep/weight_estimator.go
  sweep/weight_estimator_test.go
Labels: fees, utxo sweeping

#8031 chanacceptor+lnrpc: add simple taproot channel support
  chanacceptor/rpcacceptor.go
  itest/lnd_channel_backup_test.go
  itest/lnd_funding_test.go
  itest/lnd_multi-hop_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  rpcserver.go
Labels: rpc, taproot chans, no-changelog

#8035 build: bump version to v0.17.0 rc5
  build/version.go
Labels: no-changelog

#7267 routing: Support Pathfinding to Blinded Routes
  channeldb/payments.go
  channeldb/payments_test.go
  cmd/lncli/cmd_payments.go
  docs/release-notes/release-notes-0.18.0.md
  htlcswitch/hop/payload.go
  htlcswitch/hop/payload_test.go
  itest/list_on_test.go
  itest/lnd_route_blinding.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_backend_test.go
  lnrpc/routerrpc/router_server.go
  record/hop.go
  routing/blinding.go
  routing/blinding_test.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_session.go
  routing/route/route.go
  routing/route/route_test.go
  routing/router.go
  routing/router_test.go
Labels: onion routing, crypto, path finding, blinded paths

#8041 peer: launch persistent peer pruning in background goroutine
  peer/brontide.go
Labels: no-changelog

#8037 lnwallet+rpcserver: fix weight calculation for taproot channels
  itest/list_on_test.go
  itest/lnd_payment_test.go
  lnwallet/channel.go
  rpcserver.go
Labels: no-changelog
