Repository lightningnetwork/lnd, pull requests merged in 2023-10, with the labels that each got.

#7998 sample-lnd.conf: fix typo
  sample-lnd.conf
Labels: no-itest, no-changelog

#7925 funding: wait for coinbase maturity before sending channel_ready
  funding/manager.go
  funding/manager_test.go
  lnwallet/chanfunding/canned_assembler.go
Labels: funding, no-changelog

#8053 lncli: fix description of connect/disconnect peer
  cmd/lncli/commands.go
Labels: lncli

#8025 Add instructions to generate type hints
  docs/grpc/python.md
Labels: python-grpc, docs, no-itest, no-changelog

#7887 funding: remove dead code and sanity check pending chan ID
  funding/manager.go
  lnwallet/test/test_interface.go
  lnwallet/wallet.go
  lnwallet/wallet_test.go
Labels: funding, no-changelog

#7889 tlv: fuzz test encoding/decoding
  tlv/fuzz_test.go
Labels: fuzzing, no-changelog

#8076 scripts: kill lnd on windows to access log files
  .github/workflows/main.yml
  scripts/itest_parallel.sh
Labels: no-changelog

#7937 htlcswitch/hop: use InvalidOnionVersion for replayed packets
  docs/release-notes/release-notes-0.17.1.md
  htlcswitch/hop/iterator.go
  itest/lnd_misc_test.go
Labels: bug fix

#8066 multi: extend `InvoiceDB` methods with a context argument
  channeldb/db.go
  channeldb/invoice_test.go
  channeldb/invoices.go
  contractcourt/channel_arbitrator.go
  contractcourt/interfaces.go
  contractcourt/mock_registry_test.go
  docs/release-notes/release-notes-0.18.0.md
  htlcswitch/interfaces.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  htlcswitch/switch_test.go
  htlcswitch/test_utils.go
  invoices/interface.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/invoicesrpc/invoices_server.go
  rpcserver.go
Labels: database, refactoring

#8083 github: print debug logs for failed unit tests
  .github/workflows/main.yml
Labels: no-itest, no-changelog

#8093 chore: pkg import only once
  lnwallet/btcwallet/btcwallet.go
Labels: no-changelog

#7824 input+sweep: make sure input with no fee rate is not added to cluster
  docs/release-notes/release-notes-0.18.0.md
  funding/batch.go
  input/mocks.go
  lncfg/wtclient.go
  lnrpc/walletrpc/walletkit_server.go
  lnrpc/wtclientrpc/wtclient.go
  lnwallet/chainfee/rates.go
  rpcserver.go
  server.go
  sweep/sweeper.go
  sweep/sweeper_test.go
Labels: fees, P1, utxo sweeping

#8092 multi: fix peer unit test and disable `paralleltest`
  .golangci.yml
  funding/manager_test.go
  input/taproot_test.go
  lnwallet/channel_test.go
  lnwallet/musig_session_test.go
  lnwallet/rebroadcaster_test.go
  peer/brontide_test.go
Labels: tests, flake fix, no-changelog

#8090 Add more information when a co-op close is failing.
  htlcswitch/link.go
  peer/brontide.go
Labels: logging, P1, no-itest, no-changelog

#7828 multi: pong enforcement
  chainntnfs/best_block_view.go
  chainntnfs/best_block_view_test.go
  chainreg/chainregistry.go
  docs/release-notes/release-notes-0.18.0.md
  peer/brontide.go
  peer/ping_manager.go
  peer/ping_manager_test.go
  server.go
Labels: p2p

#8014 build: prep for Go 1.22 by using GOEXPERIMENT=loopvar for tests
  Makefile
  discovery/chan_series.go
  discovery/syncer_test.go
  scripts/release.sh
Labels: golang/build system, tests

#8091 sweep: remove possible RBF when sweeping new inputs
  docs/release-notes/release-notes-0.18.0.md
  itest/lnd_channel_backup_test.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_multi-hop_test.go
  itest/lnd_routing_test.go
  server.go
  sweep/sweeper.go
  sweep/sweeper_test.go
Labels: utxo sweeping

#8101 chainfee: Fix test flake in `TestWebAPIFeeEstimator`
  lnwallet/chainfee/estimator.go
  lnwallet/chainfee/estimator_test.go
  lnwallet/chainfee/mocks.go
Labels: fees, flake fix, no-changelog

#8123 add release build and go report status badges
  README.md
Labels: no-itest, no-changelog

#7669 lnwire: fuzz onion failure messages
  docs/release-notes/release-notes-0.18.0.md
  lnwire/fuzz_test.go
Labels: onion routing, fuzzing

#8135 multi: fix test flakes in unit tests and itests
  invoices/invoiceregistry_test.go
  itest/lnd_multi-hop_test.go
  lntest/harness.go
Labels: flake fix, no-changelog

#8104 multi: skip InitRemoteMusigNonces if we've already called it
  docs/release-notes/release-notes-0.17.1.md
  itest/list_on_test.go
  itest/lnd_open_channel_test.go
  lntest/harness_assertion.go
  lnwallet/channel.go
  peer/brontide.go
Labels: bug fix, taproot, taproot chans

#7811 contractcourt: stop lnd when received witness is empty
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/interface.go
  chainntnfs/mempool.go
  chainntnfs/mempool_test.go
  chainntnfs/txnotifier.go
  chainntnfs/txnotifier_test.go
  contractcourt/htlc_timeout_resolver.go
  contractcourt/htlc_timeout_resolver_test.go
  docs/release-notes/release-notes-0.18.0.md
Labels: security, backend, bitcoind, P2
