Repository lightningnetwork/lnd, pull requests merged in 2023-06, with the labels that each got.

#7238 contractcourt: fully use chanPoint variable
  contractcourt/chain_arbitrator.go
Labels: no-changelog

#7742 multimutex: remove HashMutex, make Mutex type a type param
  blockcache/blockcache.go
  discovery/gossiper.go
  htlcswitch/payment_result.go
  multimutex/hash_mutex.go
  multimutex/multimutex.go
  routing/control_tower.go
  routing/router.go
Labels: no-changelog

#7752 contractcourt: improve logging for failing dangling htlcs
  contractcourt/channel_arbitrator.go
Labels: no-changelog

#7340 [4/?] - input+lnwallet: prepare input package for funding logic, add new MusigSession abstraction
  blockcache/blockcache.go
  contractcourt/breacharbiter_test.go
  discovery/gossiper.go
  htlcswitch/payment_result.go
  htlcswitch/test_utils.go
  input/musig2.go
  input/musig2_session_manager.go
  input/test_utils.go
  lntest/mock/signer.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/btcwallet/signer.go
  lnwallet/chanfunding/assembler.go
  lnwallet/chanfunding/canned_assembler.go
  lnwallet/chanfunding/psbt_assembler.go
  lnwallet/chanfunding/wallet_assembler.go
  lnwallet/musig_session.go
  lnwallet/musig_session_test.go
  lnwallet/rpcwallet/rpcwallet.go
  lnwallet/test/test_interface.go
  lnwallet/test_utils.go
  lnwallet/transactions_test.go
  multimutex/hash_mutex.go
  multimutex/multimutex.go
  peer/test_utils.go
  routing/control_tower.go
  routing/router.go
  rpcserver.go
  watchtower/wtmock/signer.go
Labels: taproot chans, no-changelog

#7687 wtclient: AddressIterator fuzz test
  docs/release-notes/release-notes-0.17.0.md
  watchtower/wtclient/fuzz_test.go
Labels: watchtower, fuzzing

#7689 Housekeeping (fix small issues, take over stale contributor PRs)
  .golangci.yml
  channeldb/invoices.go
  cmd/lncli/cmd_payments.go
  cmd/lncli/commands.go
  docker/lnd/start-lnd.sh
  docs/INSTALL.md
  docs/release-notes/release-notes-0.17.0.md
  funding/manager_test.go
  htlcswitch/failure_test.go
  htlcswitch/mock.go
  htlcswitch/testdata/long_failure_msg.json
  invoices/test_utils.go
  itest/lnd_channel_backup_test.go
  itest/lnd_channel_funding_fund_max_test.go
  itest/lnd_etcd_failover_test.go
  itest/lnd_res_handoff_test.go
  itest/lnd_routing_test.go
  itest/lnd_wipe_fwdpkgs_test.go
  lnrpc/chainrpc/chain_server.go
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/lightning_grpc.pb.go
  lnrpc/routerrpc/router_server_deprecated.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  lnrpc/watchtowerrpc/handler.go
  lntest/fee_service.go
  lntest/harness.go
  lnutils/sync_map.go
  lnwallet/mock.go
  lnwire/channel_ready.go
  lnwire/warning.go
  rpcserver.go
  sample-lnd.conf
  tls_manager.go
  tools/Dockerfile
  tools/go.mod
  tools/go.sum
  watchtower/wtclient/queue.go
  watchtower/wtdb/migration3/client_db_test.go
  watchtower/wtdb/migration4/client_db_test.go
  watchtower/wtdb/migration7/client_db_test.go
Labels: no-changelog

#7344 [5/? ] - lnwallet: add taproot funding support to the internal wallet flow (reservations)
  channeldb/channel.go
  contractcourt/chain_watcher.go
  lnwallet/channel.go
  lnwallet/commitment.go
  lnwallet/musig_session.go
  lnwallet/reservation.go
  lnwallet/revocation_producer.go
  lnwallet/revocation_producer_itest.go
  lnwallet/test/test_interface.go
  lnwallet/wallet.go
  peer/brontide.go
Labels: taproot chans, no-changelog

#7565 Fix non-deterministic behaviour for custom accounts
  cmd/lncli/walletrpc_active.go
  docs/release-notes/release-notes-0.17.0.md
  itest/lnd_wallet_import_test.go
  lntest/rpc/wallet_kit.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/btcwallet/psbt.go
Labels: wallet, bug fix, accounting

#7771 multi: add tower config defaults
  config.go
  docs/release-notes/release-notes-0.17.0.md
  lncfg/watchtower.go
  lncfg/wtclient.go
  sample-lnd.conf
  server.go
  watchtower/conf.go
Labels: config, watchtower

#7728 lnrpc+itest: return channel Memo for Pending channels
  itest/lnd_onchain_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  rpcserver.go
Labels: no-changelog

#7710 Channeldb: Store HTLC Extra TLVs in Onion Blob Varbytes
  channeldb/channel.go
  channeldb/channel_test.go
  contractcourt/briefcase_test.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_incoming_resolver_test.go
  contractcourt/htlc_outgoing_contest_resolver_test.go
  contractcourt/htlc_success_resolver_test.go
  docs/release-notes/release-notes-0.17.0.md
  lnmock/routing.go
  lnwallet/channel.go
Labels: onion routing, HTLC, tlv, blinded paths

#7763 Better temp miner management and more verbose loggings
  itest/lnd_open_channel_test.go
  itest/lnd_zero_conf_test.go
  lntest/btcd.go
  lntest/harness_miner.go
  peer/brontide.go
  server.go
Labels: logging, itests, no-changelog

#7774 lnd: add debug log when syncing blocks
  lnd.go
Labels: no-changelog

#7777 lnd: fix pprof server redirects
  lnd.go
Labels: no-changelog

#7767 Fix mempool memory usage
  docs/release-notes/release-notes-0.17.0.md
  go.mod
  go.sum
Labels: mempool, modules

#7772 scripts: update release notes check for merge queue usage
  scripts/check-release-notes.sh
Labels: no-itest, no-changelog
