Repository lightningnetwork/lnd, pull requests merged in 2023-11, with the labels that each got.

#8139 CI: upgrade bitcoind version to 0.25
  scripts/install_bitcoind.sh
Labels: no-changelog

#8138 build: create v0.17.1-rc1 branch
  build/version.go
  cmd/lncli/chainrpc_active.go
  cmd/lncli/commands.go
  cmd/lncli/neutrino_active.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  docs/release-notes/release-notes-0.17.1.md
  go.mod
  go.sum
  htlcswitch/hop/iterator.go
  htlcswitch/link.go
  itest/list_on_test.go
  itest/lnd_channel_backup_test.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_macaroons_test.go
  itest/lnd_misc_test.go
  itest/lnd_multi-hop_test.go
  itest/lnd_onchain_test.go
  itest/lnd_open_channel_test.go
  lnrpc/chainrpc/chain_server.go
  lnrpc/chainrpc/chainkit.pb.go
  lnrpc/chainrpc/chainkit.pb.gw.go
  lnrpc/chainrpc/chainkit.pb.json.go
  lnrpc/chainrpc/chainkit.proto
  lnrpc/chainrpc/chainkit.swagger.json
  lnrpc/chainrpc/chainkit.yaml
  lnrpc/chainrpc/chainkit_grpc.pb.go
  lntest/harness_assertion.go
  lntest/mock/chainio.go
  lntest/rpc/chain_kit.go
  lnwallet/btcwallet/blockchain.go
  lnwallet/channel.go
  lnwallet/interface.go
  lnwallet/mock.go
  macaroons/constraints_test.go
  macaroons/service.go
  macaroons/service_test.go
  peer/brontide.go
  routing/notifications_test.go
  sweep/sweeper.go
  sweep/tx_input_set.go
  sweep/txgenerator.go
Labels: releases

#7503 channeldb+routing: decouple payment lifecycle flow and fix stuck payments
  channeldb/mp_payment.go
  channeldb/mp_payment_test.go
  docs/release-notes/release-notes-0.18.0.md
  htlcswitch/switch.go
  itest/lnd_max_htlcs_test.go
  routing/control_tower.go
  routing/control_tower_test.go
  routing/mock_test.go
  routing/payment_lifecycle.go
  routing/payment_lifecycle_test.go
  routing/router.go
  routing/router_test.go
Labels: code health, routing, payments, refactoring

#8155 release: create v0.17.1 rc2 release branch
  .github/workflows/main.yml
  build/version.go
  go.mod
  go.sum
Labels: releases

#8158 peer: send messages in Start via writeMessage to bypass writeHandler
  docs/release-notes/release-notes-0.17.1.md
  peer/brontide.go
Labels: bug fix

#8162 build: create v0.17.1 rc3 release branch
  build/version.go
  docs/release-notes/release-notes-0.17.1.md
  peer/brontide.go
Labels: no-changelog

#8117 channeldb+refactor: remove `kvdb.Backend` from channel DB schemas
  autopilot/graph.go
  channeldb/channel_cache_test.go
  channeldb/db.go
  channeldb/graph.go
  channeldb/graph_cache.go
  channeldb/graph_cache_test.go
  channeldb/graph_test.go
  channeldb/models/cached_edge_policy.go
  channeldb/models/channel_auth_proof.go
  channeldb/models/channel_edge_info.go
  channeldb/models/channel_edge_policy.go
  discovery/chan_series.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  docs/release-notes/release-notes-0.18.0.md
  funding/manager.go
  funding/manager_test.go
  lnrpc/devrpc/dev_server.go
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/invoicesrpc/addinvoice_test.go
  lnrpc/routerrpc/router_backend.go
  netann/chan_status_manager_test.go
  netann/channel_announcement.go
  netann/channel_announcement_test.go
  netann/channel_update.go
  netann/interface.go
  peer/brontide.go
  routing/blinding.go
  routing/graph.go
  routing/heap.go
  routing/localchans/manager.go
  routing/localchans/manager_test.go
  routing/mock_graph_test.go
  routing/mock_test.go
  routing/notifications.go
  routing/notifications_test.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_lifecycle.go
  routing/payment_session.go
  routing/payment_session_source.go
  routing/payment_session_test.go
  routing/router.go
  routing/router_test.go
  routing/unified_edges.go
  routing/unified_edges_test.go
  routing/validation_barrier.go
  rpcserver.go
  server.go
Labels: channels, refactoring, kvdb

#8171 channeldb+discovery: pass correct SCID to `MarkEdgeLive`
  channeldb/error.go
  channeldb/graph.go
  channeldb/graph_test.go
  discovery/gossiper.go
  docs/release-notes/release-notes-0.18.0.md
Labels: bug fix

#8180 peer/test: fix race in TestHandleNewPendingChannel
  peer/brontide_test.go
Labels: tests, data-race, no-changelog

#8186 peer: send reestablish, shutdown messages before starting writeHandler
  peer/brontide.go
Labels: bug fix, brontide, no-changelog

#8173 tlv: simplify encoding functions
  tlv/primitive.go
  tlv/truncated.go
Labels: refactoring, tlv, no-changelog

#8201 itest: fix flake in `multi_hop_htlc_remote_chain_claim`
  itest/lnd_multi-hop_test.go
Labels: flake fix, no-changelog

#8198 peer: test for startup writeHander data race
  peer/brontide_test.go
  peer/test_utils.go
Labels: brontide, no-changelog

#8187 release: create v0.17.2-beta release branch
  build/version.go
  docs/release-notes/release-notes-0.17.2.md
  peer/brontide.go
  peer/brontide_test.go
  peer/test_utils.go
Labels: no-changelog

#8181 docs/comprehensive lncli
  .github/pull_request_template.md
  .vscode/settings.json
  cmd/lncli/commands.go
  docs/release-notes/release-notes-0.18.0.md
  lnrpc/autopilotrpc/autopilot.proto
  lnrpc/autopilotrpc/autopilot.swagger.json
  lnrpc/autopilotrpc/autopilot_grpc.pb.go
  lnrpc/devrpc/dev.proto
  lnrpc/devrpc/dev.swagger.json
  lnrpc/devrpc/dev_grpc.pb.go
  lnrpc/invoicesrpc/invoices.proto
  lnrpc/invoicesrpc/invoices.swagger.json
  lnrpc/invoicesrpc/invoices_grpc.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/lightning_grpc.pb.go
  lnrpc/neutrinorpc/neutrino.proto
  lnrpc/neutrinorpc/neutrino.swagger.json
  lnrpc/neutrinorpc/neutrino_grpc.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_grpc.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_grpc.pb.go
  lnrpc/watchtowerrpc/watchtower.proto
  lnrpc/watchtowerrpc/watchtower.swagger.json
  lnrpc/watchtowerrpc/watchtower_grpc.pb.go
  lnrpc/wtclientrpc/wtclient.proto
  lnrpc/wtclientrpc/wtclient.swagger.json
  lnrpc/wtclientrpc/wtclient_grpc.pb.go
Labels: documentation, lncli

#8224 input: fix `fatal error: concurrent map writes`
  docs/release-notes/release-notes-0.17.3.md
  input/musig2_session_manager.go
  lntest/harness.go
Labels: P1, bug fix

#8209 docs: fix typos [skip ci]
  docs/release-notes/release-notes-0.14.0.md
  docs/release-notes/release-notes-0.16.1.md
  sample-lnd.conf
Labels: no-changelog

#8222 wtclient+migration: start storing chan max height in channel details bucket
  docs/release-notes/release-notes-0.18.0.md
  watchtower/wtclient/client.go
  watchtower/wtclient/interface.go
  watchtower/wtdb/client_chan_summary.go
  watchtower/wtdb/client_db.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtdb/log.go
  watchtower/wtdb/migration8/codec.go
  watchtower/wtdb/migration8/log.go
  watchtower/wtdb/migration8/migration.go
  watchtower/wtdb/migration8/migration_test.go
  watchtower/wtdb/migration8/range_index.go
  watchtower/wtdb/queue.go
  watchtower/wtdb/queue_test.go
  watchtower/wtdb/version.go
Labels: watchtower, performance

#8220 multi: fix loopvar and enhance logging around channel reestablishment
  channeldb/channel.go
  docs/release-notes/release-notes-0.17.3.md
  htlcswitch/link.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  peer/brontide.go
Labels: logging

#8177 routerrpc: optionally return the new payment status
  docs/release-notes/release-notes-0.18.0.md
  itest/list_on_test.go
  itest/lnd_max_htlcs_test.go
  itest/lnd_trackpayments_test.go
  lnrpc/routerrpc/config.go
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lnrpc/routerrpc/router_server.go
  routing/control_tower.go
  routing/control_tower_test.go
  rpcserver.go
  sample-lnd.conf
Labels: payments, compatibility

#8151 routing: launch fetchFundingTx in goroutine so router can exit
  docs/release-notes/release-notes-0.17.3.md
  routing/router.go
Labels: bug fix, shutdown

#8232 gomod: update `btcwallet` version
  docs/release-notes/release-notes-0.17.3.md
  go.mod
  go.sum
Labels: optimization, mempool
