Repository lightningnetwork/lnd, pull requests merged in 2023-05, with the labels that each got.

#7568 Add config options for custom feature bits
  cmd/lncli/peersrpc_active.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  docs/release-notes/release-notes-0.17.0.md
  feature/manager.go
  feature/manager_internal_test.go
  feature/set.go
  funding/manager.go
  itest/list_on_test.go
  itest/lnd_channel_graph_test.go
  itest/lnd_custom_features.go
  lncfg/protocol_experimental_off.go
  lncfg/protocol_experimental_on.go
  lnrpc/peersrpc/config_active.go
  lnrpc/peersrpc/peers_server.go
  lnwire/features.go
  lnwire/features_test.go
  netann/host_ann.go
  netann/node_announcement.go
  peer/brontide.go
  rpcserver.go
  server.go
  subrpcserver_config.go
Labels: wire protocol, gossip, feature bits

#7667 [skip ci] htlcswitch: fix double sat/kw output
  htlcswitch/link.go
Labels: no-itest, no-changelog

#7678 Restore support for `PKCS8`-encoded cert private keys
  docs/release-notes/release-notes-0.17.0.md
  tls_manager.go
Labels: tls

#7486 lnrpc: update docs for invoice amt_paid
  lnrpc/invoicesrpc/invoices.swagger.json
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
Labels: no-changelog

#7688 Update docker images
  docker/btcd/Dockerfile
  docker/ltcd/Dockerfile
  lnrpc/Dockerfile
  lnrpc/gen_protos_docker.sh
Labels: no-changelog

#7707 watchtower: miscellaneous fixes
  watchtower/blob/type.go
  watchtower/wtclient/client.go
Labels: no-changelog

#7668 multi: accept memo note when opening channel
  channeldb/channel.go
  cmd/lncli/cmd_open_channel.go
  docs/release-notes/release-notes-0.17.0.md
  funding/manager.go
  itest/lnd_open_channel_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lntest/harness.go
  lnwallet/reservation.go
  lnwallet/wallet.go
  rpcserver.go
Labels: rpc, channels

#7693 lncli: Global flags to accept ENV vars overrides
  cmd/lncli/main.go
  docs/release-notes/release-notes-0.17.0.md
Labels: no-itest, no-changelog

#7720 docs: move entry for 7705 to 0.16.3
  docs/release-notes/release-notes-0.16.3.md
  docs/release-notes/release-notes-0.17.0.md
Labels: no-itest, no-changelog

#7333 [2/?] - input: add taproot chan scripts, control block logic, and spending routines
  input/script_utils.go
  input/script_utils_test.go
  input/taproot.go
  input/taproot_test.go
  input/test_utils.go
Labels: funding, taproot, taproot chans, no-changelog

#7726 contractcourt: force the sweeper to always resolve outgoing HTLCs
  contractcourt/htlc_timeout_resolver.go
  contractcourt/utxonursery.go
  docs/release-notes/release-notes-0.16.3.md
Labels: no-changelog
