Repository lightningnetwork/lnd, pull requests merged in 2023-08, with the labels that each got.

#7846 htlcswitch: split mailCourier by courierType
  htlcswitch/mailbox.go
Labels: no-changelog

#7859 chainntnfs: remove block info from conf detail copy
  chainntnfs/test/test_interface.go
  chainntnfs/txnotifier.go
Labels: no-changelog

#7875 refactor: move State server REST registration
  lnd.go
  rpcserver.go
Labels: no-changelog

#7518 Fix race between `channel_ready` and link update
  .golangci.yml
  config.go
  discovery/mock_test.go
  docs/release-notes/release-notes-0.17.0.md
  funding/manager.go
  funding/manager_test.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  itest/list_on_test.go
  itest/lnd_open_channel_test.go
  lncfg/dev.go
  lncfg/dev_integration.go
  lnpeer/mock_peer.go
  lnpeer/peer.go
  peer/brontide.go
  peer/brontide_test.go
  server.go
Labels: funding, brontide

#7870 scripts: Direct 'lnd --help' output to a file
  scripts/check-sample-lnd-conf.sh
Labels: no-itest, no-changelog

#7177 funding: fix channel type negotiation bug
  docs/release-notes/release-notes-0.17.0.md
  funding/commitment_type_negotiation.go
  funding/commitment_type_negotiation_test.go
  funding/manager.go
  funding/manager_test.go
Labels: funding, bug fix

#7880 trivial: fix loggings, variable names and conf notification order
  contractcourt/channel_arbitrator.go
  contractcourt/htlc_success_resolver.go
  input/input.go
  sweep/sweeper.go
Labels: logging, no-changelog

#7881 mod: bump neutrino dependency to v0.16.0
  go.mod
  go.sum
Labels: no-changelog

#7894 trivial: fix unit test flake for `Ping` message
  lnwire/lnwire_test.go
Labels: no-itest, no-changelog

#7472 [9/9] multi: add full on chain resolution support for simple taproot channels
  chanbackup/single.go
  chanrestore.go
  contractcourt/anchor_resolver.go
  contractcourt/breacharbiter.go
  contractcourt/breacharbiter_test.go
  contractcourt/briefcase.go
  contractcourt/briefcase_test.go
  contractcourt/chain_watcher.go
  contractcourt/channel_arbitrator.go
  contractcourt/commit_sweep_resolver.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_success_resolver.go
  contractcourt/htlc_timeout_resolver.go
  contractcourt/taproot_briefcase.go
  contractcourt/taproot_briefcase_test.go
  contractcourt/utxonursery.go
  feature/default_sets.go
  feature/deps.go
  feature/manager.go
  funding/commitment_type_negotiation.go
  funding/manager.go
  funding/manager_test.go
  htlcswitch/link.go
  input/input.go
  input/script_desc.go
  input/script_utils.go
  input/signdescriptor.go
  input/size.go
  input/size_test.go
  input/taproot_test.go
  input/witnessgen.go
  itest/lnd_channel_backup_test.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_funding_test.go
  itest/lnd_multi-hop_test.go
  itest/lnd_revocation_test.go
  lncfg/protocol.go
  lncfg/protocol_integration.go
  lntest/mock/signer.go
  lntest/utils.go
  lnutils/memory.go
  lnwallet/chancloser/chancloser.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/commitment.go
  lnwallet/reservation.go
  lnwallet/transactions.go
  lnwire/features.go
  peer/musig_chan_closer.go
  routing/router.go
  rpcserver.go
Labels: contracts, taproot, taproot chans

#7648 funding: fix flake in itest caused by persistent fee param changes
  chainreg/chainregistry.go
  channeldb/db.go
  channeldb/forwarding_policy.go
  channeldb/models/channel.go
  funding/manager.go
  funding/manager_test.go
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  htlcswitch/test_utils.go
  peer/brontide.go
  routing/localchans/manager.go
  routing/localchans/manager_test.go
  server.go
Labels: P1, no-changelog

#7907 Release notes for 0.17 updated to the new format
  docs/release-notes/release-notes-0.17.0.md
Labels: documentation, no-itest, no-changelog

#7932 psbt: fix channel funding address for simple taproot channels
  itest/list_on_test.go
  itest/lnd_psbt_test.go
  itest/lnd_remote_signer_test.go
  lntest/harness.go
  lnwallet/chanfunding/psbt_assembler.go
Labels: funding, psbt, taproot, taproot chans, no-changelog

#7936 contractcourt: fix potential panic during startup
  contractcourt/channel_arbitrator.go
Labels: no-changelog

#7938 peer: eliminate circular waiting by calling maybeSendNodeAnn async
  peer/brontide.go
Labels: no-changelog

#7927 multi: ensure link is always torn down due to db failures, add exponential back off for sql-kvdb failures
  docs/release-notes/release-notes-0.17.0.md
  htlcswitch/link.go
  htlcswitch/linkfailure.go
  kvdb/sqlbase/db.go
  kvdb/sqlbase/readwrite_tx.go
  lnwallet/channel.go
  peer/brontide.go
Labels: bug, database, safety, no-changelog
