Repository lightningnetwork/lnd, pull requests merged in 2024-12, with the labels that each got.

#9328 docker+docs: update documentation around Golang minimum version
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .golangci.yml
  Dockerfile
  dev.Dockerfile
  docker/btcd/Dockerfile
  docs/INSTALL.md
  go.mod
  lnrpc/Dockerfile
  make/builder.Dockerfile
Labels: no-itest, no-changelog

#9305 tlv: update to fn v2
  tlv/go.mod
  tlv/go.sum
  tlv/record_type.go
Labels: no-itest, no-changelog, size/nano

#9331 multi: rename `lll` to `ll` and remove unused `nolint`
  discovery/gossiper.go
  invoices/sql_store.go
  lnwire/typed_fee.go
Labels: no-itest, no-changelog, size/nano

#9324 Don't block on channel arbitator startup
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  docs/release-notes/release-notes-0.18.4.md
Labels: bug fix, init, custom chans

#9333 [custom channels]: refactor AuxTrafficManager to be used for forwarding as well
  config_builder.go
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  peer/brontide.go
  routing/bandwidth.go
  routing/bandwidth_test.go
  routing/mock_test.go
  routing/payment_lifecycle.go
  routing/payment_lifecycle_test.go
  routing/payment_session_source.go
  routing/router.go
  routing/router_test.go
  server.go
Labels: htlcswitch, refactoring, no-changelog, custom chans

#9316 routing: fix mc blinded path behaviour.
  docs/release-notes/release-notes-0.18.4.md
  docs/release-notes/release-notes-0.19.0.md
  input/script_utils.go
  routing/blinding.go
  routing/blinding_test.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/result_interpretation.go
  routing/result_interpretation_test.go
Labels: P0, blinded paths

#8512 [3/4] - lnwallet/chancloser: add new protofsm based RBF chan closer
  lnwallet/chancloser/chancloser.go
  lnwallet/chancloser/chancloser_test.go
  lnwallet/chancloser/interface.go
  lnwallet/chancloser/mock.go
  lnwallet/chancloser/rbf_coop_msg_mapper.go
  lnwallet/chancloser/rbf_coop_states.go
  lnwallet/chancloser/rbf_coop_test.go
  lnwallet/chancloser/rbf_coop_transitions.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/close_test.go
  lnwallet/commitment.go
  lnwire/closing_complete.go
  lnwire/lnwire_test.go
  peer/brontide.go
  protofsm/state_machine.go
  protofsm/state_machine_test.go
Labels: channel closing, channel management, spec, P1, rbf, no-changelog

#9335 release: create branch for v0.18.4-beta.rc2
  build/version.go
  config_builder.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  docs/release-notes/release-notes-0.18.4.md
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  input/script_utils.go
  peer/brontide.go
  routing/bandwidth.go
  routing/bandwidth_test.go
  routing/blinding.go
  routing/blinding_test.go
  routing/mock_test.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_lifecycle.go
  routing/payment_lifecycle_test.go
  routing/payment_session_source.go
  routing/result_interpretation.go
  routing/result_interpretation_test.go
  routing/router.go
  routing/router_test.go
  server.go
Labels: golang/build system, releases, no-changelog

#9341 fn: Remove ctx from GoroutineManager constructor
  docs/release-notes/release-notes-0.19.0.md
  fn/goroutine_manager.go
  fn/goroutine_manager_test.go
Labels: no-itest

#9348 github: update goveralls tool
  .github/workflows/main.yml
Labels: CI, no-itest, no-changelog, coveralls

#9276 Beat [3/4]: prepare resolvers to handle the `blockbeat`
  contractcourt/anchor_resolver.go
  contractcourt/breach_resolver.go
  contractcourt/briefcase_test.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  contractcourt/commit_sweep_resolver.go
  contractcourt/commit_sweep_resolver_test.go
  contractcourt/contract_resolver.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_incoming_contest_resolver_test.go
  contractcourt/htlc_outgoing_contest_resolver.go
  contractcourt/htlc_outgoing_contest_resolver_test.go
  contractcourt/htlc_success_resolver.go
  contractcourt/htlc_success_resolver_test.go
  contractcourt/htlc_timeout_resolver.go
  contractcourt/htlc_timeout_resolver_test.go
  contractcourt/mock_registry_test.go
  invoices/invoiceregistry.go
Labels: no-itest, no-changelog

#9309 chainntnfs: fix `TestHistoricalConfDetailsTxIndex`
  chainntnfs/bitcoindnotify/bitcoind_test.go
  chainntnfs/test/bitcoind/bitcoind_test.go
  chainntnfs/txnotifier_test.go
  go.mod
  go.sum
Labels: flake fix, no-changelog

#9343 fn: expand the ContextGuard and add tests
  fn/context_guard.go
  fn/context_guard_test.go
  fn/tests.go
Labels: no-itest

#9352 scripts: update Roasbeef's key ID in verify-install.sh
  scripts/verify-install.sh
Labels: no-itest, no-changelog

#9357 contractcourt: include custom records on replayed htlc
  contractcourt/htlc_incoming_contest_resolver.go
Labels: custom chans

#9303 htlcswitch+routing: handle nil pointer dereference properly
  htlcswitch/packet.go
  htlcswitch/switch.go
  lnwallet/channel.go
  routing/payment_lifecycle.go
Labels: bug fix, no-changelog, size/micro

#9367 release: create branch for v0.18.4-beta
  build/version.go
  contractcourt/htlc_incoming_contest_resolver.go
Labels: golang/build system, releases, no-changelog

#9374 fn: add set copy method Copy
  fn/set.go
Labels: size/micro

#9242 Reapply #8644
  .github/workflows/main.yml
  Makefile
  batch/batch.go
  batch/batch_test.go
  docs/release-notes/release-notes-0.19.0.md
  go.mod
  go.sum
  graph/db/graph.go
  itest/lnd_multi-hop-payments_test.go
  kvdb/go.mod
  kvdb/go.sum
  kvdb/postgres/db.go
  kvdb/sqlbase/db.go
  kvdb/sqlbase/readwrite_tx.go
  log.go
  sqldb/interfaces.go
  sqldb/sqlerrors.go
Labels: database, kvdb, postgres

#9381 workflows: fix no space left error
  .github/workflows/main.yml
Labels: no-changelog
