Repository lightningnetwork/lnd, pull requests merged in 2024-06, with the labels that each got.

#8802 scripts: add pgp key for suheb [skip ci]
  scripts/keys/suheb.asc
  scripts/verify-install.sh
Labels: no-itest, no-changelog

#8808 fn: add predicate combinators for && and ||
  fn/predicate.go
Labels: no-itest, no-changelog

#8816 [custom channels]: co-op closing bugfix
  lnwallet/chancloser/chancloser.go
  rpcserver.go
Labels: taproot, taproot chans, custom chans

#8823 lncli: fix parsing of --amp when sending a payment
  cmd/lncli/cmd_payments.go
  docs/release-notes/release-notes-0.18.1.md
Labels: no-itest

#8815 trivial: fix linter errors and return verbose errors
  channeldb/graph.go
  contractcourt/breach_arbitrator_test.go
  discovery/gossiper.go
  funding/manager.go
  netann/chan_status_manager.go
  peer/brontide.go
  rpcserver.go
  server.go
Labels: no-changelog

#8828 lntest: increase timeout for postgres backend
  .github/workflows/main.yml
  chainntnfs/bitcoindnotify/bitcoind_test.go
  itest/lnd_route_blinding_test.go
  lntest/wait/timeouts.go
  lntest/wait/timeouts_darwin.go
  lntest/wait/timeouts_remote_db.go
Labels: no-changelog

#8829 .github: rebase before running itests & unit tests
  .github/actions/rebase/action.yml
  .github/workflows/main.yml
Labels: no-changelog

#8841 itest: provide a temporary fix to unblock CI
  itest/lnd_channel_force_close_test.go
Labels: no-changelog

#8839 itest+lntest: let abandoned channel be either not found or in zombie
  itest/lnd_misc_test.go
  lntest/harness_assertion.go
Labels: test flake, no-changelog

#8811 lncli: fix typo in inbound fee help text
  cmd/lncli/commands.go
Labels: no-changelog

#8549 Misson Control Store: Improve performance
  docs/release-notes/release-notes-0.18.1.md
  routing/missioncontrol_store.go
  routing/missioncontrol_store_test.go
Labels: mission control

#8838 cli: update `pendingsweeps` response
  cmd/lncli/walletrpc_types.go
Labels: cli, utxo sweeping, no-changelog

#8853 fn: add additional utility methods for Result[T]
  fn/result.go
Labels: no-itest, no-changelog, fn

#8820 multi: implement+integrate new AuxSweeper sub-system to allow 3rd parties to add extra outputs to sweep transaction
  config_builder.go
  contractcourt/breach_arbitrator.go
  contractcourt/breach_arbitrator_test.go
  contractcourt/briefcase.go
  contractcourt/chain_arbitrator.go
  contractcourt/chain_watcher.go
  contractcourt/commit_sweep_resolver.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_outgoing_contest_resolver.go
  contractcourt/htlc_success_resolver.go
  contractcourt/htlc_timeout_resolver.go
  contractcourt/taproot_briefcase.go
  contractcourt/taproot_briefcase_test.go
  funding/manager.go
  go.mod
  go.sum
  input/input.go
  input/mocks.go
  lnwallet/aux_resolutions.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/interface.go
  peer/brontide.go
  server.go
  sweep/fee_bumper.go
  sweep/fee_bumper_test.go
  sweep/interface.go
  sweep/sweeper.go
  sweep/sweeper_test.go
  sweep/tx_input_set.go
  sweep/tx_input_set_test.go
  sweep/txgenerator.go
  sweep/txgenerator_test.go
Labels: no-changelog

#8791 routing: assume TLV onion feature bit
  docs/release-notes/release-notes-0.18.1.md
  routing/additional_edge.go
  routing/additional_edge_test.go
  routing/blinding_test.go
  routing/mocks.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/route/route.go
Labels: tlv

#8861 multi: hook up breach arb with new aux sweeper sub-system
  contractcourt/breach_arbitrator.go
  contractcourt/breach_arbitrator_test.go
  contractcourt/briefcase.go
  contractcourt/taproot_briefcase.go
  contractcourt/taproot_briefcase_test.go
  contractcourt/utxonursery.go
  lnwallet/aux_resolutions.go
  lnwallet/channel.go
  server.go
Labels: chain handling, no-changelog, custom chans

#8862 Fix an error string match between different `btcd` versions
  docs/release-notes/release-notes-0.18.1.md
  docs/release-notes/release-notes-0.18.2.md
  go.mod
  go.sum
Labels: bug fix, btcd

#8867 multi: add taproot chans overlay feature bit
  feature/default_sets.go
  feature/deps.go
  feature/manager.go
  funding/commitment_type_negotiation.go
  funding/manager_test.go
  lncfg/protocol.go
  lncfg/protocol_integration.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnwallet/reservation.go
  lnwallet/wallet.go
  lnwire/features.go
  rpcserver.go
  sample-lnd.conf
  server.go
Labels: custom chans

#8796 multi: allow min-depth of zero for non-zero conf channels
  docs/release-notes/release-notes-0.18.2.md
  funding/manager.go
Labels: P2, zero conf
