Repository lightningnetwork/lnd, pull requests merged in 2024-01, with the labels that each got.

#8307 lnwallet: fix logging.
  lnwallet/channel.go
Labels: no-changelog

#8095 missioncontrol: add invalid onion blinding handling for blinded paths
  docs/release-notes/release-notes-0.18.0.md
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_backend.go
  lnwire/onion_error.go
  lnwire/onion_error_test.go
  routing/result_interpretation.go
  routing/result_interpretation_test.go
Labels: routing, mission control, blinded paths

#8142 routing: Add Validation for Decoding Blinded Paths
  docs/release-notes/release-notes-0.18.0.md
  htlcswitch/hop/fuzz_test.go
  htlcswitch/hop/iterator.go
  htlcswitch/hop/iterator_test.go
  htlcswitch/hop/payload.go
  htlcswitch/hop/payload_test.go
  routing/route/route.go
  routing/route/route_test.go
  routing/router_test.go
Labels: routing, blinded paths

#8325 chore: fix typos [skip ci]
  cmd/lncli/cmd_macaroon.go
  cmd/lncli/peersrpc_active.go
  cmd/lncli/walletrpc_active.go
  kvdb/config.go
  kvdb/etcd/commit_queue.go
  kvdb/etcd/readwrite_tx.go
  kvdb/readwrite_bucket_test.go
  lntest/harness.go
  lntest/harness_node_manager.go
  sweep/sweeper_test.go
  sweep/txgenerator.go
Labels: no-changelog

#8342 docs: update Node.JS example
  docs/grpc/javascript.md
Labels: gRPC, docs, no-itest, no-changelog

#7736 watchtower+refactor: CommitmentType and JusticeKit interface
  docs/release-notes/release-notes-0.18.0.md
  watchtower/blob/commitments.go
  watchtower/blob/justice_kit.go
  watchtower/blob/justice_kit_packet.go
  watchtower/blob/justice_kit_test.go
  watchtower/blob/type.go
  watchtower/lookout/justice_descriptor.go
  watchtower/lookout/justice_descriptor_test.go
  watchtower/lookout/lookout_test.go
  watchtower/wtclient/backup_task.go
  watchtower/wtclient/backup_task_internal_test.go
  watchtower/wtdb/client_db_test.go
  watchtower/wtdb/tower_db.go
  watchtower/wtdb/tower_db_test.go
  watchtower/wtmock/tower_db.go
  watchtower/wtserver/server_test.go
Labels: code health, watchtower, P1, refactoring

#8334 tlv: various enhancements to the new RecordT type
  tlv/internal/gen/gen_tlv_types.go
  tlv/record_type.go
  tlv/record_type_test.go
  tlv/tlv_type_param.go
  tlv/tlv_types_generated.go
Labels: tlv, no-changelog

#8346 routing+routerrpc: remove redudant error check
  lnrpc/routerrpc/router_server.go
  routing/router.go
Labels: no-changelog

#8096 lnwallet: Introduce a fee buffer.
  docs/release-notes/release-notes-0.18.0.md
  htlcswitch/link.go
  htlcswitch/link_test.go
  itest/lnd_amp_test.go
  itest/lnd_multi-hop-error-propagation_test.go
  itest/lnd_send_multi_path_payment_test.go
  lntest/utils.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/transactions_test.go
  routing/pathfind.go
Labels: channels, fees, htlcswitch, P1

#8188 rpcserver+lncli: add ability to create encrypted debug information package
  cmd/lncli/cmd_debug.go
  cmd/lncli/main.go
  config.go
  config_test.go
  docs/release-notes/release-notes-0.18.0.md
  go.mod
  lnencrypt/crypto.go
  lnencrypt/crypto_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.pb.gw.go
  lnrpc/lightning.pb.json.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/lightning.yaml
  lnrpc/lightning_grpc.pb.go
  rpcserver.go
Labels: enhancement, config, privacy, cli, lncli, debugging

#8361 lntest: standby test nodes in remote signing configuration
  lntest/harness.go
Labels: no-changelog

#8376 fn: add UnsafeFromSome to Option API
  fn/option.go
Labels: no-itest, no-changelog, fn

#8233 wtclient: handle un-acked updates for exhausted sessions
  docs/release-notes/release-notes-0.18.0.md
  watchtower/wtclient/client.go
  watchtower/wtclient/client_test.go
  watchtower/wtdb/client_db.go
Labels: watchtower, bug fix

#8372 routing: deep copy any transaction we obtain from `GetBlock` call.
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/interface.go
  chainntnfs/neutrinonotify/neutrino.go
  lnwallet/test/test_interface.go
  routing/chainview/bitcoind.go
  routing/chainview/btcd.go
  routing/chainview/neutrino.go
  routing/notifications_test.go
  routing/router.go
  watchtower/lookout/lookout.go
Labels: no-changelog

#8279 sweep: use p2tr output as change weight
  sweep/tx_input_set.go
  sweep/tx_input_set_test.go
Labels: fees, bug fix, no-changelog

#8388 htlcswitch: update fuzzPayload for route blinding
  htlcswitch/hop/fuzz_test.go
Labels: onion routing, fuzzing, no-changelog

#8403 config: pass tower manager pointer in to PopulateDependencies
  subrpcserver_config.go
Labels: no-changelog

#7733 watchtower: support taproot channel commitments
  cmd/lncli/wtclient.go
  docs/release-notes/release-notes-0.18.0.md
  input/script_utils.go
  itest/lnd_revocation_test.go
  lnrpc/wtclientrpc/wtclient.go
  lnrpc/wtclientrpc/wtclient.pb.go
  lnrpc/wtclientrpc/wtclient.proto
  lnrpc/wtclientrpc/wtclient.swagger.json
  peer/brontide.go
  server.go
  watchtower/blob/commitments.go
  watchtower/blob/justice_kit.go
  watchtower/blob/justice_kit_packet.go
  watchtower/blob/justice_kit_test.go
  watchtower/blob/type.go
  watchtower/blob/type_test.go
  watchtower/lookout/justice_descriptor.go
  watchtower/lookout/justice_descriptor_test.go
  watchtower/wtclient/backup_task.go
  watchtower/wtclient/backup_task_internal_test.go
  watchtower/wtclient/client_test.go
  watchtower/wtclient/manager.go
  watchtower/wtclient/session_negotiator.go
  watchtower/wtmock/signer.go
  watchtower/wtpolicy/policy.go
  watchtower/wtpolicy/policy_test.go
  watchtower/wtwire/features.go
Labels: watchtower, P1, taproot chans

#8407 fix: fix typo "(cltv_expiry" to "(cltv_expiry)" in `channeldb/channel.go` [skip ci]
  channeldb/channel.go
Labels: inline documentation

#8413 docs: add template for 0.17.4
  docs/release-notes/release-notes-0.17.4.md
Labels: no-itest, no-changelog

#8411 Makefile: add `make help` command that describes goals
  Makefile
Labels: documentation, docs, inline documentation, no-itest, no-changelog

#8406 Fix case where Opening Channels get stuck forever.
  docs/release-notes/release-notes-0.17.4.md
  itest/list_on_test.go
  itest/lnd_psbt_test.go
  lncfg/config.go
  lncfg/dev.go
  lncfg/dev_integration.go
  lntest/harness_assertion.go
  peer/brontide.go
  peer/brontide_test.go
  server.go
Labels: bug, channel management

#8385 peer: make PingManager disconnect call async
  docs/release-notes/release-notes-0.17.4.md
  peer/brontide.go
  peer/ping_manager.go
Labels: p2p, bug fix, llm-review

#8401 gomod: fix `btcd` mempool leak fix and `GetBlock` heap escape
  blockcache/blockcache.go
  chainreg/no_chain_backend.go
  docs/release-notes/release-notes-0.17.4.md
  go.mod
  go.sum
Labels: bug fix

#8336 fn: add some new goodies to sub-module to be used in future PRs
  fn/conc_queue.go
  fn/either.go
  fn/events.go
  fn/func.go
  fn/go.mod
  fn/go.sum
  fn/option.go
  fn/queue.go
  fn/recv.go
  fn/send.go
  fn/set.go
Labels: no-changelog

#8419 kvdb: embedded postgres upgrade to allow setting a custom `max_connections` config value
  docs/release-notes/release-notes-0.18.0.md
  kvdb/go.mod
  kvdb/go.sum
  kvdb/postgres/fixture.go
Labels: database, kvdb

#8421 lnwallet: remove redundant unused fields
  lnwallet/channel.go
Labels: code health, beginner, needs review, refactoring, no-changelog, llm-review

#8420 contractcourt: rename files for package consistency
  contractcourt/contract_resolver.go
  contractcourt/htlc_incoming_contest_resolver_test.go
Labels: code health, beginner, needs review, refactoring, no-itest, no-changelog, llm-review

#8345 lnwallet: perform mempool acceptance check before publishing
  contractcourt/chain_arbitrator.go
  docs/release-notes/release-notes-0.18.0.md
  go.mod
  go.sum
  lnutils/errors.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/test/test_interface.go
Labels: wallet, mempool

#8438 routerrpc: make use of fee limit obvious in SendPaymentV2
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
  lnrpc/routerrpc/router_grpc.pb.go
Labels: no-itest, no-changelog

#8426 Expose closing tx in waiting_close_channels
  cmd/lncli/commands.go
  docs/release-notes/release-notes-0.18.0.md
  itest/lnd_channel_force_close_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.pb.gw.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lntest/rpc/lnd.go
  rpcserver.go
Labels: enhancement, rpc

#8416 release: create v0.17.4 rc1 release branch
  blockcache/blockcache.go
  build/version.go
  chainreg/no_chain_backend.go
  docs/release-notes/release-notes-0.17.4.md
  go.mod
  go.sum
  itest/list_on_test.go
  itest/lnd_psbt_test.go
  lncfg/config.go
  lncfg/dev.go
  lncfg/dev_integration.go
  lntest/harness_assertion.go
  peer/brontide.go
  peer/brontide_test.go
  server.go
  tls_manager.go
Labels: releases, no-changelog

#8442 peer: fix issue where we echo remote Shutdown
  peer/brontide.go
  peer/brontide_test.go
Labels: bug, no-changelog
