Repository lightningnetwork/lnd, pull requests merged in 2024-05, with the labels that each got.

#8712 invoices: if there are no invoices make gc noop
  channeldb/invoices.go
  invoices/invoices_test.go
Labels: bug, invoices, no-changelog

#8716 sweep: make `TxPublisher.currentHeight` atomic
  sweep/fee_bumper.go
Labels: no-changelog

#8703 itest/flake: add more comprehensive assertions before HTLC cleared check
  itest/lnd_route_blinding_test.go
Labels: itests, flake fix, no-changelog

#8731 cli: add `--amp` to `SendPaymentRequest` in `payinvoice`
  cmd/lncli/cmd_payments.go
Labels: no-itest, no-changelog

#8719 Merge fee cache and fix sample conf
  chainreg/chainregistry.go
  config.go
  config_builder.go
  docs/release-notes/release-notes-0.18.0.md
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/test_utils.go
  lncfg/fee.go
  lncfg/neutrino.go
  lntest/fee_service.go
  lntest/node/config.go
  lnwallet/chainfee/estimator.go
  lnwallet/chainfee/estimator_test.go
  peer/brontide.go
  sample-lnd.conf
Labels: no-changelog

#8732 invoices: ensure synchronous access to NewTestSqliteDB
  invoices/invoiceregistry_test.go
  invoices/invoices_test.go
Labels: no-changelog

#7364 Add test coverage for integration tests
  .github/workflows/main.yml
  .gitignore
  Makefile
  make/testing_flags.mk
  scripts/itest_part.sh
Labels: code health, itests, no-changelog

#8733 build: bump version to v0.18.0-beta.rc2
  build/version.go
Labels: no-changelog

#8746 build: update release builds and CI to Go 1.22.3
  .github/workflows/main.yml
  .github/workflows/release.yaml
  Dockerfile
  dev.Dockerfile
  make/builder.Dockerfile
Labels: no-changelog

#8765 routing: log edge when skipping it
  routing/unified_edges.go
Labels: no-changelog

#8744 cfg: move experimental options to main protocol cfg
  config.go
  docs/release-notes/release-notes-0.18.0.md
  lncfg/protocol.go
  lncfg/protocol_experimental_off.go
  lncfg/protocol_experimental_on.go
  lncfg/protocol_integration.go
  sample-lnd.conf
  server.go
Labels: config

#8751 contractcourt+sweep: fix fee function and deadline issue
  chainntnfs/txnotifier.go
  cmd/lncli/walletrpc_active.go
  contractcourt/chain_arbitrator.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  itest/list_on_test.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_multi-hop_test.go
  itest/lnd_sweep_test.go
  sweep/README.md
  sweep/fee_bumper.go
  sweep/fee_function.go
  sweep/fee_function_test.go
  sweep/sweeper.go
  sweep/sweeper_test.go
  sweep/tx_input_set.go
Labels: utxo sweeping, no-changelog

#8631 [code-health]: reduce duplication in brontide test.
  peer/brontide_test.go
  peer/test_utils.go
Labels: no-changelog

#8762 Adjust ping parameters to improve tor stability
  peer/brontide.go
  peer/ping_manager.go
  peer/ping_manager_test.go
Labels: no-changelog

#8773 build: bump verison to v0.18.0-beta.rc3
  build/version.go
Labels: no-changelog

#8758 multi: Inbound fees are retained when not provided
  cmd/lncli/commands.go
  itest/lnd_channel_policy_test.go
  itest/lnd_multi-hop-payments_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lntest/node/watcher.go
  routing/localchans/manager.go
  routing/router.go
  rpcserver.go
Labels: no-changelog

#8622 [3/5]: multi: add new AuxFundingController for custom external funding flows
  channeldb/models/channel_edge_info.go
  config_builder.go
  discovery/gossiper.go
  funding/aux_funding.go
  funding/manager.go
  itest/lnd_psbt_test.go
  lnwallet/chanfunding/canned_assembler.go
  lnwallet/chanfunding/psbt_assembler.go
  lnwallet/reservation.go
  lnwallet/test/test_interface.go
  lnwallet/wallet.go
  log.go
  peer/brontide.go
  protofsm/log.go
  protofsm/msg_router.go
  protofsm/msg_router_test.go
  routing/router.go
  server.go
Labels: funding, custom chans

#8632 [4/5]: lnwallet: add new AuxSigner interface to mirror SigPool
  chainreg/chainregistry.go
  config_builder.go
  contractcourt/chain_arbitrator.go
  funding/manager.go
  htlcswitch/link.go
  lnwallet/aux_signer.go
  lnwallet/channel.go
  lnwallet/commitment.go
  lnwallet/config.go
  lnwallet/sigpool.go
  lnwallet/wallet.go
  peer/brontide.go
  server.go
Labels: custom chans

#8774 lnwallet+sweep: fix wrong unit used in fee calculation
  contractcourt/breach_arbitrator.go
  htlcswitch/link_test.go
  input/input.go
  input/mocks.go
  input/size.go
  input/size_test.go
  input/witnessgen.go
  itest/lnd_channel_funding_fund_max_test.go
  itest/lnd_recovery_test.go
  itest/lnd_sweep_test.go
  itest/lnd_taproot_test.go
  lnrpc/walletrpc/walletkit_server.go
  lnrpc/walletrpc/walletkit_server_test.go
  lntest/harness.go
  lntest/utils.go
  lntypes/txsize.go
  lntypes/txsize_test.go
  lnwallet/chainfee/rates.go
  lnwallet/chancloser/chancloser.go
  lnwallet/chanfunding/coin_select.go
  lnwallet/chanfunding/coin_select_test.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/commitment.go
  lnwallet/reservation.go
  lnwallet/test_utils.go
  lnwallet/transactions_test.go
  sweep/aggregator.go
  sweep/aggregator_test.go
  sweep/fee_bumper.go
  sweep/tx_input_set.go
  sweep/weight_estimator.go
  sweep/weight_estimator_test.go
  watchtower/blob/commitments.go
  watchtower/lookout/justice_descriptor.go
  watchtower/lookout/justice_descriptor_test.go
  watchtower/wtclient/backup_task.go
  watchtower/wtpolicy/policy.go
Labels: no-changelog

#8771 [6/5]: invoice+rpc: add exit hop InvoiceAcceptor sub-systems and RPC calls
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/interfaces.go
  contractcourt/mock_registry_test.go
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/mock.go
  invoices/interface.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/invoices.go
  invoices/settlement_interceptor.go
  invoices/test_utils_test.go
  invoices/update.go
  invoices/update_invoice_test.go
  itest/list_on_test.go
  itest/lnd_invoice_acceptor_test.go
  lnd.go
  lnrpc/invoicesrpc/config_active.go
  lnrpc/invoicesrpc/htlc_modifier.go
  lnrpc/invoicesrpc/invoices.pb.go
  lnrpc/invoicesrpc/invoices.pb.gw.go
  lnrpc/invoicesrpc/invoices.proto
  lnrpc/invoicesrpc/invoices.swagger.json
  lnrpc/invoicesrpc/invoices.yaml
  lnrpc/invoicesrpc/invoices_grpc.pb.go
  lnrpc/invoicesrpc/invoices_server.go
  lnrpc/invoicesrpc/utils.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/routerrpc/router_server.go
  lntest/harness.go
  lntest/rpc/invoices.go
  lntest/rpc/router.go
  routing/bandwidth.go
  routing/payment_lifecycle.go
  routing/payment_session.go
  routing/payment_session_source.go
  rpcserver.go
  server.go
  subrpcserver_config.go
Labels: taproot, taproot chans, custom chans

#8789 fn: add Result type
  fn/result.go
Labels: no-itest

#8784 build: bump version to v0.18.0-beta.rc4
  build/version.go
Labels: releases, no-changelog

#8788 scripts: add gpg key for proofofkeags [skip ci]
  scripts/keys/proofofkeags.asc
  scripts/verify-install.sh
Labels: no-itest, no-changelog

#8794 build: bump version to v0.18.0 beta
  build/version.go
Labels: releases

#8799 docs: add release notes template for 0.18.1
  docs/release-notes/release-notes-0.18.1.md
Labels: no-itest, no-changelog

#8798 chore: fix some comments
  funding/manager.go
  lnwallet/wallet.go
Labels: no-changelog
