Repository lightningnetwork/lnd, pull requests merged in 2024-04, with the labels that each got.

#8515 coin select: add coin selection strategy option to all on-chain RPCs
  cmd/lncli/cmd_open_channel.go
  cmd/lncli/commands.go
  cmd/lncli/main.go
  cmd/lncli/walletrpc_active.go
  docs/release-notes/release-notes-0.18.0.md
  funding/batch.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/marshall_utils.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  lnrpc/walletrpc/walletkit_server_test.go
  lntest/mock/walletcontroller.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/btcwallet/psbt.go
  lnwallet/interface.go
  lnwallet/mock.go
  lnwallet/rpcwallet/rpcwallet.go
  lnwallet/test/test_interface.go
  rpcserver.go
Labels: rpc, cli, lncli, chain handling, psbt, coin selection

#8160 [2/3]: Support Forwarding of Blinded Payments
  config.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_incoming_contest_resolver_test.go
  contractcourt/interfaces.go
  docs/release-notes/release-notes-0.18.0.md
  htlcswitch/hop/forwarding_info.go
  htlcswitch/hop/fuzz_test.go
  htlcswitch/hop/iterator.go
  htlcswitch/hop/iterator_test.go
  htlcswitch/hop/payload.go
  htlcswitch/hop/payload_test.go
  htlcswitch/link.go
  itest/list_on_test.go
  itest/lnd_route_blinding.go
  itest/lnd_route_blinding_test.go
  lncfg/protocol.go
  lncfg/protocol_integration.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwire/update_add_htlc.go
  peer/brontide.go
  sample-lnd.conf
  server.go
Labels: blinded paths

#8615 Revert "feature: make gossip queries compulsory"
  docs/release-notes/release-notes-0.18.0.md
  feature/default_sets.go
  feature/manager_internal_test.go
  peer/brontide_test.go
Labels: gossip

#8603 sqldb+invoices: turn sqldb into a go module
  .github/workflows/main.yml
  config_builder.go
  docs/release-notes/release-notes-0.18.0.md
  go.mod
  go.sum
  invoices/invoiceregistry_test.go
  invoices/invoices_test.go
  invoices/sql_store.go
  sqldb/go.mod
  sqldb/go.sum
  sqldb/sqlutils.go
Labels: database

#8642 kvdb: bump to sqldb/v1.0.1
  go.mod
  go.sum
  kvdb/go.mod
  kvdb/go.sum
Labels: no-itest, no-changelog

#8643 build: bump top level module to kvdb v1.4.6
  go.mod
  go.sum
Labels: golang/build system, no-changelog

#8573 GitHub: use bitcoind v27.0 for CI
  .github/workflows/main.yml
  docs/release-notes/release-notes-0.18.0.md
  go.mod
  go.sum
  scripts/install_bitcoind.sh
Labels: back port candidate

#8661 tlv: add axiomatic RecordProducer implementation for Record
  tlv/record.go
Labels: no-changelog

#8627 lnrpc: rejects positive inbound fees by default
  cmd/lncli/commands.go
  config.go
  docs/release-notes/release-notes-0.18.0.md
  rpcserver.go
  sample-lnd.conf
Labels: config, inbound fee

#8664 release: create v0.17.5 release branch
  .github/workflows/main.yml
  build/version.go
  chainntnfs/test_utils.go
  docs/release-notes/release-notes-0.17.5.md
  go.mod
  go.sum
  lnwallet/test/test_interface.go
  routing/chainview/interface_test.go
  scripts/install_bitcoind.sh
Labels: bitcoind, bug fix, releases

#8678 Add hieblmi to verify install script
  scripts/verify-install.sh
Labels: no-itest, no-changelog

#8545 dont use sweeper unconfirmed utxos
  docs/release-notes/release-notes-0.18.0.md
  funding/manager.go
  funding/manager_test.go
  go.mod
  go.sum
  itest/list_on_test.go
  itest/lnd_channel_funding_utxo_selection_test.go
  itest/lnd_funding_test.go
  itest/lnd_psbt_test.go
  lnrpc/walletrpc/walletkit_server.go
  lntest/harness.go
  lntest/mock/walletcontroller.go
  lntest/rpc/wallet_kit.go
  lnwallet/btcwallet/psbt.go
  lnwallet/chanfunding/wallet_assembler.go
  lnwallet/interface.go
  lnwallet/mock.go
  lnwallet/test/test_interface.go
  lnwallet/wallet.go
  rpcserver.go
  server.go
  sweep/sweeper.go
Labels: funding, utxo sweeping

#8590 lntest: add test node name to tmp directory name
  lntest/node/harness_node.go
Labels: no-changelog

#8685 fix lncli bumpfee flag parsing
  cmd/lncli/walletrpc_active.go
  docs/release-notes/release-notes-0.18.0.md
Labels: lncli, bug fix

#8621 fix sync neutrino nodes
  docs/release-notes/release-notes-0.18.0.md
  go.mod
  go.sum
  itest/lnd_psbt_test.go
Labels: neutrino, bug fix

#8681 lnrpc: ensure parsing of the Amp flag for payments is consistent
  docs/release-notes/release-notes-0.18.0.md
  itest/lnd_amp_test.go
  lnrpc/routerrpc/router_backend.go
  lntest/harness.go
Labels: bug fix, amp, api

#8485 [3/3]: Blinded Route Error Handling
  config.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_incoming_contest_resolver_test.go
  docs/release-notes/release-notes-0.18.0.md
  feature/default_sets.go
  feature/deps.go
  feature/manager.go
  htlcswitch/circuit.go
  htlcswitch/hop/error_encryptor.go
  htlcswitch/hop/fuzz_test.go
  htlcswitch/hop/iterator.go
  htlcswitch/hop/iterator_test.go
  htlcswitch/hop/payload.go
  htlcswitch/hop/payload_test.go
  htlcswitch/link.go
  htlcswitch/mailbox.go
  htlcswitch/mock.go
  htlcswitch/switch.go
  itest/list_on_test.go
  itest/lnd_route_blinding_test.go
  lncfg/protocol.go
  lncfg/protocol_integration.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/peersrpc/peers.swagger.json
  lnrpc/routerrpc/router.swagger.json
  lnwire/features.go
  server.go
Labels: routing, blinded paths

#8694 channeldb: fix race in TestPackager by removing global test var
  channeldb/forwarding_package_test.go
Labels: bug fix, no-changelog

#8696 sqldb+kvdb: update to sqlite v1.29.8
  kvdb/go.mod
  kvdb/go.sum
  sqldb/go.mod
  sqldb/go.sum
Labels: dependencies, no-changelog, sqlite

#8692 tlv: add new types and functions
  tlv/go.mod
  tlv/go.sum
  tlv/record.go
  tlv/record_type.go
Labels: tlv, no-itest, no-changelog

#8699 build: update to sqldb v1.0.2
  go.mod
  go.sum
  kvdb/go.mod
  kvdb/go.sum
Labels: no-changelog

#8700 build: update to kvdb v1.4.8
  go.mod
  go.sum
Labels: golang/build system, dependencies, no-changelog

#8695 make: add cache directory for linter
  Makefile
Labels: no-itest, no-changelog

#8706 0.18: add contributors from git log, polish release notes
  docs/release-notes/release-notes-0.18.0.md
Labels: docs, no-itest, no-changelog

#8705 lnrpc: fix typo
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_grpc.pb.go
Labels: no-itest, no-changelog

#8683 [1/?]: multi: add ability to fund+use musig2 channels that commit to a tapscript root
  channeldb/channel.go
  channeldb/channel_test.go
  contractcourt/chain_watcher.go
  funding/manager.go
  input/script_utils.go
  lnwallet/chancloser/chancloser_test.go
  lnwallet/chanfunding/canned_assembler.go
  lnwallet/chanfunding/interface.go
  lnwallet/chanfunding/psbt_assembler.go
  lnwallet/chanfunding/wallet_assembler.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwallet/musig_session.go
  lnwallet/reservation.go
  lnwallet/test_utils.go
  lnwallet/wallet.go
  peer/musig_chan_closer.go
  routing/router.go
Labels: taproot, musig2, taproot chans
