Repository lightningnetwork/lnd, pull requests merged in 2024-11, with the labels that each got.

#9221 htlcswitch: fix flake in `TestChannelLinkCancelFullCommitment`
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/switch_test.go
  htlcswitch/test_utils.go
Labels: flake fix, no-itest, no-changelog, size/micro

#9215 routerrpc/trivial: add docs to forward interceptor
  lnrpc/routerrpc/router.pb.go
  lnrpc/routerrpc/router.proto
  lnrpc/routerrpc/router.swagger.json
Labels: no-changelog, size/micro

#9167 routing+migration32: update migration 32 to use pure TLV encoding for mission control results
  channeldb/migration/lnwire21/msat.go
  channeldb/migration/lnwire21/true_boolean.go
  channeldb/migration32/migration_test.go
  channeldb/migration32/mission_control_store.go
  channeldb/migration32/route.go
  docs/release-notes/release-notes-0.19.0.md
  lnwire/channel_update_2.go
  routing/missioncontrol.go
  routing/missioncontrol_store.go
  routing/missioncontrol_store_test.go
  routing/result_interpretation.go
  routing/result_interpretation_test.go
  routing/route/route.go
Labels: blinded paths

#8985 fn: more fn goodies
  fn/either.go
  fn/either_test.go
  fn/fn.go
  fn/list_test.go
  fn/option.go
  fn/option_test.go
  fn/result.go
  fn/result_test.go
  fn/slice.go
  fn/slice_test.go
Labels: breaking, P1, no-changelog, fn

#7762 lnrpc: return meaningful response instead of empty one
  chanbackup/recover.go
  chanbackup/recover_test.go
  channeldb/payment_control_test.go
  channeldb/payments.go
  cmd/commands/cmd_custom.go
  cmd/commands/cmd_payments.go
  cmd/commands/commands.go
  docs/release-notes/release-notes-0.19.0.md
  itest/lnd_channel_backup_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  rpcserver.go
  server.go
Labels: rpc, P2

#9068 Cancel back outgoing dust htlcs before commitment is confirmed.
  contractcourt/briefcase.go
  contractcourt/briefcase_test.go
  contractcourt/chain_watcher.go
  contractcourt/channel_arbitrator.go
  contractcourt/channel_arbitrator_test.go
  contractcourt/htlc_timeout_resolver.go
  docs/release-notes/release-notes-0.19.0.md
  htlcswitch/switch.go
  itest/lnd_multi-hop_test.go
Labels: HTLC, force closes, size/kilo

#9182 Deprecate dust-threshold config value
  config.go
  docs/release-notes/release-notes-0.19.0.md
  htlcswitch/link.go
  htlcswitch/switch_test.go
  itest/lnd_payment_test.go
  lntest/harness.go
  sample-lnd.conf
  scripts/check-sample-lnd-conf.sh
Labels: config, size/nano

#9259 trivial: prepare itest for `blockbeat`
  itest/lnd_channel_backup_test.go
  itest/lnd_channel_policy_test.go
  itest/lnd_coop_close_with_htlcs_test.go
  itest/lnd_forward_interceptor_test.go
  itest/lnd_funding_test.go
  itest/lnd_hold_persistence_test.go
  itest/lnd_invoice_acceptor_test.go
  itest/lnd_misc_test.go
  itest/lnd_mpp_test.go
  itest/lnd_multi-hop-error-propagation_test.go
  itest/lnd_multi-hop_test.go
  itest/lnd_open_channel_test.go
  itest/lnd_payment_test.go
  itest/lnd_psbt_test.go
  itest/lnd_res_handoff_test.go
  itest/lnd_revocation_test.go
  itest/lnd_route_blinding_test.go
  itest/lnd_routing_test.go
  itest/lnd_rpc_middleware_interceptor_test.go
  itest/lnd_switch_test.go
  itest/lnd_wallet_import_test.go
  itest/lnd_watchtower_test.go
  itest/lnd_wipe_fwdpkgs_test.go
  itest/lnd_zero_conf_test.go
  lntest/harness.go
  lntest/harness_assertion.go
  lntest/harness_node_manager.go
  lntest/node/config.go
  lntest/node/harness_node.go
Labels: flake fix

#9251 lnwire: add new fuzz targets
  lnwire/fuzz_test.go
Labels: wire protocol, fuzzing, no-itest, no-changelog

#9194 multi: generate and pass along HTLC resolution blobs for aux channels
  contractcourt/breach_arbitrator.go
  contractcourt/briefcase.go
  contractcourt/chain_watcher.go
  contractcourt/htlc_incoming_contest_resolver.go
  contractcourt/htlc_lease_resolver.go
  contractcourt/htlc_outgoing_contest_resolver.go
  contractcourt/htlc_success_resolver.go
  contractcourt/htlc_timeout_resolver.go
  contractcourt/taproot_briefcase.go
  contractcourt/taproot_briefcase_test.go
  contractcourt/testdata/rapid/TestHtlcAuxBlobEncodeDecode/TestHtlcAuxBlobEncodeDecode-20240902140253-81338.fail
  docs/release-notes/release-notes-0.18.4.md
  docs/release-notes/release-notes-0.19.0.md
  go.mod
  go.sum
  input/input.go
  input/mocks.go
  lnwallet/aux_leaf_store.go
  lnwallet/aux_resolutions.go
  lnwallet/channel.go
  lnwallet/commitment.go
  lnwallet/mock.go
  macaroons/fuzz_test.go
  sweep/fee_bumper.go
  sweep/interface.go
  sweep/mock_test.go
  sweep/tx_input_set.go
Labels: chain handling, custom chans

#9273 lntest: print node PID when launching in itests
  lntest/node/harness_node.go
Labels: no-changelog

#9275 peer+lnd: fix peer blocking on node shutdown
  docs/release-notes/release-notes-0.19.0.md
  peer/brontide.go
  server.go
Labels: bug fix, size/micro

#9279 misc: nil checks and remove deprecated default values
  config.go
  lntest/harness_assertion.go
  lntest/node/state.go
Labels: no-changelog

#9272 sweep: update storeRecord to include utxo index
  sweep/fee_bumper.go
  sweep/fee_bumper_test.go
Labels: no-changelog

#9271 wtwire: simply fuzz targets
  watchtower/wtwire/fuzz_test.go
Labels: refactoring, fuzzing, no-itest, no-changelog

#9281 wtdb: export versions of wtclient.db
  watchtower/wtdb/version.go
Labels: migration, kvdb, no-itest, no-changelog

#8337 [1/4] - protofsm: add new package for driving generic protocol FSMs
  protofsm/daemon_events.go
  protofsm/log.go
  protofsm/msg_mapper.go
  protofsm/state_machine.go
  protofsm/state_machine_test.go
Labels: spec, P1, no-changelog, protocol, fsm

#9258 chainntnfs: fix missing notifications
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/interface.go
  chainntnfs/neutrinonotify/neutrino.go
  chainntnfs/txnotifier.go
  docs/release-notes/release-notes-0.19.0.md
Labels: notifications, bug fix, flake fix, size/micro

#9284 fn: update go.mod to v2
  fn/go.mod
Labels: no-itest, no-changelog

#9292 lnd: stop `graphBuilder` during shutdown
  server.go
Labels: bug fix, no-changelog, size/micro

#9291 lnwallet: log the amounts in the same unit
  lnwallet/channel.go
  lnwallet/channel_test.go
Labels: no-changelog, size/micro

#8805 localchans: recreate missing edge if not found
  channeldb/graph.go
  cmd/commands/commands.go
  docs/release-notes/release-notes-0.18.4.md
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  log.go
  routing/localchans/log.go
  routing/localchans/manager.go
  routing/localchans/manager_test.go
  rpcserver.go
  server.go
Labels: graph, P2

#9301 multi: fix some function names in interface comment
  input/input.go
  input/mocks.go
  sweep/walletsweep.go
  watchtower/wtwire/message.go
Labels: no-itest, no-changelog

#8270 DynComms [1/n]: Implement Quiescence Protocol
  docs/release-notes/release-notes-0.19.0.md
  feature/default_sets.go
  feature/manager.go
  go.mod
  go.sum
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/linkfailure.go
  htlcswitch/mock.go
  htlcswitch/quiescer.go
  htlcswitch/quiescer_test.go
  itest/list_on_test.go
  itest/lnd_quiescence_test.go
  lncfg/protocol.go
  lncfg/protocol_integration.go
  lnrpc/devrpc/config_active.go
  lnrpc/devrpc/dev.pb.go
  lnrpc/devrpc/dev.pb.gw.go
  lnrpc/devrpc/dev.pb.json.go
  lnrpc/devrpc/dev.proto
  lnrpc/devrpc/dev.swagger.json
  lnrpc/devrpc/dev.yaml
  lnrpc/devrpc/dev_grpc.pb.go
  lnrpc/devrpc/dev_server.go
  lntest/rpc/harness_rpc.go
  lntest/rpc/lnd.go
  lnwire/features.go
  lnwire/message.go
  peer/brontide.go
  peer/test_utils.go
  server.go
  subrpcserver_config.go
Labels: P1, dynamic commitments

#9295 go.mod: bump btclog dep
  build/config.go
  build/handler_sets.go
  build/prefix_log.go
  contractcourt/contract_resolver.go
  go.mod
  go.sum
  htlcswitch/link.go
  htlcswitch/quiescer.go
  lnwallet/channel.go
  peer/brontide.go
  routing/missioncontrol.go
  routing/payment_session.go
  watchtower/wtclient/client.go
Labels: no-changelog

#9311 protofsm: fix race in state machine executor tests
  protofsm/state_machine_test.go
Labels: bug fix, no-changelog, protofsm
