Repository lightningnetwork/lnd, pull requests merged in 2025-01, with the labels that each got.

#9411 .github: bump upload-artifact action to v4
  .github/workflows/main.yml
Labels: no-changelog

#9404 chore: fix some typos
  docs/debugging_lnd.md
  docs/signing_release_candidate.md
Labels: no-itest, no-changelog

#9388 Fix some typos
  build/sub_logger.go
  chainio/consumer_test.go
  chainio/dispatcher_test.go
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  channeldb/revocation_log_test.go
  contractcourt/breach_arbitrator.go
  contractcourt/htlc_timeout_resolver.go
  discovery/gossiper_test.go
  docs/code_contribution_guidelines.md
  itest/lnd_switch_test.go
Labels: no-changelog

#9361 fn: optimize context guard
  fn/context_guard.go
  fn/context_guard_test.go
Labels: no-itest

#9344 htlcswitch+go.mod: use updated fn.ContextGuard
  go.mod
  go.sum
  htlcswitch/link.go
  htlcswitch/link_test.go
  htlcswitch/test_utils.go
  protofsm/state_machine.go
  protofsm/state_machine_test.go
Labels: no-changelog

#9378 chainntnfs: fix test `testSingleConfirmationNotification`
  chainntnfs/test/test_interface.go
Labels: no-itest, no-changelog, size/micro

#9355 contractcourt: add rapid derived fuzz test for HtlcAuxBlob
  contractcourt/taproot_briefcase_test.go
Labels: testing, fuzzing, rapid

#9274 The sweeper subsystem uses now also the configured budget values for HTLCs
  contractcourt/htlc_timeout_resolver.go
  docs/release-notes/release-notes-0.19.0.md
  itest/lnd_sweep_test.go
Labels: utxo sweeping

#9383 bugfix createmissingedge
  routing/localchans/manager.go
Labels: no-changelog

#9425 itest: fix flake in `testSweepHTLCs`
  itest/lnd_sweep_test.go
Labels: flake fix, no-changelog, size/nano

#9429 .github: update actions versions
  .github/actions/setup-go/action.yml
  .github/workflows/main.yml
  .github/workflows/release.yaml
Labels: no-changelog, size/nano

#9424 multi: fix inconsistent state in gossip syncer
  discovery/gossiper.go
  discovery/sync_manager.go
  discovery/sync_manager_test.go
  discovery/syncer.go
  docs/release-notes/release-notes-0.19.0.md
  graph/builder.go
  graph/db/graph.go
  graph/db/graph_cache.go
  graph/db/models/channel_edge_policy.go
  routing/unified_edges.go
Labels: bug fix, gossip, size/micro

#9232 chanbackup: archive old channel backup files
  chanbackup/backupfile.go
  chanbackup/backupfile_test.go
  config.go
  docs/release-notes/release-notes-0.19.0.md
  sample-lnd.conf
  server.go
Labels: enhancement, SCB, size/kilo

#9241 discovery+graph: track job set dependencies in vb
  discovery/gossiper.go
  discovery/validation_barrier.go
  discovery/validation_barrier_test.go
  docs/release-notes/release-notes-0.19.0.md
  graph/builder.go
  graph/errors.go
  graph/validation_barrier.go
  graph/validation_barrier_test.go
Labels: graph, refactoring

#9442 misc: fix incorrect inclusion of nil err in various formatted strings
  lnrpc/routerrpc/router_server.go
  lntest/harness_assertion.go
Labels: logging, no-changelog

#9445 itest: fix flake in `testAnchorThirdPartySpend`
  itest/list_exclude_test.go
  itest/list_on_test.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_onchain_test.go
Labels: itests, flake fix, no-changelog, size/nano

#9454 Add Custom Error msg and Prioritise replayed HTLCs
  docs/release-notes/release-notes-0.18.5.md
  htlcswitch/interfaces.go
  htlcswitch/link.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/invoices.go
  invoices/mock.go
  invoices/modification_interceptor.go
  invoices/resolution_result.go
  invoices/test_utils_test.go
  invoices/update.go
  itest/list_on_test.go
  itest/lnd_forward_interceptor_test.go
  itest/lnd_invoice_acceptor_test.go
  lnrpc/invoicesrpc/utils.go
  routing/bandwidth_test.go
Labels: testing, amp, custom chans, size/kilo

#9456 lnrpc+docs: deprecate warning `SendToRoute`, `SendToRouteSync`, `SendPayment`, and `SendPaymentSync` in Release 0.19
  docs/release-notes/release-notes-0.19.0.md
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lnrpc/lightning_grpc.pb.go
Labels: rpc

#9459 invoices: amp invoices bugfix.
  channeldb/invoices.go
  docs/release-notes/release-notes-0.18.5.md
  invoices/interface.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/sql_store.go
  invoices/update_invoice.go
Labels: bug fix, amp, invoices

#9460 release: create branch for v0.18.5-beta.rc1
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .golangci.yml
  Dockerfile
  Makefile
  batch/batch.go
  batch/batch_test.go
  build/version.go
  channeldb/graph.go
  cmd/commands/commands.go
  cmd/commands/walletrpc_active.go
  dev.Dockerfile
  docker/btcd/Dockerfile
  docs/release-notes/release-notes-0.18.5.md
  go.mod
  go.sum
  htlcswitch/interfaces.go
  htlcswitch/link.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/invoices.go
  invoices/mock.go
  invoices/modification_interceptor.go
  invoices/resolution_result.go
  invoices/test_utils_test.go
  invoices/update.go
  itest/list_on_test.go
  itest/lnd_forward_interceptor_test.go
  itest/lnd_invoice_acceptor_test.go
  itest/lnd_multi-hop-payments_test.go
  kvdb/go.mod
  kvdb/go.sum
  kvdb/postgres/db.go
  kvdb/sqlbase/db.go
  kvdb/sqlbase/readwrite_tx.go
  lnrpc/Dockerfile
  lnrpc/gen_protos_docker.sh
  lnrpc/invoicesrpc/utils.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  log.go
  make/builder.Dockerfile
  routing/bandwidth_test.go
  routing/localchans/log.go
  routing/localchans/manager.go
  routing/localchans/manager_test.go
  routing/payment_lifecycle.go
  rpcserver.go
  server.go
  sqldb/interfaces.go
  sqldb/sqlerrors.go
  tools/Dockerfile
Labels: golang/build system, releases, no-changelog
