Repository lightningnetwork/lnd, pull requests merged in 2025-03, with the labels that each got.

#9565 GitHub+docs: no longer accept typo fixes to fight PR spam
  .github/pull_request_template.md
  docs/code_contribution_guidelines.md
Labels: no-itest, no-changelog

#9571 lnwallet+protofsm: fix logging
  lnwallet/chancloser/rbf_coop_transitions.go
  protofsm/state_machine.go
Labels: no-itest, no-changelog

#9576 build: add yaml tags to some LogConfig fields
  build/config.go
  build/config_dev.go
  build/config_prod.go
Labels: no-changelog

#9568 lnwallet: update RBF state machine w/ latest spec guidelines
  lnwallet/chancloser/rbf_coop_states.go
  lnwallet/chancloser/rbf_coop_test.go
  lnwallet/chancloser/rbf_coop_transitions.go
  lnwallet/channel.go
  lnwallet/channel_test.go
  lnwire/closing_complete.go
  lnwire/closing_sig.go
  lnwire/lnwire_test.go
  protofsm/state_machine.go
Labels: rbf, no-changelog

#9577 graph: move topology subscription to `ChannelGraph`
  autopilot/manager.go
  docs/release-notes/release-notes-0.19.0.md
  docs/release-notes/release-notes-0.20.0.md
  graph/builder.go
  graph/db/graph.go
  graph/db/graph_test.go
  graph/db/notifications.go
  graph/notifications_test.go
  pilot.go
  rpcserver.go
  server.go
Labels: graph, refactoring

#9574 lntest: wait for ChanUpdate req to be fully processed before sending another
  docs/release-notes/release-notes-0.19.0.md
  lntest/node/watcher.go
Labels: test flake, flake fix

#9586 config: only create a sub-log manager if one doesnt already exist
  config.go
Labels: no-changelog

#9573 discovery: obtain channelMtx before doing any DB calls in `handleChannelUpdate`
  discovery/gossiper.go
  discovery/gossiper_test.go
  docs/release-notes/release-notes-0.19.0.md
Labels: graph, gossip, flake fix

#9582 itest: properly document the known flakes
  itest/flakes.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_funding_test.go
  itest/lnd_hold_invoice_force_test.go
  itest/lnd_misc_test.go
  itest/lnd_multi-hop_force_close_test.go
  itest/lnd_network_test.go
  itest/lnd_payment_test.go
  itest/lnd_sweep_test.go
  itest/lnd_test.go
Labels: itests, flake fix, no-changelog, size/micro

#9581 tor: fix `TestReconnectSucceed`
  tor/controller_test.go
Labels: flake fix, no-itest, no-changelog

#9597 contractcourt: fix rebase issue with removed variadic option
  contractcourt/commit_sweep_resolver.go
  contractcourt/htlc_lease_resolver.go
Labels: no-changelog

#9563 chanbackup: fix test flake in `TestUpdateAndSwap`
  chanbackup/backupfile_test.go
Labels: flake fix, no-itest, no-changelog, size/micro

#9595 multi: fix flakes and gossip syncer
  discovery/syncer.go
  discovery/syncer_test.go
  docs/release-notes/release-notes-0.19.0.md
  itest/lnd_forward_interceptor_test.go
  lnrpc/routerrpc/forward_interceptor.go
  tor/controller_test.go
Labels: tor, gossip, flake fix, size/micro

#9606 config: rename skip-sql-invoice-migration to skip-native-sql-migration
  config_builder.go
  docs/release-notes/release-notes-0.19.0.md
  lncfg/db.go
  sample-lnd.conf
Labels: config

#9605 cmd: fix error parsed from status
  cmd/commands/commands.go
  docs/release-notes/release-notes-0.19.0.md
Labels: wallet, cli, size/micro

#9601 lnd: pass through neutrino MaxPeers config
  config.go
  config_builder.go
  docs/release-notes/release-notes-0.19.0.md
  sample-lnd.conf
Labels: config, neutrino, bug fix, size/micro

#9600 lntest+itest: document and fix more flakes
  go.mod
  go.sum
  itest/flakes.go
  itest/lnd_channel_backup_test.go
  itest/lnd_coop_close_with_htlcs_test.go
  itest/lnd_open_channel_test.go
  itest/lnd_route_blinding_test.go
  itest/lnd_sweep_test.go
  itest/lnd_wipe_fwdpkgs_test.go
  lntest/harness_assertion.go
Labels: flake fix, no-changelog, size/micro

#9602 multi: make sure HTLCs are locked in the itest
  contractcourt/chain_watcher.go
  contractcourt/channel_arbitrator.go
  docs/release-notes/release-notes-0.19.0.md
  htlcswitch/link.go
  htlcswitch/switch.go
  itest/flakes.go
  itest/lnd_multi-hop_force_close_test.go
  itest/lnd_sweep_test.go
  lnrpc/lightning.pb.go
  lnrpc/lightning.proto
  lnrpc/lightning.swagger.json
  lntest/harness_assertion.go
  netann/chan_status_manager_test.go
  peer/brontide.go
  rpcserver.go
Labels: rpc, htlcswitch, flake fix, size/micro

#9609 Fix inaccurate `listunspent` result
  docs/release-notes/release-notes-0.19.0.md
  go.mod
  go.sum
  itest/flakes.go
  itest/list_exclude_test.go
  itest/lnd_multi-hop_force_close_test.go
  itest/lnd_sweep_test.go
  lnwallet/btcwallet/btcwallet.go
  lnwallet/btcwallet/log.go
  lnwallet/btcwallet/signer.go
  lnwallet/log.go
  log.go
  sqldb/interfaces.go
  sweep/fee_bumper.go
  sweep/sweeper.go
Labels: wallet, bug fix, flake fix, size/kilo

#9623 Size msg test msg
  .gitignore
  lnwire/accept_channel.go
  lnwire/announcement_signatures.go
  lnwire/announcement_signatures_2.go
  lnwire/channel_announcement.go
  lnwire/channel_announcement_2.go
  lnwire/channel_ready.go
  lnwire/channel_reestablish.go
  lnwire/channel_update.go
  lnwire/channel_update_2.go
  lnwire/closing_complete.go
  lnwire/closing_sig.go
  lnwire/closing_signed.go
  lnwire/commit_sig.go
  lnwire/custom.go
  lnwire/dyn_ack.go
  lnwire/dyn_propose.go
  lnwire/dyn_reject.go
  lnwire/error.go
  lnwire/funding_created.go
  lnwire/funding_signed.go
  lnwire/gossip_timestamp_range.go
  lnwire/init_message.go
  lnwire/kickoff_sig.go
  lnwire/lnwire_test.go
  lnwire/message.go
  lnwire/node_announcement.go
  lnwire/open_channel.go
  lnwire/ping.go
  lnwire/pong.go
  lnwire/query_channel_range.go
  lnwire/query_short_chan_ids.go
  lnwire/reply_channel_range.go
  lnwire/reply_short_chan_ids_end.go
  lnwire/revoke_and_ack.go
  lnwire/serialized_size_test.go
  lnwire/shutdown.go
  lnwire/stfu.go
  lnwire/test_message.go
  lnwire/test_utils.go
  lnwire/update_add_htlc.go
  lnwire/update_fail_htlc.go
  lnwire/update_fail_malformed_htlc.go
  lnwire/update_fee.go
  lnwire/update_fulfill_htlc.go
  lnwire/warning.go
Labels: wire protocol, tests, no-changelog

#9543 multi: fix payment failure overwrite
  docs/release-notes/release-notes-0.19.0.md
  itest/list_on_test.go
  itest/lnd_trackpayments_test.go
  routing/control_tower.go
  routing/router.go
  routing/router_test.go
Labels: notifications, payments

#9642 lnd: skip setting `blockbeat` for `nochainbackend` mode
  server.go
Labels: no-changelog, size/nano

#9645 docs: update release notes with contributors
  docs/release-notes/release-notes-0.19.0.md
Labels: no-itest, no-changelog

#9649 cmd: fix incorrect error code
  cmd/commands/commands.go
Labels: no-itest, no-changelog

#9627 Sweep inputs even the budget cannot be covered
  docs/release-notes/release-notes-0.19.0.md
  itest/list_on_test.go
  itest/lnd_funding_test.go
  itest/lnd_multi-hop_force_close_test.go
  itest/lnd_sweep_test.go
  lntest/harness.go
  lntest/harness_miner.go
  rpcserver.go
  sweep/fee_bumper.go
  sweep/fee_bumper_test.go
  sweep/sweeper.go
  sweep/sweeper_test.go
  sweep/tx_input_set.go
  sweep/tx_input_set_test.go
Labels: utxo sweeping, size/kilo

#9650 lnwallet/chancloser: fix flake in TestRbfChannelFlushingTransitions/early_offer
  lnwallet/chancloser/rbf_coop_test.go
  protofsm/state_machine.go
Labels: bug fix, no-changelog

#9654 mod: use sqldb v1.0.8
  go.mod
  go.sum
Labels: golang/build system, no-changelog
