Repository lightningnetwork/lnd, pull requests merged in 2025-02, with the labels that each got.

#9438 channeldb+lnd: set invoice bucket tombstone after migration
  channeldb/invoice_test.go
  channeldb/invoices.go
  config_builder.go
  docs/release-notes/release-notes-0.19.0.md
  itest/lnd_invoice_migration_test.go
Labels: enhancement, database, invoices

#9469 build: use the tagged 1.0.7 version of sqldb
  go.mod
  go.sum
Labels: no-changelog

#9482 lntest: log timestamp when printing errors
  lntest/node/harness_node.go
Labels: flake fix, no-changelog, size/nano

#9476 graph: refactor `graph.Builder` update handling
  discovery/gossiper.go
  docs/release-notes/release-notes-0.19.0.md
  graph/ann_validation.go
  graph/builder.go
  graph/stats.go
  netann/node_announcement.go
Labels: code health, graph, refactoring

#9470 Make BumpFee RPC user inputs more stricter.
  cmd/commands/walletrpc_active.go
  docs/release-notes/release-notes-0.18.5.md
  itest/lnd_onchain_test.go
  itest/lnd_sweep_test.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
Labels: utxo sweeping

#9492 itest: fix flake in `testForwardInterceptorRestart`
  itest/lnd_forward_interceptor_test.go
Labels: itests, flake fix, no-changelog, size/micro

#9477 discovery+graph: various preparations for moving funding tx validation to the gossiper
  discovery/gossiper.go
  discovery/gossiper_test.go
  docs/release-notes/release-notes-0.19.0.md
  graph/builder.go
  graph/builder_test.go
  graph/errors.go
  lnmock/chain.go
Labels: graph, refactoring

#9495 fix graphbuilder flake
  graph/builder_test.go
  graph/notifications_test.go
Labels: no-itest, no-changelog

#9480 graph+autopilot: remove `autopilot` access to raw `graphdb.ChannelGraph`
  autopilot/graph.go
  autopilot/interface.go
  autopilot/prefattach_test.go
  docs/release-notes/release-notes-0.19.0.md
  graph/builder.go
  graph/db/graph.go
  graph/db/graph_cache_test.go
  graph/db/graph_test.go
  graph/db/interfaces.go
  graph/interfaces.go
  rpcserver.go
Labels: graph, interface abstraction

#9472 release: make v0.18.5 rc2 branch
  build/version.go
  channeldb/invoices.go
  cmd/commands/walletrpc_active.go
  docs/release-notes/release-notes-0.18.5.md
  invoices/interface.go
  invoices/invoiceregistry.go
  invoices/invoiceregistry_test.go
  invoices/sql_store.go
  invoices/update_invoice.go
  itest/lnd_onchain_test.go
  itest/lnd_sweep_test.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  routing/localchans/manager.go
Labels: releases, no-changelog

#9500 doc: creating release-notes-0.20.0.md
  docs/release-notes/release-notes-0.20.0.md
Labels: no-changelog

#9503 release: bump version to v0.18.5
  build/version.go
Labels: releases

#9150 routing+htlcswitch: fix stuck inflight payments
  channeldb/mp_payment.go
  channeldb/mp_payment_test.go
  channeldb/payment_control_test.go
  channeldb/payments_test.go
  docs/release-notes/release-notes-0.19.0.md
  itest/lnd_multi-hop_force_close_test.go
  lntest/harness_assertion.go
  routing/control_tower_test.go
  routing/payment_lifecycle.go
  routing/payment_lifecycle_test.go
  routing/router.go
  routing/router_test.go
Labels: payments, bug fix, size/kilo

#9496 graph: remove redundant iteration through a node's persisted channels
  docs/release-notes/release-notes-0.19.0.md
  graph/db/graph.go
  graph/db/graph_cache.go
  graph/db/graph_cache_test.go
  graph/db/graph_test.go
Labels: graph, interface abstraction, performance

#9508 .github: ignore Send coverage errors
  .github/workflows/main.yml
Labels: no-changelog

#9478 discovery+graph: move funding tx validation to the gossiper
  discovery/gossiper.go
  discovery/gossiper_test.go
  docs/release-notes/release-notes-0.19.0.md
  graph/builder.go
  graph/builder_test.go
  graph/db/models/channel_edge_info.go
  graph/errors.go
  graph/interfaces.go
  graph/notifications_test.go
  server.go
Labels: graph, gossip, refactoring, validation

#9517 workflows: skip coverage error in job `finish`
  .github/workflows/main.yml
Labels: no-changelog

#9493 For some lncli cmds we should not replace the content with other data
  cmd/commands/cmd_payments.go
  cmd/commands/commands.go
Labels: no-itest, no-changelog

#9515 graph: ensure topology subscriber handling and network msg handling is synchronous
  graph/builder.go
Labels: flake fix, no-changelog

#9516 invoicesrpc: remove direct access to ChannelGraph pointer
  docs/release-notes/release-notes-0.19.0.md
  lnrpc/invoicesrpc/addinvoice.go
  lnrpc/invoicesrpc/config_active.go
  lnrpc/invoicesrpc/interfaces.go
  lnrpc/invoicesrpc/invoices_server.go
  subrpcserver_config.go
Labels: interface abstraction

#9512 multi: update build system to Go 1.23
  .github/workflows/main.yml
  .github/workflows/release.yaml
  .golangci.yml
  Dockerfile
  Makefile
  autopilot/prefattach_test.go
  dev.Dockerfile
  docker/btcd/Dockerfile
  docs/INSTALL.md
  go.mod
  graph/db/graph.go
  invoices/sql_migration_test.go
  lnrpc/Dockerfile
  lnrpc/gen_protos_docker.sh
  make/builder.Dockerfile
  tools/.custom-gcl.yml
  tools/Dockerfile
  tools/go.mod
  tools/go.sum
  tools/linters/go.mod
  tools/linters/go.sum
Labels: no-changelog

#9518 walletrpc: fix description of bumpfee.immediate
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
Labels: inline documentation, no-itest, no-changelog

#9513 graph+routing: refactor to remove `graphsession`
  docs/release-notes/release-notes-0.19.0.md
  graph/db/graph.go
  graph/db/graph_test.go
  graph/db/interfaces.go
  graph/graphsession/graph_session.go
  routing/bandwidth.go
  routing/graph.go
  routing/integrated_routing_context_test.go
  routing/integrated_routing_test.go
  routing/mock_graph_test.go
  routing/pathfind.go
  routing/pathfind_test.go
  routing/payment_session.go
  routing/payment_session_test.go
  routing/router_test.go
  routing/unified_edges.go
  rpcserver.go
  server.go
Labels: routing, graph, interface abstraction, refactoring

#9525 graph: Restrict interface to update channel proof instead of entire channel
  graph/builder.go
  graph/db/graph.go
  graph/interfaces.go
Labels: graph, no-changelog

#9448 sweep: properly handle failed sweeping txns
  contractcourt/anchor_resolver.go
  docs/release-notes/release-notes-0.19.0.md
  itest/list_on_test.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_sweep_test.go
  sweep/fee_bumper.go
  sweep/fee_bumper_test.go
  sweep/mock_test.go
  sweep/store.go
  sweep/store_test.go
  sweep/sweeper.go
  sweep/sweeper_test.go
Labels: utxo sweeping

#9530 multi: fix debug log
  htlcswitch/link.go
  lnwallet/channel.go
Labels: no-itest, no-changelog

#9447 sweep: start tracking input spending status in the fee bumper
  chainntnfs/mempool.go
  contractcourt/anchor_resolver.go
  docs/release-notes/release-notes-0.19.0.md
  itest/list_on_test.go
  itest/lnd_channel_force_close_test.go
  itest/lnd_sweep_test.go
  sweep/fee_bumper.go
  sweep/fee_bumper_test.go
  sweep/mock_test.go
  sweep/store.go
  sweep/store_test.go
  sweep/sweeper.go
  sweep/sweeper_test.go
Labels: utxo sweeping, size/micro

#9535 GitHub: remove duplicate caching
  .github/actions/setup-go/action.yml
Labels: no-itest, no-changelog

#9534 graph: refactor Builder network message handling
  graph/builder.go
Labels: graph, refactoring, no-changelog

#8900 Makefile: add GOCC variable
  Makefile
  make/release_flags.mk
  make/testing_flags.mk
Labels: no-changelog

#9545 graph: extract cache from CRUD [2]
  autopilot/prefattach_test.go
  config_builder.go
  docs/release-notes/release-notes-0.19.0.md
  graph/db/graph.go
  graph/db/graph_test.go
  graph/db/kv_store.go
  graph/db/options.go
  graph/notifications_test.go
  peer/test_utils.go
  routing/pathfind_test.go
Labels: graph

#9550 graph: extract cache from CRUD [3]
  docs/release-notes/release-notes-0.19.0.md
  graph/db/graph.go
  graph/db/graph_test.go
  graph/db/kv_store.go
Labels: graph

#9549 Fix unit test flake `TestHistoricalConfDetailsTxIndex`
  Makefile
  chainntnfs/bitcoindnotify/bitcoind_test.go
  chainntnfs/test/test_interface.go
  docs/release-notes/release-notes-0.19.0.md
  lntest/unittest/backend.go
  lnwallet/test/test_interface.go
  routing/chainview/interface_test.go
  scripts/unit-test-flake-hunter.sh
Labels: flake fix, size/micro

#9551 graph: extract cache from CRUD [4]
  docs/release-notes/release-notes-0.19.0.md
  graph/db/graph.go
  graph/db/kv_store.go
Labels: graph

#9555 graph: extract cache from CRUD [6]
  autopilot/prefattach_test.go
  docs/release-notes/release-notes-0.19.0.md
  graph/db/graph.go
  graph/db/graph_test.go
  graph/db/kv_store.go
  graph/notifications_test.go
  peer/test_utils.go
  routing/pathfind_test.go
  server.go
Labels: graph

#9566 lntest+itest: change the method signature of `AssertPaymentStatus`
  itest/lnd_experimental_endorsement.go
  itest/lnd_forward_interceptor_test.go
  itest/lnd_hold_persistence_test.go
  itest/lnd_htlc_timeout_resolver_test.go
  itest/lnd_mpp_test.go
  itest/lnd_multi-hop_force_close_test.go
  itest/lnd_payment_test.go
  itest/lnd_route_blinding_test.go
  lntest/harness_assertion.go
Labels: no-changelog, size/nano

#9521 unit: remove GOACC, use Go 1.20 native coverage functionality
  .github/workflows/main.yml
  .github/workflows/release.yaml
  Makefile
  make/builder.Dockerfile
  make/testing_flags.mk
  scripts/release.sh
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: no-changelog

#9559 multi: preliminary changes towards integrating the new RBF close protocol feature
  channeldb/channel.go
  contractcourt/chain_watcher.go
  feature/default_sets.go
  htlcswitch/interfaces.go
  htlcswitch/switch.go
  input/fuzz_script_is_op_return_test.go
  input/script_utils.go
  lnwallet/chancloser/rbf_coop_msg_mapper.go
  lnwallet/chancloser/rbf_coop_states.go
  lnwallet/chancloser/rbf_coop_test.go
  lnwallet/channel.go
  lnwire/features.go
  log.go
  peer/brontide.go
  peer/brontide_test.go
  peer/chan_observer.go
  peer/daemon_adapters.go
  peer/test_utils.go
  protofsm/msg_mapper.go
  protofsm/state_machine.go
  protofsm/state_machine_test.go
  rpcserver.go
  server.go
Labels: no-changelog
