Repository lightningnetwork/lnd, pull requests merged in 2025-04, with the labels that each got.

#9655 scripts+bw-compatibility-test: update Dave and make it use sqlite
  dev.Dockerfile
  scripts/bw-compatibility-test/docker-compose.override.yaml
  scripts/bw-compatibility-test/docker-compose.yaml
  scripts/bw-compatibility-test/network.sh
  scripts/bw-compatibility-test/test.sh
Labels: no-changelog

#9666 lnd: remove unnecessary debug log to avoid misunderstanding
  config_builder.go
Labels: no-changelog

#9665 kvdb: bump etcd libs to v3.5.12
  go.mod
  go.sum
  kvdb/etcd/embed.go
  kvdb/go.mod
  kvdb/go.sum
  lnrpc/autopilotrpc/autopilot.pb.gw.go
  lnrpc/autopilotrpc/autopilot.swagger.json
  lnrpc/chainrpc/chainkit.pb.gw.go
  lnrpc/chainrpc/chainkit.swagger.json
  lnrpc/chainrpc/chainnotifier.pb.gw.go
  lnrpc/chainrpc/chainnotifier.swagger.json
  lnrpc/devrpc/dev.pb.gw.go
  lnrpc/devrpc/dev.swagger.json
  lnrpc/invoicesrpc/invoices.pb.gw.go
  lnrpc/invoicesrpc/invoices.swagger.json
  lnrpc/lightning.pb.gw.go
  lnrpc/lightning.swagger.json
  lnrpc/lnclipb/lncli.swagger.json
  lnrpc/neutrinorpc/neutrino.pb.gw.go
  lnrpc/neutrinorpc/neutrino.swagger.json
  lnrpc/peersrpc/peers.pb.gw.go
  lnrpc/peersrpc/peers.swagger.json
  lnrpc/routerrpc/router.pb.gw.go
  lnrpc/routerrpc/router.swagger.json
  lnrpc/signrpc/signer.pb.gw.go
  lnrpc/signrpc/signer.swagger.json
  lnrpc/stateservice.pb.gw.go
  lnrpc/stateservice.swagger.json
  lnrpc/verrpc/verrpc.pb.gw.go
  lnrpc/verrpc/verrpc.swagger.json
  lnrpc/walletrpc/walletkit.pb.gw.go
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletunlocker.pb.gw.go
  lnrpc/walletunlocker.swagger.json
  lnrpc/watchtowerrpc/watchtower.pb.gw.go
  lnrpc/watchtowerrpc/watchtower.swagger.json
  lnrpc/wtclientrpc/wtclient.pb.gw.go
  lnrpc/wtclientrpc/wtclient.swagger.json
Labels: golang/build system, maintenance, no-changelog

#9669 multi: downgrade to legacy coop close for taproot channels
  itest/list_on_test.go
  itest/lnd_coop_close_with_htlcs_test.go
  lncfg/protocol.go
  lntest/node/config.go
  peer/brontide.go
  server.go
Labels: channel closing, taproot, taproot chans, no-changelog

#9672 kvdb/sqlite: enable incremental auto_vacuum on DB creation
  go.mod
  go.sum
  kvdb/sqlite/db.go
  sqldb/sqlite.go
Labels: kvdb, no-changelog, sqlite

#9681 macaroons+kvdb: improve signal-to-noise ratio of `context.TODO`
  kvdb/backend.go
  kvdb/etcd/db_test.go
  kvdb/etcd/fixture.go
  kvdb/etcd/readwrite_tx_test.go
  kvdb/etcd/walletdb_interface_test.go
  macaroons/service_test.go
  macaroons/store_test.go
Labels: code health, refactoring, no-changelog

#9680 discovery: thread context through in preparation for passing to graph DB
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/reliable_sender.go
  discovery/reliable_sender_test.go
  lnd.go
  server.go
Labels: graph, refactoring, no-changelog

#9689 chainrpc: fix description of several methods
  lnrpc/chainrpc/chain_server.go
Labels: no-itest, no-changelog

#9685 discovery: thread contexts through syncer, sync manager and reliable sender
  discovery/bootstrapper.go
  discovery/gossiper.go
  discovery/gossiper_test.go
  discovery/sync_manager.go
  discovery/sync_manager_test.go
  discovery/syncer.go
  discovery/syncer_test.go
  peer/brontide.go
  server.go
Labels: code health, no-changelog

#9694 graph/db: clean up test code in preparation for DB abtraction
  graph/db/graph_test.go
Labels: no-changelog

#9690 autopilot: thread contexts through in preparation for GraphSource methods taking a context
  autopilot/agent.go
  autopilot/agent_test.go
  autopilot/betweenness_centrality.go
  autopilot/betweenness_centrality_test.go
  autopilot/combinedattach.go
  autopilot/externalscoreattach.go
  autopilot/externalscoreattach_test.go
  autopilot/graph.go
  autopilot/interface.go
  autopilot/manager.go
  autopilot/prefattach.go
  autopilot/prefattach_test.go
  autopilot/simple_graph.go
  autopilot/top_centrality.go
  autopilot/top_centrality_test.go
  discovery/bootstrapper.go
  lnd.go
  lnrpc/autopilotrpc/autopilot_server.go
  rpcserver.go
Labels: no-changelog

#9705 lntest: assert shutdown via logs only if log file handle is present
  lntest/node/harness_node.go
Labels: bug, itests, no-changelog

#9696 Add `development_guidelines.md` for both human and machine
  .github/pull_request_template.md
  docs/code_contribution_guidelines.md
  docs/code_formatting_rules.md
  docs/development_guidelines.md
  docs/review.md
Labels: documentation, no-itest, no-changelog, size/micro

#9703 Patch htlc attempt hash for legacy payments
  docs/release-notes/release-notes-0.19.0.md
  routing/payment_lifecycle.go
  routing/payment_lifecycle_test.go
Labels: payments

#9684 multi: update new walletdb version in main go.mod and kvdb go.mod
  aliasmgr/aliasmgr_test.go
  batch/batch_test.go
  channeldb/forwarding_package_test.go
  channeldb/migration_01_to_11/db.go
  channeldb/migtest/migtest.go
  config_builder.go
  contractcourt/briefcase_test.go
  contractcourt/channel_arbitrator_test.go
  go.mod
  go.sum
  htlcswitch/resolution_store_test.go
  kvdb/backend.go
  kvdb/backend_js.go
  kvdb/bolt_fixture.go
  kvdb/go.mod
  kvdb/go.sum
  kvdb/interface.go
  lntest/unittest/backend.go
  lnwallet/test/test_interface.go
  macaroons/service_test.go
  macaroons/store_test.go
  routing/chainview/interface_test.go
  routing/integrated_routing_context_test.go
  routing/missioncontrol_store_test.go
  routing/missioncontrol_test.go
  walletunlocker/service_test.go
Labels: dependencies, no-changelog

#9710 graph+channeldb: test clean-up in preparation for different graph DB backend
  channeldb/db_test.go
  channeldb/meta_test.go
  graph/builder_test.go
  graph/db/graph_test.go
  graph/notifications_test.go
Labels: code health, graph, tests, no-changelog

#9712 mod: bump kvdb to v1.4.15
  go.mod
  go.sum
Labels: no-changelog

#9714 invoices: reduce log spam when migrating invoices to SQL
  invoices/sql_migration.go
Labels: logging, no-changelog

#9720 chainntnfs: increase logging of the subsystems
  chainntnfs/bitcoindnotify/bitcoind.go
  chainntnfs/btcdnotify/btcd.go
  chainntnfs/neutrinonotify/neutrino.go
Labels: no-itest, no-changelog

#9715 itest: remove manual channel closures from route blinding tests
  itest/lnd_route_blinding_test.go
Labels: no-changelog

#9727 Aux bandwidth manager: also pass HTLC blob to `ShouldHandleTraffic`
  htlcswitch/interfaces.go
  htlcswitch/link.go
  htlcswitch/switch.go
  routing/bandwidth_test.go
Labels: no-itest, no-changelog

#9724 walletrpc: allow custom lock ID and duration in `FundPsbt`
  docs/release-notes/release-notes-0.19.0.md
  itest/list_on_test.go
  itest/lnd_psbt_test.go
  lnrpc/walletrpc/psbt.go
  lnrpc/walletrpc/walletkit.pb.go
  lnrpc/walletrpc/walletkit.proto
  lnrpc/walletrpc/walletkit.swagger.json
  lnrpc/walletrpc/walletkit_server.go
  lnrpc/walletrpc/walletkit_server_test.go
  lntest/rpc/wallet_kit.go
  lntest/utils.go
Labels: rpc, psbt

#9722 Change RPC call order for the btcd notifier
  chainntnfs/btcdnotify/btcd.go
Labels: flake fix, no-changelog

#9723 Add the global lock for the wallet db back for postgres
  docs/release-notes/release-notes-0.19.0.md
  go.mod
  go.sum
  kvdb/postgres/config.go
  kvdb/postgres/db.go
  kvdb/sqlbase/db.go
  kvdb/sqlbase/readwrite_tx.go
  lncfg/db.go
Labels: database, kvdb, postgres

#9734 Improve logging when fetching invoices and payments
  channeldb/invoices.go
  channeldb/payment_control.go
  channeldb/payments.go
  cmd/commands/cmd_payments.go
  invoices/invoiceregistry.go
  invoices/sql_store.go
  routing/control_tower.go
  routing/router.go
Labels: payments, logging, invoices, no-changelog, size/micro

#9719 accessman: add logging to new sub-system
  accessman.go
  lnutils/log.go
  log.go
Labels: no-changelog

#9749 mulit: increase logprogress time
  channeldb/invoices.go
  channeldb/payment_control.go
  channeldb/payments.go
  invoices/sql_store.go
Labels: no-changelog

#9746 lnwallet: no need to consult the aux unit for legacy channels
  docs/release-notes/release-notes-0.19.0.md
  lnwallet/channel.go
Labels: channel closing, custom chans

#9755 htlcswitch+routing: add funding blob to PaymentBandwidth
  htlcswitch/interfaces.go
  htlcswitch/link.go
  routing/bandwidth_test.go
Labels: no-changelog

#9736 build: bump version to v0.19.0 rc3
  build/version.go
  go.mod
  go.sum
Labels: no-itest, no-changelog

#9759 GitHub: fix order of operations for release build
  .github/workflows/release.yaml
Labels: no-changelog

#9776 docs: update release notes with more detail on the RBF coop close section
  docs/release-notes/release-notes-0.19.0.md
Labels: documentation, no-itest, no-changelog
